//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, QQHttpClientSession, UIImage;

@interface AddFriendSendMsgHeaderUpload : NSObject
{
    QQHttpClientSession *_session;
    unsigned int _uploadError;
    id <AddFriendSendMsgHeaderUploadDelegate> _theDelegate;
    UIImage *_image;
    UIImage *_thumbImage;
    double _process;
    NSString *_url;
    NSString *_fileName;
    unsigned long long _groupCode;
    NSString *_httpMethod;
}

- (void)cancelUpLoad;
- (void)cancelUpLoadWithError:(unsigned int)arg1;
- (void)dealloc;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
- (int)getBkn;
- (id)getParams;
- (id)getUrlRequest:(id)arg1 Cookie:(id)arg2;
@property(nonatomic) unsigned long long groupCode; // @synthesize groupCode=_groupCode;
@property(copy, nonatomic) NSString *httpMethod; // @synthesize httpMethod=_httpMethod;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (id)initWithDelegate:(id)arg1;
- (_Bool)judgeParamsFit;
@property(nonatomic) double process; // @synthesize process=_process;
- (void)qqHttpClientSessionFailWithError:(id)arg1 error:(id)arg2;
- (void)qqHttpClientSessionRequestDidLoad:(id)arg1 respObj:(id)arg2;
@property(nonatomic) id <AddFriendSendMsgHeaderUploadDelegate> theDelegate; // @synthesize theDelegate=_theDelegate;
@property(retain, nonatomic) UIImage *thumbImage; // @synthesize thumbImage=_thumbImage;
@property(nonatomic) unsigned int uploadError; // @synthesize uploadError=_uploadError;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
- (_Bool)startUpLoad;
- (void)uploadbytes:(long long)arg1 expected:(long long)arg2;

@end

