//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSString, QQAsynUrlImageView, UIButton, UILabel, UIView;

@interface ADPopupPanel : UIControl
{
    NSString *_pic;
    NSString *_desc;
    NSString *_buttonTitle;
    NSString *_openURL;
    UIView *_panel;
    QQAsynUrlImageView *_urlImageView;
    UILabel *_descLabel;
    UIButton *_bigButton;
    UIButton *_closeButton;
    int _reportKey;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1 pic:(id)arg2 desc:(id)arg3 buttonTitle:(id)arg4 openURL:(id)arg5 btnBgColor:(id)arg6;
- (void)layoutSubviews;
- (void)onClick;
- (void)onClose;
@property(nonatomic) int reportKey; // @synthesize reportKey=_reportKey;

@end

