//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQGroupPropertyModel.h"

@class APMidasEnteryViewController, APMidasWechatPaySignBiz;

@interface APMidasPageEntery : QQGroupPropertyModel
{
    APMidasEnteryViewController *pageEnteryCtrl;
    id <APMidasPayDelegate> payDelegate;
}

+ (id)instance;
- (void).cxx_destruct;
- (void)flowQuery:(id)arg1;
- (_Bool)initAcctSave:(id)arg1;
- (void)initCommonParams:(id)arg1;
- (_Bool)initGoods:(id)arg1;
- (_Bool)initMonth:(id)arg1;
- (void)lauch:(id)arg1 delegate:(id)arg2;
- (void)net:(id)arg1 delegate:(id)arg2;
@property(retain, nonatomic) APMidasEnteryViewController *pageEnteryCtrl; // @synthesize pageEnteryCtrl;
@property(nonatomic) __weak id <APMidasPayDelegate> payDelegate; // @synthesize payDelegate;
- (void)processWechatPayResult:(id)arg1;
- (void)processWechatSign:(_Bool)arg1;
- (void)wechatPaySign:(id)arg1;

// Remaining properties
@property(retain, nonatomic) APMidasWechatPaySignBiz *paySignBiz; // @dynamic paySignBiz;

@end

