//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ARBinhaiProgressView, UILabel;

@interface ARBinhaiTimeView : UIView
{
    ARBinhaiProgressView *_progress;
    UIView *_tbgView;
    UILabel *_label;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1 resourcePath:(id)arg2;
- (void)updateTime:(int)arg1 progress:(double)arg2;

@end

