//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary, NSMutableArray, NSString;

@interface ArkAppCGIQueryTask : NSObject
{
    _Bool _success;
    int _type;
    NSString *_url;
    NSMutableArray *_callbackList;
    NSDictionary *_requestHeader;
    NSDictionary *_responseHeader;
    NSString *_path;
    NSData *_reqData;
    NSData *_rspData;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableArray *callbackList; // @synthesize callbackList=_callbackList;
- (void)doCallback;
- (id)init;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
@property(retain, nonatomic) NSData *reqData; // @synthesize reqData=_reqData;
@property(retain, nonatomic) NSDictionary *requestHeader; // @synthesize requestHeader=_requestHeader;
@property(retain, nonatomic) NSDictionary *responseHeader; // @synthesize responseHeader=_responseHeader;
@property(retain, nonatomic) NSData *rspData; // @synthesize rspData=_rspData;
@property(nonatomic) _Bool success; // @synthesize success=_success;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;

@end

