//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CADisplayLink, UIImageView;

@interface ARMapWGHandGuiderView : UIView
{
    UIImageView *_handView;
    CADisplayLink *_link;
    _Bool _showing;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)dismiss;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)refresh;
@property(nonatomic) _Bool showing; // @synthesize showing=_showing;
- (void)setup;
- (void)show;
- (void)startAnimation;
- (void)startDisplayLink;
- (void)stopDisplayLink;

@end

