//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ARMapCountAnimView, NSDateFormatter, NSString, NSTimer, UILabel;

@interface ARMapCountView : UIView
{
    ARMapCountAnimView *_animView;
    UILabel *_regionLabel;
    UILabel *_countLabel;
    UILabel *_countRightLabel;
    NSDateFormatter *_dateFormatter;
    NSTimer *_timer;
    double _beginTime;
    int _hongBaoCount;
    NSString *_region;
    unsigned char isStartHongbao;
    int _curState;
    NSTimer *_countReduceTimer;
    int _currCount;
    int _toCount;
    int _reduceCount;
    unsigned long long _lastBegintime;
    int _lastAdcode;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)didMoveToSuperview;
- (id)formattedNumber:(unsigned long long)arg1;
- (id)getURLWithURL:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)scheduleDidChange:(id)arg1;
- (void)singlePoiStatusChanged:(id)arg1;
- (void)startCountReduceTimer;
- (void)startTimerDown;
- (void)stopCountReduceTimer;
- (void)stopCountReduceTimerAndResetValue;
- (void)timeDowning;
- (void)topCloudTapAction:(id)arg1;
- (void)updateCountLabelWithFontSize:(int)arg1 text:(id)arg2;
- (void)updateCountReduce;

@end

