//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SAMRequestItem.h"

@class NSArray, NSData, NSDictionary, NSString;

@interface ARMapPOIRequestItem : SAMRequestItem
{
    _Bool _ret;
    int _accuracy;
    unsigned int _sigTime;
    unsigned int _fakePeriod;
    unsigned int _fakeTimes;
    unsigned int _flushDist;
    unsigned int _flushTime;
    unsigned int _awardRange;
    int _req_occasion;
    long long _lat;
    long long _lon;
    double _lbsSigLon;
    double _lbsSigLat;
    NSString *_lbsSig;
    NSString *_encryptSig;
    NSString *_adcode;
    NSDictionary *_fakeInfo;
    long long _appID;
    NSData *_cookie;
    void *_mapGame;
    long long _result;
    NSArray *_poiList;
    NSArray *_taskList;
    NSData *_respCookie;
    unsigned long long _bigScanTaskID;
    NSString *_bigScanJson;
    double _bigScanBeginTime;
    unsigned long long _animationTaskID;
    NSString *_animationUrl;
    NSString *_animationMd5;
    double _animationBeginTime;
    NSString *_preRegion;
    double _preTime;
}

- (void).cxx_destruct;
@property(nonatomic) int accuracy; // @synthesize accuracy=_accuracy;
@property(copy, nonatomic) NSString *adcode; // @synthesize adcode=_adcode;
@property(nonatomic) double animationBeginTime; // @synthesize animationBeginTime=_animationBeginTime;
@property(copy, nonatomic) NSString *animationMd5; // @synthesize animationMd5=_animationMd5;
@property(nonatomic) unsigned long long animationTaskID; // @synthesize animationTaskID=_animationTaskID;
@property(copy, nonatomic) NSString *animationUrl; // @synthesize animationUrl=_animationUrl;
@property(nonatomic) long long appID; // @synthesize appID=_appID;
@property(nonatomic) unsigned int awardRange; // @synthesize awardRange=_awardRange;
@property(nonatomic) double bigScanBeginTime; // @synthesize bigScanBeginTime=_bigScanBeginTime;
@property(retain, nonatomic) NSString *bigScanJson; // @synthesize bigScanJson=_bigScanJson;
@property(nonatomic) unsigned long long bigScanTaskID; // @synthesize bigScanTaskID=_bigScanTaskID;
- (id)cheatAppList;
@property(retain, nonatomic) NSData *cookie; // @synthesize cookie=_cookie;
@property(copy, nonatomic) NSString *encryptSig; // @synthesize encryptSig=_encryptSig;
@property(copy, nonatomic) NSDictionary *fakeInfo; // @synthesize fakeInfo=_fakeInfo;
@property(nonatomic) unsigned int fakePeriod; // @synthesize fakePeriod=_fakePeriod;
@property(nonatomic) unsigned int fakeTimes; // @synthesize fakeTimes=_fakeTimes;
@property(nonatomic) unsigned int flushDist; // @synthesize flushDist=_flushDist;
@property(nonatomic) unsigned int flushTime; // @synthesize flushTime=_flushTime;
- (char *)getRequestBuffer;
- (id)init;
@property(nonatomic) long long lat; // @synthesize lat=_lat;
@property(copy, nonatomic) NSString *lbsSig; // @synthesize lbsSig=_lbsSig;
@property(nonatomic) double lbsSigLat; // @synthesize lbsSigLat=_lbsSigLat;
@property(nonatomic) double lbsSigLon; // @synthesize lbsSigLon=_lbsSigLon;
@property(nonatomic) long long lon; // @synthesize lon=_lon;
@property(nonatomic) void *mapGame; // @synthesize mapGame=_mapGame;
- (id)notifyRespBuffer:(const char *)arg1 len:(int)arg2 seq:(int)arg3;
@property(retain, nonatomic) NSArray *poiList; // @synthesize poiList=_poiList;
@property(copy, nonatomic) NSString *preRegion; // @synthesize preRegion=_preRegion;
@property(nonatomic) double preTime; // @synthesize preTime=_preTime;
@property(nonatomic) int req_occasion; // @synthesize req_occasion=_req_occasion;
@property(retain, nonatomic) NSData *respCookie; // @synthesize respCookie=_respCookie;
@property(nonatomic) long long result; // @synthesize result=_result;
@property(nonatomic) _Bool ret; // @synthesize ret=_ret;
- (id)serviceCmd;
@property(nonatomic) unsigned int sigTime; // @synthesize sigTime=_sigTime;
@property(retain, nonatomic) NSArray *taskList; // @synthesize taskList=_taskList;

@end

