//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEngineDispatchDelegate.h"

@class NSMutableArray, NSString, NSTimer;

@interface asdtq2xahs : NSObject <IEngineDispatchDelegate>
{
    struct _QQSecAutoDtHandler *_asdhalksj3;
    NSMutableArray *_lslsfjk23j;
    NSTimer *_ttlmlnal3k;
    _Bool sb21knlsxc;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)ad549djkbn;
@property(nonatomic) struct _QQSecAutoDtHandler *asdhalksj3; // @synthesize asdhalksj3=_asdhalksj3;
- (void)dasl2zx46d;
- (void)dealloc;
- (void)dfjgkcnxmn:(id)arg1;
- (void)didRecievedMsg:(CDStruct_7895f40e)arg1;
- (void)dsadg3zk7e2;
- (id)init;
@property(retain, nonatomic) NSMutableArray *lslsfjk23j; // @synthesize lslsfjk23j=_lslsfjk23j;
- (void)notifyError:(id)arg1;
@property(retain, nonatomic) NSTimer *ttlmlnal3k; // @synthesize ttlmlnal3k=_ttlmlnal3k;
- (void)zxdqoidlnz:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

