//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AudioDecoder;

@interface AudioDecoderWrapper : NSObject
{
    AudioDecoder *_audioDecoders[2];
    int _channel;
    int _sampleRate;
    _Bool _forLearn;
    short *_zeroSamples;
}

- (void).cxx_destruct;
- (void)closeFiles;
- (void)dealloc;
- (int)getRealTotalFrames;
- (int)getTotalFrames;
- (id)init;
- (_Bool)openLeftFile:(id)arg1 rightFile:(id)arg2 sampleRate:(int)arg3 forLearn:(_Bool)arg4;
- (_Bool)readFile:(unsigned int *)arg1 leftSamples:(short **)arg2 rightSamples:(short **)arg3;
- (_Bool)readFile:(void *)arg1 outSize:(int)arg2;
- (void)setChannel:(int)arg1;

@end

