//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IAsynDownloadImageObserver.h"

@class NSMutableArray, NSString;

@interface AVFunDrawingMrg : NSObject <IAsynDownloadImageObserver>
{
    struct dispatch_queue_s *_queue;
    NSMutableArray *_downloadList;
    id <AVFunDrawingMrgDelegate> _delegate;
    NSMutableArray *_totalArray;
}

+ (id)basicPath;
+ (void)clearOldCache:(id)arg1;
+ (id)configPath;
+ (id)getConfigFromCache;
+ (id)getInstance;
+ (_Bool)isPackageExist:(id)arg1;
+ (id)itemArrayFrom:(id)arg1;
+ (id)packagePath:(id)arg1;
+ (void)preDownload:(id)arg1;
+ (void)saveConfigureation:(id)arg1;
+ (id)zipPath:(id)arg1;
- (void)dealloc;
@property(nonatomic) id <AVFunDrawingMrgDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didDownloadFail:(id)arg1;
- (void)downloadImageFinished:(id)arg1;
- (struct dispatch_queue_s *)getCustomQueue;
- (id)getDrawingToolsArrayWithIconPrepared:(_Bool)arg1;
- (id)init;
- (void)removeAllDrawingTools;
@property(retain, nonatomic) NSMutableArray *totalArray; // @synthesize totalArray=_totalArray;
- (void)startDownload:(id)arg1;
- (id)toStrByUIColor:(id)arg1;
- (id)toUIColorByStr:(id)arg1;
- (void)unZipPacket:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

