//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVGLImage, AVGLNickView, UIImageView;

@interface AVGLRenderView : NSObject
{
    AVGLImage *_image;
    struct {
        float Position[3];
        float TexCoord[2];
    } _vertexs[4];
    struct CGRect _frame;
    int _glTextureRotateAngle;
    id <AVGLRenderViewProtocol> _delegate;
    double _yRotateAngle;
    double _xRotateAngle;
    float _yRotateMatrix[16];
    float _textureRotateMatrix[4];
    float _textureBoundMatrix[4];
    float _textureScaleMatrix[4];
    unsigned int *_planarTextureHandles;
    unsigned int _rgbTexture;
    unsigned int _outputRgbTexture;
    double _boundWidth;
    _Bool _enableCutting;
    _Bool _hasBlackEdge;
    double _animationCoordDeviation[4];
    double _animationRotateDeviation;
    double _animationAlphaDeviation;
    struct CGRect _destinationFrame;
    int _textueDisplayType;
    _Bool _needDisplayLoading;
    double _textureYUVType;
    _Bool _isDisplayBlocked;
    _Bool _isDisplayStoped;
    _Bool _onlyDisplayBackGround;
    double _currentAnimationStep;
    AVGLNickView *_nickView;
    _Bool _isShowNickName;
    _Bool _isOpenGLDestroyed;
    unsigned int _YTextureTarget;
    unsigned int _UVTextureTarget;
    struct __CVBuffer *_yTexture;
    struct __CVBuffer *_uvTexture;
    struct __CVOpenGLESTextureCache *_videoTextureCache;
    struct __CVBuffer *_piexelBuffer;
    _Bool _isOnDetailView;
    struct CGRect _renderFrame;
    double _preTexCoord30;
    double _preTexCoord31;
    float _currScale;
    float _currWidth;
    float _currHeight;
    float _currOffsetX;
    float _currOffsetY;
    struct CGPoint _currCenter;
    _Bool _isFloat;
    int _nickPosition;
    _Bool _micSpeakState;
    float _distortRange;
    int _distortOri;
    int _distortType;
    int _xo;
    char *_strideBuf;
    int _bufLen;
    float _StridedTexCoord;
    _Bool _isStretchFrame;
    _Bool _isInTroopVideo;
    _Bool _isRoundRectShow;
    _Bool _isLocalLandScape;
    _Bool _isBlurState;
    _Bool _isNeedStrideImageWidthTo8Times;
    int _positionType;
    int _nframeangle;
    int _viewMode;
    UIImageView *_micStateView;
}

+ (void)beginAnimations:(id)arg1 context:(void *)arg2;
+ (_Bool)checkAnimation:(id)arg1 withAnimationType:(int)arg2;
+ (void)commitAnimations;
+ (int)getAnimationStatus;
+ (double)getStepLengthAtIndex:(int)arg1 withAnimationType:(int)arg2;
+ (_Bool)isAnimating;
+ (void)onRenderTimer:(id)arg1;
+ (void)registerAnimation:(id)arg1 withAnimationType:(int)arg2;
+ (void)removeAllAnimation;
+ (void)removeAnimation:(id)arg1 withAnimationType:(int)arg2;
+ (void)resetAnimation;
+ (void)setAnimationBaseView:(id)arg1;
+ (void)setAnimationCurve:(long long)arg1;
+ (void)setAnimationDelegate:(id)arg1;
+ (void)setAnimationDidStopSelector:(SEL)arg1;
+ (void)setAnimationDuration:(double)arg1;
- (void)animationAtStepIndex:(int)arg1 withAnimationType:(int)arg2;
- (void)animationEndWithAnimationType:(int)arg1;
- (void)applyRotationWithDegree:(float)arg1 withAxis:(int)arg2 withType:(int)arg3;
- (void)bindBlurImageTexture;
- (void)checkOutBound;
- (void)cleanTexture;
- (id)convertBitmapRGBA8ToUIImage:(char *)arg1 withWidth:(int)arg2 withHeight:(int)arg3;
- (void)dealloc;
- (void)destroyOpenGL;
- (void)drawBackground;
- (void)drawFrame;
- (void)drawLoading;
- (void)drawTexture;
- (float)getAutoRotateAngle;
- (struct CGRect)getCurrentRenderRect;
- (void)getshareScreenviewRectWithTouchpoint:(struct CGPoint)arg1 imageRect:(struct CGRect)arg2;
- (void)hideNickName;
- (void)initVertex;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isBlurState; // @synthesize isBlurState=_isBlurState;
@property(nonatomic) _Bool isInTroopVideo; // @synthesize isInTroopVideo=_isInTroopVideo;
@property(nonatomic) _Bool isLocalLandScape; // @synthesize isLocalLandScape=_isLocalLandScape;
@property(nonatomic) _Bool isNeedStrideImageWidthTo8Times; // @synthesize isNeedStrideImageWidthTo8Times=_isNeedStrideImageWidthTo8Times;
@property(nonatomic) _Bool isRoundRectShow; // @synthesize isRoundRectShow=_isRoundRectShow;
@property(nonatomic) _Bool isStretchFrame; // @synthesize isStretchFrame=_isStretchFrame;
@property(retain, nonatomic) UIImageView *micStateView; // @synthesize micStateView=_micStateView;
@property(nonatomic) int nframeangle; // @synthesize nframeangle=_nframeangle;
- (void)onDoubleTouch:(struct CGPoint)arg1;
- (void)onMove:(float)arg1 andY:(float)arg2;
- (void)onMoveBegin;
- (void)onMoveEnd;
- (void)onScaleBegin;
- (void)onScaleChange:(struct CGPoint)arg1 withScale:(float)arg2;
- (void)onScaleEnd;
@property(nonatomic) unsigned int outputRgbTexture; // @synthesize outputRgbTexture=_outputRgbTexture;
@property(nonatomic) int positionType; // @synthesize positionType=_positionType;
- (void)renderRGBTextureWithframeBuffer:(unsigned int)arg1;
@property(nonatomic) unsigned int rgbTexture; // @synthesize rgbTexture=_rgbTexture;
- (char *)rgbaData:(id)arg1;
- (void)setAnimationStep:(double)arg1;
- (void)setBoundsWithWidth:(float)arg1;
- (void)setCuttingEnable:(_Bool)arg1;
- (void)setDisplayBlock:(_Bool)arg1;
- (void)setDisplayStop:(_Bool)arg1;
- (void)setDistort:(float)arg1 andOrientation:(int)arg2 andType:(int)arg3;
@property(nonatomic) struct CGRect frame; // @dynamic frame;
- (void)setHasBlackEdge:(_Bool)arg1;
@property(retain, nonatomic) AVGLImage *image; // @dynamic image;
@property(nonatomic) _Bool isFloat; // @dynamic isFloat;
- (void)setMicSeakState:(_Bool)arg1;
- (void)setNeedMirrorReverse:(_Bool)arg1;
- (void)setNickName:(id)arg1;
- (void)setNickNameHidden:(_Bool)arg1;
- (void)setRotate:(int)arg1;
@property(nonatomic) int textueDisplayType; // @synthesize textueDisplayType=_textueDisplayType;
@property(nonatomic) int viewMode; // @synthesize viewMode=_viewMode;
- (void)setupTexture;
- (void)showNikeName;
- (void)strideImage:(char **)arg1 u:(char **)arg2 v:(char **)arg3;
- (void)textureCVImageBuffer:(struct __CVBuffer *)arg1 widthType:(int)arg2 heightType:(int)arg3;
- (void)textureNV12:(char *)arg1 widthType:(int)arg2 heightType:(int)arg3 index:(int)arg4;
- (void)textureRGB:(char *)arg1 widthType:(int)arg2 heightType:(int)arg3 index:(int)arg4;
- (void)textureYUV:(char *)arg1 widthType:(int)arg2 heightType:(int)arg3 index:(int)arg4;
- (void)updateFrame:(struct CGRect)arg1;
- (void)updateLodingVertex;
- (void)updateNickFrame;
- (void)updateNickView;
- (void)updateShowMicShow;
- (void)updateTexCoord;
- (void)updateVBOWithDrawType:(int)arg1;
- (void)updateVertexs;

// Remaining properties
@property(nonatomic) id <AVGLRenderViewProtocol> delegate; // @dynamic delegate;
@property(nonatomic) int nickPosition; // @dynamic nickPosition;
@property(retain, nonatomic) AVGLNickView *nickView; // @dynamic nickView;

@end

