//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface BLYSDKConfig : NSObject
{
    _Bool _debugMode;
    _Bool _defaultVersionFieldUsed;
    _Bool _monitorEnabled;
    _Bool _appTransportSecurityEnable;
    _Bool _symbolicateInProcessEnable;
    _Bool _unexpectedTerminatingDetectionEnable;
    _Bool _viewControllerTrackingEnable;
    _Bool _consolelogEnable;
    _Bool _machExceptionEnable;
    NSString *_channel;
    NSString *_version;
    NSString *_deviceIdentifier;
    double _monitorTimeout;
    id _delegate;
    NSString *_applicationGroupIdentifier;
    NSArray *_excludeModuleFilter;
    CDUnknownFunctionPointerType _logCallback;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool appTransportSecurityEnable; // @synthesize appTransportSecurityEnable=_appTransportSecurityEnable;
@property(copy, nonatomic) NSString *applicationGroupIdentifier; // @synthesize applicationGroupIdentifier=_applicationGroupIdentifier;
@property(copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(nonatomic) _Bool consolelogEnable; // @synthesize consolelogEnable=_consolelogEnable;
@property(nonatomic) _Bool debugMode; // @synthesize debugMode=_debugMode;
@property(nonatomic) _Bool defaultVersionFieldUsed; // @synthesize defaultVersionFieldUsed=_defaultVersionFieldUsed;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *deviceIdentifier; // @synthesize deviceIdentifier=_deviceIdentifier;
@property(copy, nonatomic) NSArray *excludeModuleFilter; // @synthesize excludeModuleFilter=_excludeModuleFilter;
@property(nonatomic) CDUnknownFunctionPointerType logCallback; // @synthesize logCallback=_logCallback;
@property(nonatomic) _Bool machExceptionEnable; // @synthesize machExceptionEnable=_machExceptionEnable;
@property(nonatomic) _Bool monitorEnabled; // @synthesize monitorEnabled=_monitorEnabled;
@property(nonatomic) double monitorTimeout; // @synthesize monitorTimeout=_monitorTimeout;
@property(nonatomic) _Bool symbolicateInProcessEnable; // @synthesize symbolicateInProcessEnable=_symbolicateInProcessEnable;
@property(nonatomic) _Bool unexpectedTerminatingDetectionEnable; // @synthesize unexpectedTerminatingDetectionEnable=_unexpectedTerminatingDetectionEnable;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(nonatomic) _Bool viewControllerTrackingEnable; // @synthesize viewControllerTrackingEnable=_viewControllerTrackingEnable;

@end

