//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GSBaseRequest.h"

#import "GSRequestProtocol.h"

@class NSString;

@interface CampusCircleInfoRequestItem : GSBaseRequest <GSRequestProtocol>
{
    _Bool _reqFlag;
    _Bool _reqSkey;
    _Bool _reqName;
    _Bool _reqSchoolInfo;
    unsigned long long _uin;
}

- (void *)getRequestBodyString;
- (id)parseResponseBodyString:(void *)arg1;
@property(nonatomic) _Bool reqFlag; // @synthesize reqFlag=_reqFlag;
@property(nonatomic) _Bool reqName; // @synthesize reqName=_reqName;
@property(nonatomic) _Bool reqSchoolInfo; // @synthesize reqSchoolInfo=_reqSchoolInfo;
@property(nonatomic) _Bool reqSkey; // @synthesize reqSkey=_reqSkey;
- (unsigned int)serviceNumber;
@property(nonatomic) unsigned long long uin; // @synthesize uin=_uin;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

