//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface ClassificationMenuItem : NSObject
{
    long long _classificationID;
    NSString *_classificationName;
    NSMutableArray *_pendantArray;
}

+ (id)getClassificationMenuItemList:(_Bool)arg1;
- (void).cxx_destruct;
@property(nonatomic) long long classificationID; // @synthesize classificationID=_classificationID;
@property(retain, nonatomic) NSString *classificationName; // @synthesize classificationName=_classificationName;
@property(retain, nonatomic) NSMutableArray *pendantArray; // @synthesize pendantArray=_pendantArray;

@end

