//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CMBaseCommand.h"

@class UIView;

@interface CMViewAddCommand : CMBaseCommand
{
    _Bool _isRemoveCmd;
    UIView *_view;
}

- (void).cxx_destruct;
- (void)addView;
- (id)description;
- (void)executeCmd;
- (id)initWithSuperView:(id)arg1 subView:(id)arg2;
@property(nonatomic) _Bool isRemoveCmd; // @synthesize isRemoveCmd=_isRemoveCmd;
- (void)removeView;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
- (void)undoCmd;

@end

