//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDateFormatter, NSString;

@interface Cookie : NSObject
{
    NSDateFormatter *formatter;
    _Bool _secure;
    _Bool _http;
    double _expiration;
    double _creation;
    NSString *_domain;
    NSString *_name;
    NSString *_path;
    NSString *_value;
}

- (void).cxx_destruct;
@property(nonatomic) double creation; // @synthesize creation=_creation;
@property(retain, nonatomic) NSString *domain; // @synthesize domain=_domain;
@property(nonatomic) double expiration; // @synthesize expiration=_expiration;
@property(nonatomic) _Bool http; // @synthesize http=_http;
- (id)httpCookie;
- (id)init;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
@property(nonatomic) _Bool secure; // @synthesize secure=_secure;
@property(retain, nonatomic) NSString *value; // @synthesize value=_value;
- (id)stringCookie;

@end

