//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CrashReporter : NSObject
{
    _Bool _atsSupportEnable;
}

+ (id)sharedInstance;
- (void)addSessionEvents:(id)arg1;
- (_Bool)checkAndUpload;
- (_Bool)checkCrash;
- (_Bool)checkNSExceptionHandler;
- (_Bool)checkSignalHandler;
- (_Bool)cleanCrashRecord;
- (_Bool)cleanCrashRecords:(id)arg1;
- (id)crashThreadInfo;
- (void)enableLog:(_Bool)arg1;
- (_Bool)enableSignalHandlerCheckable:(_Bool)arg1;
- (id)getCrashLog;
- (id)getCrashStack;
- (id)getCrashStackShortNames;
- (id)getCrashToUpload;
- (id)getCrashType;
- (id)getCurrentException;
- (id)init;
- (_Bool)installWithAppkey:(id)arg1;
@property(nonatomic, getter=isATSSupportEnabled) _Bool atsSupportEnable; // @synthesize atsSupportEnable=_atsSupportEnable;
- (_Bool)isCleanBeforeUpload;
- (_Bool)isEnableSymbolicateInProcess;
- (_Bool)isExpMergeUpload;
- (_Bool)isLastCloseByCrash;
- (void)printCrashStack;
- (id)processName;
- (void)reportError:(id)arg1 message:(id)arg2;
- (void)reportError:(id)arg1 message:(id)arg2 backtrace:(_Bool)arg3;
- (void)reportException:(id)arg1 message:(id)arg2;
- (void)reportException:(id)arg1 message:(id)arg2 backtrace:(_Bool)arg3;
- (void)reportUnityExceptionWithName:(id)arg1 reason:(id)arg2 stack:(id)arg3;
- (_Bool)resetDBPath:(id)arg1;
- (id)sdkVersion;
- (void)setATSSupportEnable:(_Bool)arg1;
- (void)setAttachLog:(id)arg1;
- (void)setAttachmentForStack:(id)arg1;
- (void)setBundleId:(id)arg1;
- (void)setBundleVer:(id)arg1;
- (void)setChannel:(id)arg1;
- (void)setCleanBeforeUpload:(_Bool)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDeviceId:(id)arg1;
- (void)setEnableSymbolicateInProcess:(_Bool)arg1;
- (_Bool)setExcludeShortName:(id)arg1;
- (_Bool)setExcludeShortName:(id)arg1 saveAndUpload:(_Bool)arg2;
- (void)setExpMergeUpload:(_Bool)arg1;
- (void)setGUID:(id)arg1;
- (_Bool)setIncludeShortName:(id)arg1;
- (_Bool)setLastCloseByIncludExclued:(_Bool)arg1;
- (void)setStrInternalBuildNumber:(id)arg1;
- (void)setUserData:(id)arg1 value:(id)arg2;
- (void)setUserId:(id)arg1;
- (void)setUserMachHandler:(_Bool)arg1;
- (void)uninstall;
- (_Bool)uploadCrashes:(id)arg1;

@end

