//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CrashConfigMgr : NSObject
{
    _Bool _KSCrashEnabled;
}

+ (id)crashDcpInfoFilePath;
+ (id)instance;
+ (_Bool)isContainThisDeviceVersion:(id)arg1;
+ (_Bool)isEnableDetectByDisableFlag;
+ (_Bool)isNanoCrashProtectEnable;
+ (id)nanoCrashDisableFlagPath;
+ (id)nanoCrashEanableFlagPath;
+ (void)removeNanoCrashDisableFlagFile;
+ (void)removeNanoCrashEanableFlagFile;
- (void)dealloc;
- (void)getConfigInfo;
- (id)getCrashDcpInfo;
- (id)getDpcInfo:(id)arg1;
- (void)handleCrashDcpInfo;
- (void)handleNanoCrashDisableFlag;
- (void)handleNanoCrashFlag;
- (id)init;
@property(getter=isKSCrashEnabled) _Bool KSCrashEnabled; // @synthesize KSCrashEnabled=_KSCrashEnabled;
- (void)setDefault;
- (void)updateDpcConfig:(id)arg1;

@end

