//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DrawerCellCallBack.h"

@class NSString;

@interface DrawerVideoEntry : NSObject <DrawerCellCallBack>
{
    _Bool _shouldShowEntry;
}

+ (id)GetInstance;
+ (void)registerEntry:(_Bool)arg1;
- (void)checkShouldShowVideoEntry;
- (void)dealloc;
- (id)fillCell:(id)arg1;
- (void)handleSliderOutEvent;
- (id)init;
- (float)key;
- (void)onClick;
- (void)setNeedsRefresh;
@property(nonatomic) _Bool shouldShowEntry; // @synthesize shouldShowEntry=_shouldShowEntry;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

