//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QZBaseAutoPlayImageView.h"

@class NSString, UIActivityIndicatorView;

@interface EmotionImageView : QZBaseAutoPlayImageView
{
    _Bool _dataLoaded;
    _Bool _enableAnimation;
    _Bool _lazyLoad;
    NSString *_url;
    UIActivityIndicatorView *_loadingView;
}

+ (id)loadingQueue;
- (void).cxx_destruct;
- (void)cancelLoadGif;
- (void)clearGIFDecodeTarget;
- (void)clearUrl;
- (void)dealloc;
@property(nonatomic) _Bool enableAnimation; // @synthesize enableAnimation=_enableAnimation;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool lazyLoad; // @synthesize lazyLoad=_lazyLoad;
- (void)loadGifData;
- (void)loadGifDataShowLoading:(_Bool)arg1;
@property(retain, nonatomic) UIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
- (void)play;
- (void)playImage:(id)arg1;
- (void)requestImageShowLoading:(_Bool)arg1;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
- (void)startLoadGif;
- (void)startLoadGifShowLoading:(_Bool)arg1;
- (void)stop;

@end

