//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FaceScoreFloatButtonConfigModel : NSObject
{
    unsigned int _textColor;
    unsigned int _backgroundColor;
    unsigned int _likeCount;
    NSString *_text;
    NSString *_iconUrl;
}

@property(nonatomic) unsigned int backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void)dealloc;
@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(nonatomic) unsigned int likeCount; // @synthesize likeCount=_likeCount;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) unsigned int textColor; // @synthesize textColor=_textColor;

@end

