//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface FAOnlinePreviewConfig : NSObject
{
    NSDictionary *_sourceDictionary;
    NSDictionary *_offlineDict;
    int _pkgVersion;
}

+ (id)GetInstance;
+ (_Bool)canAutoDownOffFile:(id)arg1;
+ (int)getOnlinePreviewSource:(id)arg1;
- (id)TIMDownUrl;
- (id)TIMObjectForKey:(id)arg1;
- (long long)TIMTipCountInAIO;
- (id)TIMTipLinkUrl;
- (_Bool)canLocalPreview:(id)arg1;
- (_Bool)canOnlinePreview:(id)arg1;
- (_Bool)canOnlinePreview:(id)arg1 limitSize:(_Bool)arg2;
- (_Bool)canSupportMyPCRelayChn;
- (_Bool)canSupportWiFiPhotoRelayChn;
- (void)dealloc;
@property(readonly, nonatomic) unsigned long long flowSize;
@property(readonly, nonatomic) unsigned long long flowTime;
@property(readonly, nonatomic) unsigned long long ftnThumbMaxSize;
- (id)getHttpsInterfacePage:(int)arg1;
- (_Bool)getOfflineBoolValue:(id)arg1;
- (id)getPreviewConfigInfo:(id)arg1;
- (id)getPreviewConfigInfo:(id)arg1 size:(double)arg2;
- (id)init;
- (void)loadConfigFromFile;
- (void)loadConfigNotFile;
@property(retain, nonatomic) NSDictionary *sourceDictionary; // @synthesize sourceDictionary=_sourceDictionary;
- (void)updateConfig;

@end

