//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView;

@protocol FavAudioPlayManagerDelegate <NSObject>
- (UIView *)getParentView;
- (void)onDownloadAudioBegin;
- (void)onDownloadAudioEnd:(_Bool)arg1 localid:(unsigned long long)arg2;
- (void)onPlayBegin:(NSString *)arg1;
- (void)onPlayEnd:(NSString *)arg1;
@end

