//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@class BaseInfoModel, NSMutableString, UIWebView;

@interface FavoritesRichText : NSArray
{
    NSMutableString *_html;
    BaseInfoModel *_model;
    int _status;
    id <FavRichTextDelegate> _delegate;
    int _elemCount;
    UIWebView *_webView;
}

+ (id)getBaseUrl;
+ (id)textContentFromHtml:(id)arg1 delimiter:(id)arg2;
- (void)addHtmlEnd;
- (void)addHtmlStart;
- (void)addNumber:(id)arg1;
- (void)addParagraph:(id)arg1;
- (void)addPicture:(id)arg1 imgIndex:(int)arg2 thumbUrl:(id)arg3 defaultPath:(id)arg4 withAnchor:(_Bool)arg5;
- (void)addSysFace:(id)arg1 faceName:(id)arg2;
- (void)addUrl:(id)arg1 text:(id)arg2;
- (void)dealloc;
@property(nonatomic) id <FavRichTextDelegate> delegate; // @synthesize delegate=_delegate;
- (id)editableTemplate;
- (void)endParagraph;
- (struct CGRect)getBoundingRectForImg:(int)arg1 fromImgList:(id)arg2;
- (id)getBriefTextHtml:(id)arg1;
- (id)getCompatibleRichMediaHtml:(id)arg1 forEditor:(_Bool)arg2;
- (id)getHtml;
- (id)getHtmlByParsingText:(id)arg1 ignoreUrls:(_Bool)arg2;
- (id)getHtmlForEditor:(_Bool)arg1;
- (id)getHtmlWithTemplate:(id)arg1 head:(id)arg2 body:(id)arg3;
- (id)getPureTextHtml:(id)arg1;
- (id)getRichmediaHtml:(id)arg1 forEditor:(_Bool)arg2;
- (id)getSysfaceHtml:(id)arg1 startedWithX14:(_Bool)arg2 addQuotes:(_Bool)arg3;
- (id)htmlBySetHtml:(id)arg1 withHeaderHtml:(id)arg2 andFooterHtml:(id)arg3;
- (id)imgIdWithUrl:(id)arg1 andIndex:(int)arg2;
- (int)imgIndexFromImgRequest:(id)arg1;
- (id)imgRequestFromPhotoUrl:(id)arg1 andImgIndex:(int)arg2;
- (id)init;
@property(retain, nonatomic) BaseInfoModel *model; // @synthesize model=_model;
- (unsigned long long)processContentAfterEditing;
- (void)reloadPhoto:(id)arg1 localPath:(id)arg2;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (id)simpleTemplate;
- (id)styles;

@end

