//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSTimer;

@interface FlappyEgg : UIImageView
{
    float _vecX;
    float _vecY;
    float _gravity;
    _Bool _firstJump;
    _Bool _disappear;
    struct CGPoint _jumpEndPosition;
    NSTimer *_timer;
    double _timeDelay;
    CDUnknownBlockType _action;
    CDUnknownBlockType _beforeEggRemoved;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
- (void)animationDidStart:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
@property(copy, nonatomic) CDUnknownBlockType beforeEggRemoved; // @synthesize beforeEggRemoved=_beforeEggRemoved;
- (void)cancel;
- (id)initWithImage:(id)arg1;
- (void)play;
- (_Bool)play0;
- (void)play1;
- (void)play2;
- (float)randomDropDistRatio;
@property(nonatomic) double timeDelay; // @synthesize timeDelay=_timeDelay;

@end

