//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class CALayer, UILabel;

@interface FTSRecommendItemCell : UICollectionViewCell
{
    UILabel *_titleLabel;
    CALayer *_vertalSeparatorLayer;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setData:(id)arg1;
@property(retain, nonatomic) CALayer *vertalSeparatorLayer; // @synthesize vertalSeparatorLayer=_vertalSeparatorLayer;
- (void)setVertcalSeparatorHidden:(_Bool)arg1;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

