//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class QQDynamicTabSearchHotWordModel, UILabel;

@interface FTSSubTabSearchHotWordViewCell : UICollectionViewCell
{
    UILabel *_titleLabel;
    QQDynamicTabSearchHotWordModel *_cellModel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) QQDynamicTabSearchHotWordModel *cellModel; // @synthesize cellModel=_cellModel;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)layoutViews;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

