//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AutoPbModel.h"

@class NSMutableArray;

@interface GetAuthDataRsp : AutoPbModel
{
    unsigned int _auth;
    NSMutableArray *_accuDataArr;
    unsigned long long _timeStamp;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *accuDataArr; // @synthesize accuDataArr=_accuDataArr;
@property(nonatomic) unsigned int auth; // @synthesize auth=_auth;
- (id)getPropertyInfos;
@property(nonatomic) unsigned long long timeStamp; // @synthesize timeStamp=_timeStamp;

@end

