//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IndexSearchResultModel : NSObject
{
    _Bool _isFromNewDB;
    int _matchScore;
    long long _docid;
    NSString *_conversationUin;
    NSString *_uin;
    NSString *_content;
    long long _ftsMsgSearchWayType;
    NSString *_ftsPersonSearchNick;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *conversationUin; // @synthesize conversationUin=_conversationUin;
@property(nonatomic) long long docid; // @synthesize docid=_docid;
@property(nonatomic) long long ftsMsgSearchWayType; // @synthesize ftsMsgSearchWayType=_ftsMsgSearchWayType;
@property(retain, nonatomic) NSString *ftsPersonSearchNick; // @synthesize ftsPersonSearchNick=_ftsPersonSearchNick;
- (unsigned long long)hash;
- (id)init;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic) _Bool isFromNewDB; // @synthesize isFromNewDB=_isFromNewDB;
@property(nonatomic) int matchScore; // @synthesize matchScore=_matchScore;
@property(retain, nonatomic) NSString *uin; // @synthesize uin=_uin;

@end

