//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KeyingBaseParameters.h"

#import "NSCopying.h"

@interface KeyingColorDiffParameters : KeyingBaseParameters <NSCopying>
{
    float _uA;
    float _uD;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
@property(nonatomic) float uA; // @synthesize uA=_uA;
@property(nonatomic) float uD; // @synthesize uD=_uD;

@end

