//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class KSCrashReportStore, NSArray, NSDictionary, NSString;

@interface KSCrash : NSObject
{
    _Bool _printTraceToStdout;
    _Bool _searchThreadNames;
    _Bool _searchQueueNames;
    _Bool _introspectMemory;
    _Bool _catchZombies;
    int _deleteBehaviorAfterSendAll;
    int _handlingCrashTypes;
    int _maxStoredReports;
    id <KSCrashReportFilter> _sink;
    NSDictionary *_userInfo;
    double _deadlockWatchdogInterval;
    CDUnknownFunctionPointerType _onCrash;
    CDUnknownFunctionPointerType _wroteCrashDone;
    CDUnknownFunctionPointerType _crashHappened;
    KSCrashReportStore *_crashReportStore;
    NSString *_bundleName;
    NSString *_logFilePath;
    NSString *_nextCrashID;
    NSArray *_doNotIntrospectClasses;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)load;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (double)activeDurationSinceLastCrash;
- (double)activeDurationSinceLaunch;
- (id)allReports;
- (void)applicationDidBecomeActive;
- (void)applicationDidEnterBackground;
- (void)applicationWillEnterForeground;
- (void)applicationWillResignActive;
- (void)applicationWillTerminate;
- (double)backgroundDurationSinceLastCrash;
- (double)backgroundDurationSinceLaunch;
@property(retain, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
@property(nonatomic) _Bool catchZombies; // @synthesize catchZombies=_catchZombies;
@property(nonatomic) CDUnknownFunctionPointerType crashHappened; // @synthesize crashHappened=_crashHappened;
@property(readonly, retain, nonatomic) NSString *crashReportPath;
@property(retain, nonatomic) KSCrashReportStore *crashReportStore; // @synthesize crashReportStore=_crashReportStore;
- (id)crashReportsPath;
- (_Bool)crashedLastLaunch;
@property(nonatomic) double deadlockWatchdogInterval; // @synthesize deadlockWatchdogInterval=_deadlockWatchdogInterval;
- (void)deleteAllReports;
@property(nonatomic) int deleteBehaviorAfterSendAll; // @synthesize deleteBehaviorAfterSendAll=_deleteBehaviorAfterSendAll;
- (int)demangleLanguages;
@property(retain, nonatomic) NSArray *doNotIntrospectClasses; // @synthesize doNotIntrospectClasses=_doNotIntrospectClasses;
- (_Bool)ensureDirectoryExists:(id)arg1;
- (id)generateLiveReport;
@property(nonatomic) int handlingCrashTypes; // @synthesize handlingCrashTypes=_handlingCrashTypes;
- (id)init;
- (id)initWithReportFilesDirectory:(id)arg1;
- (_Bool)install;
@property(nonatomic) _Bool introspectMemory; // @synthesize introspectMemory=_introspectMemory;
- (int)launchesSinceLastCrash;
- (id)liveReportPath;
@property(retain, nonatomic) NSString *logFilePath; // @synthesize logFilePath=_logFilePath;
@property(nonatomic) int maxStoredReports; // @synthesize maxStoredReports=_maxStoredReports;
@property(retain, nonatomic) NSString *nextCrashID; // @synthesize nextCrashID=_nextCrashID;
- (id)nullTerminated:(id)arg1;
@property(nonatomic) CDUnknownFunctionPointerType onCrash; // @synthesize onCrash=_onCrash;
@property(nonatomic) _Bool printTraceToStdout; // @synthesize printTraceToStdout=_printTraceToStdout;
@property(readonly, retain, nonatomic) NSString *recrashReportPath;
- (_Bool)redirectConsoleLogsToDefaultFile;
- (_Bool)redirectConsoleLogsToFile:(id)arg1 overwrite:(_Bool)arg2;
- (unsigned long long)reportCount;
- (void)reportUserException:(id)arg1 reason:(id)arg2 language:(id)arg3 lineOfCode:(id)arg4 stackTrace:(id)arg5 terminateProgram:(_Bool)arg6;
@property(nonatomic) _Bool searchQueueNames; // @synthesize searchQueueNames=_searchQueueNames;
@property(nonatomic) _Bool searchThreadNames; // @synthesize searchThreadNames=_searchThreadNames;
- (void)sendAllReportsWithCompletion:(CDUnknownBlockType)arg1;
- (void)sendReports:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;
- (int)sessionsSinceLastCrash;
- (int)sessionsSinceLaunch;
- (void)setDemangleLanguages:(int)arg1;
- (void)setLogCallback:(CDUnknownFunctionPointerType)arg1;
@property(retain, nonatomic) id <KSCrashReportFilter> sink; // @synthesize sink=_sink;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) CDUnknownFunctionPointerType wroteCrashDone; // @synthesize wroteCrashDone=_wroteCrashDone;
@property(readonly, retain, nonatomic) NSString *stateFilePath;
- (void)uninstall;

@end

