//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, UIColor;

@interface MarioEmojiInfo : NSObject
{
    _Bool _isGif;
    _Bool _isTextImage;
    _Bool _needTextRect;
    _Bool _isStar;
    NSString *_textImagePath;
    NSString *_pathorurl;
    NSString *_text;
    NSString *_sentiment;
    UIColor *_text_color;
    NSArray *_tokens;
    NSString *_fontname;
    struct CGRect _textRect;
}

- (void)dealloc;
@property(retain, nonatomic) NSString *fontname; // @synthesize fontname=_fontname;
@property _Bool isGif; // @synthesize isGif=_isGif;
@property(nonatomic) _Bool isStar; // @synthesize isStar=_isStar;
@property _Bool isTextImage; // @synthesize isTextImage=_isTextImage;
@property _Bool needTextRect; // @synthesize needTextRect=_needTextRect;
@property(retain, nonatomic) NSString *pathorurl; // @synthesize pathorurl=_pathorurl;
@property(retain, nonatomic) NSString *sentiment; // @synthesize sentiment=_sentiment;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSString *textImagePath; // @synthesize textImagePath=_textImagePath;
@property struct CGRect textRect; // @synthesize textRect=_textRect;
@property(retain, nonatomic) UIColor *text_color; // @synthesize text_color=_text_color;
@property(retain, nonatomic) NSArray *tokens; // @synthesize tokens=_tokens;

@end

