//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QQLockDictionary;

@interface MessageTabTopManager : NSObject
{
    QQLockDictionary *_topMsgTabDict;
}

+ (id)GetInstance;
- (void)appWillEnterForeGround;
- (void)dealloc;
- (id)getDiscussSession;
- (id)getGroupSession;
- (id)getNotGroupOrDiscussSession;
- (int)getTopCount;
- (int)getTopState:(id)arg1;
- (id)init;
- (_Bool)isNeedToSaveLocalTopGroup;
- (_Bool)loadHistroyTopMsgTapFromFilePath;
- (void)printTopSession;
- (void)removeMessageTop:(id)arg1;
- (void)removeMessageTopWithoutAbility:(id)arg1;
- (void)saveCurrentTopMsgTap;
- (void)saveLocalTopGrpSaveTag;
- (void)setMessageTop:(id)arg1;
- (void)setMessageTop:(id)arg1 withTime:(id)arg2;
@property(retain) QQLockDictionary *topMsgTabDict; // @synthesize topMsgTabDict=_topMsgTabDict;
- (void)updateLocalTopGrpToCommonGrp;
- (void)updateModelArrayTopState:(id)arg1;
- (void)updateModelTopState:(id)arg1;

@end

