//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QRCodeScanViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "QBAAlertViewDelegate.h"
#import "QCRecorderDelegate.h"
#import "QQAudioSessionManagerDelegate.h"
#import "QQMultiImagePickerControllerDelegate.h"
#import "QRCodeScanDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSDate, NSString, QQMultiImagePickerController, QRCodeReaderOverlayView, SDScanManager, TwoDimensionBarcodeManager, UIActivityIndicatorView, UIButton, UIImage, UILabel, UIView, UIViewController;

@interface MQQRCodeReaderViewController : QRCodeScanViewController <MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate, QQMultiImagePickerControllerDelegate, QCRecorderDelegate, QQAudioSessionManagerDelegate, QRCodeScanDelegate, UINavigationControllerDelegate, QBAAlertViewDelegate>
{
    UIViewController *_guideViewCtrl;
    id <QRCodeScanDelegate> _webviewPluginDelegate;
    id <QRCodeScanDelegate> _delegateForCaller;
    _Bool _bProcessScanResultByCaller;
    _Bool _isInvokeByJs;
    _Bool _isNeedJSResult;
    QRCodeReaderOverlayView *_overlayView;
    _Bool _isNotFirstFromQRCodeActionItem;
    _Bool _isFromPublicAccountAbility;
    struct CGRect _customScanRect;
    _Bool _ishasResult;
    _Bool _isFromLibrary;
    int _retryCount;
    _Bool _isAppear;
    _Bool _isAppearForLibImage;
    _Bool _isEnterBackGroundStopcapture;
    UIView *_headerBar;
    UILabel *_titleLabel;
    _Bool _lastNavigationBarHiddenState;
    long long _lastStatusBarStyle;
    _Bool _bShowHeaderBar;
    unsigned long long _customUIType;
    id <MQQRCodeReaderDelegate> _bizDelegate;
    UIView *_customContentView;
    int _openQRCodeReaderSrc;
    UILabel *_loadingLabel;
    UIActivityIndicatorView *_activeIndicator;
    NSString *_scanResult;
    TwoDimensionBarcodeManager *_qrcodeMgr;
    SDScanManager *_sdcodeMgr;
    _Bool _torchIsOn;
    _Bool _isOpenByAppHasResult;
    _Bool _isDecodeImageFromOut;
    UIImage *_imageFromLibrary;
    NSString *_scanResultFromLibrary;
    _Bool _bWriteLogScan;
    NSDate *_vcInitTime;
    UIButton *_rightbutton;
    UIButton *_guideBack;
    struct CGRect activeRect;
    int _lastScanMode;
    _Bool _isFromSmartDeviceScanAction;
    _Bool _isNeedShowOly;
    _Bool _isShowOlympicView;
    _Bool _jsGotoShowOlympicView;
    _Bool _isNeedShowOCR;
    _Bool _isShowOCRView;
    _Bool _jsGotoShowOCRView;
    _Bool _hideNavigationBarWhenDisapper;
    _Bool _recordVocalPrint;
    _Bool _isRecordFinished;
    int _customStatusBarStyle;
    QRCodeReaderOverlayView *_arView;
    QRCodeReaderOverlayView *_ocrView;
    QQMultiImagePickerController *_qrcodePhotoPicker;
    NSDate *_enterOlyDate;
}

+ (int)GetImageSeparateCountIfNeed:(id)arg1;
+ (id)GetSeparateImageByIndex:(id)arg1 index:(int)arg2;
+ (id)cutImageWithRect:(id)arg1 cutToFrame:(struct CGRect)arg2;
- (void)AddNavView;
- (void)QQMultiImagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)QQMultiImagePickerControllerDidCancel:(id)arg1;
- (void)addAnalyingView;
- (void)addPreparationUI;
- (void)alertNearFileScanDismatch;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) QRCodeReaderOverlayView *arView; // @synthesize arView=_arView;
@property _Bool bWriteLogScan; // @synthesize bWriteLogScan=_bWriteLogScan;
@property(nonatomic) id <MQQRCodeReaderDelegate> bizDelegate;
- (void)buttonClick:(id)arg1 atIndex:(int)arg2;
- (void)callOnCameraOpen;
- (void)cancel;
- (void)cancelFullScreenLayout;
@property(retain, nonatomic) UIView *customContentView;
@property(nonatomic) int customStatusBarStyle; // @synthesize customStatusBarStyle=_customStatusBarStyle;
- (void)dealWithScanResult:(id)arg1;
- (void)dealloc;
- (void)decodeImageFromLibrary;
- (void)decodeLibImageThread:(id)arg1;
- (void)didBecomeActive;
- (void)didEnterForGround;
@property(retain, nonatomic) NSDate *enterOlyDate; // @synthesize enterOlyDate=_enterOlyDate;
- (void)firstTimeUseVocalAddFriend;
- (id)getMachineType;
- (void)gotoNormalScan;
- (void)gotoOCRScan:(_Bool)arg1;
- (void)gotoQQAR:(_Bool)arg1;
- (void)gotoQRCodeCard;
@property(nonatomic) _Bool hideNavigationBarWhenDisapper; // @synthesize hideNavigationBarWhenDisapper=_hideNavigationBarWhenDisapper;
- (void)hidePreparationUI;
- (id)init;
- (void)initParam;
- (id)initWithDecodeType:(int)arg1 customUIType:(unsigned long long)arg2;
- (id)initWithDecodeType:(int)arg1 customUIType:(unsigned long long)arg2 bizDelegate:(id)arg3;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)isAppear;
@property _Bool isDecodeImageFromOut; // @synthesize isDecodeImageFromOut=_isDecodeImageFromOut;
@property(nonatomic) _Bool isFromSmartDeviceScanAction; // @synthesize isFromSmartDeviceScanAction=_isFromSmartDeviceScanAction;
- (_Bool)isIPhone6or6Plus;
@property(nonatomic) _Bool isNeedShowOCR; // @synthesize isNeedShowOCR=_isNeedShowOCR;
@property(nonatomic) _Bool isNeedShowOly; // @synthesize isNeedShowOly=_isNeedShowOly;
- (_Bool)isNeedShowTip;
@property _Bool isOpenByAppHasResult; // @synthesize isOpenByAppHasResult=_isOpenByAppHasResult;
@property(nonatomic) _Bool isRecordFinished; // @synthesize isRecordFinished=_isRecordFinished;
@property(nonatomic) _Bool isShowOCRView; // @synthesize isShowOCRView=_isShowOCRView;
@property(nonatomic) _Bool isShowOlympicView; // @synthesize isShowOlympicView=_isShowOlympicView;
- (_Bool)isSupportFullScreenLayout;
- (_Bool)isSupportRightDragToGoBack;
- (_Bool)isSupportRightDragToGoBack;
@property(nonatomic) _Bool jsGotoShowOCRView; // @synthesize jsGotoShowOCRView=_jsGotoShowOCRView;
@property(nonatomic) _Bool jsGotoShowOlympicView; // @synthesize jsGotoShowOlympicView=_jsGotoShowOlympicView;
- (void)leftButtonClick:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(long long)arg2;
- (void)modifyNavTitle:(_Bool)arg1;
@property(retain, nonatomic) QRCodeReaderOverlayView *ocrView; // @synthesize ocrView=_ocrView;
- (void)onAudioSessionActive;
- (void)onInit;
- (void)onIntterruptBegin;
- (void)onJsDelegateWillDealloc;
- (void)onLeftButtonClick:(id)arg1;
- (void)onOverlayViewAction:(id)arg1;
@property int openQRCodeReaderSrc;
@property(retain, nonatomic) QRCodeReaderOverlayView *overlayView; // @synthesize overlayView=_overlayView;
- (_Bool)qrcodeDecodeWithUIImage:(id)arg1;
@property(retain, nonatomic) QQMultiImagePickerController *qrcodePhotoPicker; // @synthesize qrcodePhotoPicker=_qrcodePhotoPicker;
@property(nonatomic) _Bool recordVocalPrint; // @synthesize recordVocalPrint=_recordVocalPrint;
- (void)recorderFinish:(id)arg1;
- (void)recorderRecording;
- (void)recorderResult:(id)arg1 type:(long long)arg2;
- (void)releaseArResource;
- (void)removeAnalyingView;
- (void)restartScan;
- (id)scaleToSizeByAspectMax:(id)arg1 TargetSize:(double)arg2;
- (void)scanLibImageFail:(id)arg1;
- (void)scanViewController:(id)arg1 didScanResult:(id)arg2;
- (void)scanViewController:(id)arg1 failWithReason:(id)arg2;
- (void)scanViewControllerDidCancel:(id)arg1;
- (void)selectPhotoFromLibrary;
@property(nonatomic) struct CGRect customScanRect; // @dynamic customScanRect;
- (void)setDecodeImage:(id)arg1;
- (void)setFullScreenLayout;
- (void)setOpenByAppByQRCodeResult:(id)arg1;
- (void)showPreparationUI;
- (float)size_h:(float)arg1;
- (float)size_s:(float)arg1;
- (float)size_s_scanRect:(float)arg1;
- (float)size_w:(float)arg1;
- (void)startRecording;
- (void)stopRecording;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)useIPhone5Res;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willEnterBackGround;
- (void)willEnterForeground;

// Remaining properties
@property(retain, nonatomic) UIActivityIndicatorView *activeIndicator; // @dynamic activeIndicator;
@property(nonatomic) _Bool bProcessScanResultByCaller; // @dynamic bProcessScanResultByCaller;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) id <QRCodeScanDelegate> delegateForCaller; // @dynamic delegateForCaller;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) UIViewController *guideViewCtrl; // @dynamic guideViewCtrl;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UIImage *imageFromLibrary; // @dynamic imageFromLibrary;
@property(nonatomic) _Bool isFromPublicAccountAbility; // @dynamic isFromPublicAccountAbility;
@property(nonatomic) _Bool isInvokeByJs; // @dynamic isInvokeByJs;
@property(nonatomic) _Bool isNeedJSResult; // @dynamic isNeedJSResult;
@property(nonatomic) _Bool isNotFirstFromQRCodeActionItem; // @dynamic isNotFirstFromQRCodeActionItem;
@property(retain, nonatomic) UILabel *loadingLabel; // @dynamic loadingLabel;
@property(retain, nonatomic) TwoDimensionBarcodeManager *qrcodeMgr; // @dynamic qrcodeMgr;
@property(retain, nonatomic) NSString *scanResult; // @dynamic scanResult;
@property(retain, nonatomic) NSString *scanResultFromLibrary; // @dynamic scanResultFromLibrary;
@property(retain, nonatomic) SDScanManager *sdcodeMgr; // @dynamic sdcodeMgr;
@property(readonly) Class superclass;
@property(nonatomic) _Bool torchIsOn; // @dynamic torchIsOn;
@property(retain, nonatomic) NSDate *vcInitTime; // @dynamic vcInitTime;
@property(nonatomic) id <QRCodeScanDelegate> webviewPluginDelegate; // @dynamic webviewPluginDelegate;

@end

