//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVAssetImageGenerator, NSURL, UIColor;

@interface MQZoneVideoRangeSliderView : UIView
{
    UIView *_topView;
    UIView *_leftView;
    UIView *_bottomView;
    UIView *_rightView;
    UIView *_bgView;
    UIView *_centerView;
    UIView *_leftMaskingView;
    UIView *_rightMaskingView;
    NSURL *_videoUrl;
    double _frameWidth;
    double _leftPosition;
    double _rightPosition;
    AVAssetImageGenerator *_imageGenerator;
    double _durationSeconds;
    UIColor *_color;
    id <MQZoneVideoRangeSliderViewDelegate> _delegate;
    double _minTime;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (id)createViewWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak id <MQZoneVideoRangeSliderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)getMovieFrame;
- (void)handleCenterPan:(id)arg1;
- (void)handleLeftPan:(id)arg1;
- (void)handleRightPan:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 videoUrl:(id)arg2 startTime:(double)arg3 stopTime:(double)arg4;
- (void)layoutSubviews;
@property(nonatomic) double minTime; // @synthesize minTime=_minTime;
- (void)videoCliped;
- (void)videoCliping;

@end

