//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

#import "UIGestureRecognizerDelegate.h"

@class CADisplayLink, NSIndexPath, NSString, QZoneViewController, UILongPressGestureRecognizer, UIView;

@interface MQZoneDragCollectionView : UICollectionView <UIGestureRecognizerDelegate>
{
    UILongPressGestureRecognizer *_longPressGesture;
    unsigned long long _scrollDirection;
    NSIndexPath *_originalIndexPath;
    NSIndexPath *_moveIndexPath;
    UIView *_tempMoveCell;
    CADisplayLink *_edgeTimer;
    struct CGPoint _lastPoint;
    _Bool _panGestureInEdit;
    double _angle;
    _Bool _edgeScrollEable;
    _Bool _isLongPress;
    _Bool _isInEditingMode;
    _Bool _noSupportLongPress;
    double _minimumPressDuration;
    QZoneViewController *_containerController;
}

- (void).cxx_destruct;
- (void)addLongPressGesture;
- (void)addPanGesture;
- (void)addTapPressGesture;
- (_Bool)canEditCellAtIndexPath:(id)arg1;
@property(nonatomic) __weak QZoneViewController *containerController; // @synthesize containerController=_containerController;
- (id)dequeueReusableCellWithReuseIdentifier:(id)arg1 forIndexPath:(id)arg2;
- (void)edgeScroll;
@property(nonatomic) _Bool edgeScrollEable; // @synthesize edgeScrollEable=_edgeScrollEable;
- (void)enterEditingMode;
- (void)gestureBegan:(id)arg1;
- (void)gestureCancelledOREnded:(id)arg1;
- (void)gestureChanged:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleGesture:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (void)handleTapGesture:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2;
@property(readonly, nonatomic, getter=isInEditingMode) _Bool isInEditingMode; // @synthesize isInEditingMode=_isInEditingMode;
@property(nonatomic) _Bool isLongPress; // @synthesize isLongPress=_isLongPress;
- (_Bool)isSlideLeftOrRight:(struct CGPoint)arg1;
- (void)longPressedGesture:(id)arg1;
@property(nonatomic) double minimumPressDuration; // @synthesize minimumPressDuration=_minimumPressDuration;
- (void)moveCell;
@property(nonatomic) _Bool noSupportLongPress; // @synthesize noSupportLongPress=_noSupportLongPress;
- (id)rasterizedImageCopyOfCell:(id)arg1;
- (void)setEdgeTimer;
- (void)setScrollDirection;
- (void)stopEdgeTimer;
- (void)stopEditingMode;
- (void)updateDataSource;
- (id)viewForSnapShot:(id)arg1;

// Remaining properties
@property(nonatomic) __weak id <MQZDragCollectionViewDataSource> dataSource; // @dynamic dataSource;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <MQZoneDragCollectionViewDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

