//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSInvocation, NSMutableData, NSString, NSURLConnection, UIActivityIndicatorView, UIImage;

@interface MSFImageView : UIImageView
{
    NSString *_url;
    UIImage *_defaultImage;
    NSMutableData *_recData;
    UIActivityIndicatorView *_act;
    NSInvocation *inv;
    NSURLConnection *cnn;
}

- (void)GetURL;
- (void)addTarget:(id)arg1 selector:(SEL)arg2;
@property(retain, nonatomic) NSURLConnection *cnn; // @synthesize cnn;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) UIImage *defaultImage; // @synthesize defaultImage=_defaultImage;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
- (void)startAnimating;
- (void)stopAnimating;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end

