//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ModGroupSort;

@interface MsgType0x210SubMsgType0x17 : NSObject
{
    unsigned int dwOpType;
    ModGroupSort *stModGroupSort;
}

+ (void)parseMsgType0x210SubMsgType0x17:(struct MsgType0x210SubMsgType0x17 *)arg1;
- (void)dealloc;
@property(nonatomic) unsigned int dwOpType; // @synthesize dwOpType;
@property(retain, nonatomic) ModGroupSort *stModGroupSort; // @synthesize stModGroupSort;

@end

