//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQRichMediaPickerController.h"

#import "NearbyVideoAuthPreviewViewDelegate.h"
#import "QQRichMediaPickerControllerDelegate.h"

@class NSString, NearbyVideoAuthFaceDetectAnalyser, NearbyVideoAuthUploader, QQProgressHUD;

@interface NearbyVideoAuthRecordViewController : QQRichMediaPickerController <QQRichMediaPickerControllerDelegate, NearbyVideoAuthPreviewViewDelegate>
{
    NearbyVideoAuthFaceDetectAnalyser *_detectAnalyser;
    NearbyVideoAuthUploader *_uploader;
    QQProgressHUD *_uploadHUD;
    int _entryType;
    long long _sourceType;
}

+ (void)doPretreatmentIfNecessary:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (Class)RichMediaPickerClass;
- (void)completeResult:(_Bool)arg1 resultType:(long long)arg2 error:(id)arg3;
- (void)dealloc;
- (void)didFaceDetectFeature:(id)arg1 faceRect:(struct CGRect)arg2;
@property int entryType; // @synthesize entryType=_entryType;
- (id)getVideoThumbnail:(id)arg1 atSecond:(double)arg2 withOutputSize:(struct CGSize)arg3;
- (void)handleUploadResult:(_Bool)arg1 resultType:(long long)arg2 error:(id)arg3 coverID:(id)arg4 videoID:(id)arg5 localImagePath:(id)arg6 localVideoPath:(id)arg7;
- (id)imageTmpPath;
- (id)init;
- (void)initMediaPickerProperties;
- (id)initWithEntryType:(int)arg1;
- (id)initWithEntryType:(int)arg1 sourceType:(long long)arg2;
- (_Bool)isNetworkConnected;
- (void)prepareForUpload;
- (void)registerNotification;
- (void)richMediaPickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)richMediaPickerControllerDidCancel:(id)arg1;
@property long long sourceType; // @synthesize sourceType=_sourceType;
- (void)setupMediaPicker;
- (void)showVideoPreviewView;
- (void)startRecord;
- (void)startUploadProcess:(id)arg1;
- (void)stopRecord;
- (void)videoAuthPreviewViewDidClickRemarkButton:(id)arg1;
- (void)videoAuthPreviewViewDidClickUploadButton:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

