//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class FlowerCountButton, NSArray, NSDictionary, NSString, QQVisualEffectView, UIButton, UICollectionView, UILabel;

@interface NearbyGiftSelectionView : UIView <UICollectionViewDataSource, UICollectionViewDelegate>
{
    QQVisualEffectView *_visualView;
    FlowerCountButton *_flowerCountButton;
    UILabel *_titelLabel;
    UIButton *_actionButton;
    UICollectionView *_giftGridView;
    UIView *_loadingView;
    NSDictionary *_coinInfo;
    long long _flowerCount;
    long long _heartCount;
    UILabel *_limitLabel;
    _Bool _isFreeGiftFinished;
    int _giftType;
    id <NearbyGiftSelectionViewDelegate> _delegate;
    NSArray *_nearbyGifts;
}

- (void).cxx_destruct;
- (id)addGiftCollectionViewWithOffsetX:(double)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(nonatomic) __weak id <NearbyGiftSelectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dismissGiftSelectionView;
@property(nonatomic) int giftType; // @synthesize giftType=_giftType;
- (void)gotoPayAction;
- (void)gotoPayActionWithSource:(id)arg1;
- (void)hiddenGiftView:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isFreeGiftFinished; // @synthesize isFreeGiftFinished=_isFreeGiftFinished;
- (void)layoutSubviews;
- (void)loadGiftConfigData;
@property(retain, nonatomic) NSArray *nearbyGifts; // @synthesize nearbyGifts=_nearbyGifts;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)refreshFooterStatus;
- (void)reloadStock;
- (void)selectDefaultGift;
@property(readonly, nonatomic) NSDictionary *selectedGiftInfo;
- (void)sendGiftAction;
- (void)showGiftView:(_Bool)arg1;
- (void)showLoaidngView;
- (void)showRetryView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

