//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@protocol NearbyGiftSelectionViewDelegate <NSObject>

@optional
- (void)giftViewDidHidden;
- (void)nearbyVideoGiftReportWithOpName:(NSString *)arg1 withSource:(NSString *)arg2;
- (void)sendGiftWithParams:(NSDictionary *)arg1;
@end

