//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Search)
- (_Bool)fullPinyinMatchKeyword:(id)arg1 pinyinLocation:(id)arg2 resultRange:(struct _NSRange *)arg3;
- (_Bool)matchKeyword:(id)arg1 resultRange:(struct _NSRange *)arg2;
- (id)mutRangeOfString:(id)arg1;
- (id)stringByRemoveStrOfRange:(struct _NSRange)arg1;
- (id)stringbyRemoveFrom:(id)arg1 To:(id)arg2;
@end

