//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface OBJForStoker : NSObject
{
    _Bool _allEn;
    long long _loc;
    long long _len;
    NSString *_str;
}

+ (id)codeTokenizer:(id)arg1 len:(int)arg2;
- (void).cxx_destruct;
@property _Bool allEn; // @synthesize allEn=_allEn;
- (_Bool)checkLastCharEn:(id)arg1;
- (id)copy;
- (id)description;
- (id)init;
@property long long len; // @synthesize len=_len;
@property long long loc; // @synthesize loc=_loc;
- (id)newObject;
@property(retain, nonatomic) NSString *str; // @synthesize str=_str;

@end

