//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OfflineResReqContent : NSObject
{
    id obj;
    SEL selecter;
}

- (void)dealloc;
@property(retain, nonatomic) id obj; // @synthesize obj;
@property(nonatomic) SEL selecter; // @synthesize selecter;

@end

