//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSEngineBase.h"

#import "IEngineDispatchDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface OneWayFriendsEngine : QSEngineBase <IEngineDispatchDelegate>
{
    NSMutableArray *_requestQueue;
    long long _seqId;
    NSMutableDictionary *_info;
    NSMutableArray *_OWFriendlist;
}

+ (id)getInstance;
- (void)didRecievedMsg:(CDStruct_7895f40e)arg1;
- (void)didparseGetInfoList:(const struct RspGetInfo *)arg1;
- (void)didparseGetUinList:(const struct RspGetList *)arg1;
- (id)getLocalOneWayFriendsList;
- (id)getQueueRequestWithSSOSeq:(int)arg1;
- (id)getQueueRequestWithType:(int)arg1;
- (id)getRequestStrType:(int)arg1;
- (int)getSeqId;
- (id)init;
- (void)initData;
- (_Bool)isOneWayFriendWithUin:(long long)arg1;
- (id)loadConfigInfo;
- (id)loadFriendsList;
- (void)notifyError:(id)arg1;
- (void)onAccountLogin:(id)arg1;
- (void)onAccountLogout:(id)arg1;
- (void)owfHandleGetListRespBody:(const char *)arg1 len:(int)arg2 seq:(int)arg3;
- (void)parseDeleteList:(basic_string_075b6133 *)arg1;
- (void)parseGetList:(basic_string_075b6133 *)arg1;
- (int)removeQueueRequest:(int)arg1;
- (_Bool)requestDeleteOneWayFriends:(id)arg1;
- (_Bool)requestGetOneWayFriendList:(_Bool)arg1;
- (void)reset;
- (void)saveConfigInfo:(id)arg1;
- (void)saveFriendsList:(id)arg1;
- (_Bool)updateReq:(unsigned int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

