//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSMutableSet, NSString, QRBookInfo;

@interface OnlineTag : NSObject <NSCopying>
{
    QRBookInfo *_onlineBookInfo;
    QRBookInfo *_bookshelfBookinfo;
    int _toReadingCharpterId;
    NSString *_toReadingCharpterTitle;
    int _toReadingType;
    int _rightParameter;
    NSString *_chapterFileUrl;
    NSMutableSet *_gettingTagsSet;
    _Bool _cancelled;
    _Bool _isCloudProgressSync;
    _Bool _isBuy;
    long long _direction;
}

- (void)addCharpterRequestId:(id)arg1;
@property(retain, nonatomic) QRBookInfo *bookshelfBookinfo; // @synthesize bookshelfBookinfo=_bookshelfBookinfo;
@property(retain, nonatomic) NSString *chapterFileUrl; // @synthesize chapterFileUrl=_chapterFileUrl;
- (_Bool)containCharpterRequestId:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
@property(nonatomic) long long direction; // @synthesize direction=_direction;
- (id)getBookInfoForDownload;
- (id)getBookInfoFromTag;
- (id)getCurrentChapterFilePath;
- (int)getTheChapterIdToReading:(int)arg1;
@property(retain, nonatomic) NSMutableSet *gettingTagsSet; // @synthesize gettingTagsSet=_gettingTagsSet;
- (id)initWithBookInfo:(id)arg1;
- (id)initWithOnlineTag:(id)arg1;
@property(nonatomic) _Bool isBuy; // @synthesize isBuy=_isBuy;
@property(nonatomic) _Bool isCloudProgressSync; // @synthesize isCloudProgressSync=_isCloudProgressSync;
- (_Bool)isFininshed;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) QRBookInfo *onlineBookInfo; // @synthesize onlineBookInfo=_onlineBookInfo;
- (void)refreshDate;
- (_Bool)removeCharpterRequestId:(id)arg1;
- (void)resetProgress;
@property(nonatomic) int rightParameter; // @synthesize rightParameter=_rightParameter;
- (_Bool)saveProgressToOnlineDB:(id)arg1;
- (void)setReadTime;
@property(nonatomic) int toReadingCharpterId; // @synthesize toReadingCharpterId=_toReadingCharpterId;
@property(retain, nonatomic) NSString *toReadingCharpterTitle; // @synthesize toReadingCharpterTitle=_toReadingCharpterTitle;
@property(nonatomic) int toReadingType; // @synthesize toReadingType=_toReadingType;

@end

