//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class PAAdMsgVideoBannerModel, QQAsynUrlImageView, UIImageView, UILabel;

@interface PAAdMsgBannerButton : UIButton
{
    PAAdMsgVideoBannerModel *_bannerModel;
    UILabel *_textLabel;
    QQAsynUrlImageView *_iconImageView;
    UIImageView *_arrowImageView;
    UILabel *_abstractLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *abstractLabel; // @synthesize abstractLabel=_abstractLabel;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) PAAdMsgVideoBannerModel *bannerModel; // @synthesize bannerModel=_bannerModel;
@property(retain, nonatomic) QQAsynUrlImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (id)initWithBannerModel:(id)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void)updateIconImageView;
- (void)updateTextLabel;

@end

