//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PluginObject.h"

@interface PCCConfigManager : PluginObject
{
}

+ (id)GetInstance;
- (void)addConfigsToDB:(id)arg1;
- (void)addResourcesToDB:(id)arg1;
- (void)createTableIfNeeded;
- (void)deleteConfigsFromDB:(id)arg1;
- (void)deleteResourcesFromDB:(id)arg1;
- (id)loadConfigItems;
- (id)loadResourceItem:(id)arg1 rid:(id)arg2;
- (id)loadResourceItems;
- (void)loadResourceItemsForConfigs:(id)arg1;
- (void)loginSuccess;
- (void)reportConfigCoverRate;
- (double)reqDate;
- (long long)reqTimes;
- (void)setReqDate:(double)arg1;
- (void)setReqTimes:(long long)arg1;
- (void)setVersion:(long long)arg1;
- (void)updateConfigs:(id)arg1;
- (void)updateConfigsToDB:(id)arg1;
- (void)updateResourcesFromUpdatedConfigs:(id)arg1 bids:(id)arg2;
- (void)updateResourcesToDB:(id)arg1;
- (long long)version;

@end

