//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "QQAvatarPendantPresentDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSString, PECropRectView, QQAvatarPendantPresenter, UIImage, UIImageView, UIScrollView;

@interface PECropView : UIView <UIScrollViewDelegate, UIGestureRecognizerDelegate, QQAvatarPendantPresentDelegate>
{
    UIImage *_image;
    UIImage *_croppedImage;
    _Bool _isShowAvatarPendant;
    _Bool _isCropAIOBackgroud;
    unsigned long long _cropType;
    double _aspectRatio;
    struct CGRect _cropRect;
    int _xo;
    UIScrollView *_scrollView;
    UIView *_zoomingView;
    UIImageView *_imageView;
    PECropRectView *_cropRectView;
    UIView *_topOverlayView;
    UIView *_leftOverlayView;
    UIView *_rightOverlayView;
    UIView *_bottomOverlayView;
    struct CGRect _insetRect;
    struct CGRect _editingRect;
    long long _interfaceOrientation;
    QQAvatarPendantPresenter *_avatarPendantPresenter;
    _Bool _isCropUserSummaryCover;
    _Bool _resizing;
}

- (void)addAvatarPendantView;
- (void)addCircleMask;
@property(nonatomic) double aspectRatio; // @dynamic aspectRatio;
- (void)automaticZoomIfEdgeTouched:(struct CGRect)arg1;
- (int)avatarPendantFileSize;
- (struct CGRect)cappedCropRectInImageRectWithCropRectView:(id)arg1;
@property(nonatomic) struct CGRect cropRect; // @dynamic cropRect;
- (void)cropRectViewDidBeginEditing:(id)arg1;
- (void)cropRectViewDidEndEditing:(id)arg1;
- (void)cropRectViewEditingChanged:(id)arg1;
@property(readonly, nonatomic) UIImage *croppedImage; // @dynamic croppedImage;
- (void)dealloc;
- (struct CGRect)frameForAvatarPendant;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (struct CGRect)getCropRect;
- (void)handleRotation:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isCropUserSummaryCover; // @synthesize isCropUserSummaryCover=_isCropUserSummaryCover;
@property(nonatomic, getter=isResizing) _Bool resizing; // @synthesize resizing=_resizing;
- (void)layoutCropRectViewWithCropRect:(struct CGRect)arg1;
- (void)layoutOverlayViewsWithCropRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)resetLayout;
- (id)rotatedImageWithImage:(id)arg1 transform:(struct CGAffineTransform)arg2;
- (void)scrollViewDidZoom:(id)arg1;
- (void)setAspectRatioWithoutAnimate:(double)arg1;
@property(retain, nonatomic) UIImage *image; // @dynamic image;
@property(nonatomic) _Bool isShowAvatarPendant; // @dynamic isShowAvatarPendant;
- (void)setupImageView;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)zoomToCropRect:(struct CGRect)arg1 animated:(_Bool)arg2;

// Remaining properties
@property(nonatomic) unsigned long long cropType; // @dynamic cropType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isCropAIOBackgroud; // @dynamic isCropAIOBackgroud;
@property(readonly) Class superclass;

@end

