//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISCBusinessCallback.h"
#import "ISCListenerCallback.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, PersonalRedBagConfigInfo;

@interface PersonalRedBagResMgr : NSObject <ISCBusinessCallback, ISCListenerCallback>
{
    NSMutableArray *_downloadingIds;
    _Bool hasPreload;
    NSObject<OS_dispatch_queue> *redbagQueue;
    NSMutableDictionary *_templateDic;
    PersonalRedBagConfigInfo *_configInfo;
    NSString *_specialChars;
}

+ (id)getInstance;
- (void).cxx_destruct;
- (void)cacheConfigInfo:(id)arg1;
- (void)cacheSpecialChars:(id)arg1;
- (void)cacheTemplate:(id)arg1;
- (_Bool)canUpdate:(unsigned long long)arg1 scid:(id)arg2 from:(id)arg3;
@property(retain, nonatomic) PersonalRedBagConfigInfo *configInfo; // @synthesize configInfo=_configInfo;
- (_Bool)deleteFiles:(unsigned long long)arg1 scid:(id)arg2;
- (void)doInit;
- (void)downloadConfigJson;
- (void)downloadFontFile;
- (void)downloadRedbagResource:(int)arg1 from:(id)arg2;
- (void)downloadSpecailChar;
- (_Bool)getItem:(unsigned long long)arg1 scid:(id)arg2 info:(id)arg3;
- (id)getOldSpecialCharImgPath:(long long)arg1;
- (id)getRedbagResourceConfigPath:(int)arg1;
- (id)getRedbagResourcePath:(int)arg1;
- (id)getRedbagResourcePathByType:(long long)arg1;
- (id)getRedbagRootPath;
- (id)getSpecialCharImgPath:(long long)arg1;
- (id)getTemplateById:(id)arg1;
- (id)getTemplateFromOldJson;
- (id)init;
- (void)initTempLateInfo;
- (void)initTemplateDic;
- (_Bool)isFileExists:(unsigned long long)arg1 scid:(id)arg2;
- (void)loadInfoFromConfigJson;
- (void)loadSpecialCharJson;
- (id)loadTemplateFromJson:(int)arg1;
- (void)onCompleted:(unsigned long long)arg1 scid:(id)arg2 cfgScid:(id)arg3 from:(id)arg4 result:(int)arg5 httpcode:(int)arg6;
- (void)onLoginAction;
- (void)onProgress:(unsigned long long)arg1 scid:(id)arg2 cfgScid:(id)arg3 progressCur:(unsigned long long)arg4 progressMax:(unsigned long long)arg5;
- (void)onRedbagDownloaded:(int)arg1;
- (void)onSpecialCharDownloaded;
- (int)parseRedbagId:(id)arg1;
- (void)preload:(_Bool)arg1;
@property(retain, nonatomic) NSString *specialChars; // @synthesize specialChars=_specialChars;
@property(retain, nonatomic) NSMutableDictionary *templateDic; // @synthesize templateDic=_templateDic;
- (void)syncTemplateDicToLocal;
- (void)unZipAioAnimFiles:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

