//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IAccountService.h"
#import "WloginCallbackProtocol_v2.h"

@class NSLock, NSMutableArray, NSString;

@interface QAccountService : NSObject <IAccountService, WloginCallbackProtocol_v2>
{
    int _loginState;
    NSString *_loginAccount;
    NSString *_activeUinOrAccountStr;
    NSString *_loginAccountEx;
    NSMutableArray *_sigItems;
    NSMutableArray *_pskeyDomainList;
    NSMutableArray *_pt4tokenDomainList;
    int _regLoginType;
    NSLock *myLock;
}

+ (id)getInstance;
- (void)SmsCodeSuccessBySmsVerifyLogin_V2:(id)arg1 tag:(long long)arg2;
- (void)SmsVerifyLoginFailed_v2:(id)arg1 andRst:(int)arg2 withErrInfo:(id)arg3 tag:(long long)arg4;
@property(retain, nonatomic) NSString *activeUinOrAccountStr; // @synthesize activeUinOrAccountStr=_activeUinOrAccountStr;
- (_Bool)addDomainListToWT:(id)arg1;
- (_Bool)addPt4tokenDomainListToWT:(id)arg1;
- (void)autoRefreshSigs;
- (void)dealloc;
- (void)deleteUserAccount:(id)arg1;
- (id)findMemSigInArray:(id)arg1 sigName:(id)arg2;
- (int)getAccountType:(id)arg1;
- (id)getActiveUinOrAccount;
- (id)getLoginAccount;
- (id)getLoginAccountEx;
- (id)getLoginNickname;
- (id)getLoginNicknameForQzone;
- (id)getMemSig_A2:(id)arg1;
- (id)getMemSig_D2:(id)arg1;
- (id)getMemSig_D2Key:(id)arg1;
- (int)getMemSig_D2KeyInt:(id)arg1;
- (long long)getOnlineStatus;
- (id)getPublicAccountInfo:(unsigned long long)arg1;
- (id)getSigByBit:(unsigned int)arg1;
- (id)getSigByBit:(unsigned int)arg1 ofAccount:(id)arg2;
- (id)getSigByBit:(unsigned int)arg1 otherAppId:(unsigned int)arg2;
- (id)getSigItem:(long long)arg1;
- (id)getSigKeyByBit:(unsigned int)arg1;
- (id)getSigKeyByBit:(unsigned int)arg1 ofAccount:(id)arg2;
- (id)getSigKeyByBit:(unsigned int)arg1 otherAppId:(unsigned int)arg2;
- (id)getSigKey_ST_Appid:(unsigned int)arg1;
- (id)getSig_A2;
- (id)getSig_A2HexStr;
- (id)getSig_D2;
- (id)getSig_D2Key;
- (int)getSig_D2KeyInt;
- (id)getSig_DA2;
- (id)getSig_PSKEY:(id)arg1;
- (id)getSig_PSKEYStr:(id)arg1;
- (id)getSig_PT4_TOKEN:(id)arg1;
- (id)getSig_PT4_TOKENStr:(id)arg1;
- (id)getSig_SIDStr;
- (id)getSig_SKEY;
- (id)getSig_SKEYStr;
- (id)getSig_ST_Appid:(unsigned int)arg1;
- (id)getSig_SUPERKEY;
- (id)getSig_SUPERKEYStr;
- (int)getSig_SuperToken:(id)arg1;
- (long long)getUin;
- (id)getUinStr;
- (id)getWloginSdk;
- (id)hexStringOfData:(id)arg1;
- (id)init;
- (void)inputPassword_v2:(id)arg1 andAccount:(id)arg2;
- (void)inputPassword_v2:(id)arg1 andAccount:(id)arg2 tag:(long long)arg3;
- (void)inputSmsCodeBySmsVerifyLogin_V2:(id)arg1 andMsgCnt:(unsigned short)arg2 andTimeout:(unsigned short)arg3 andMsg:(id)arg4 tag:(long long)arg5;
- (void)inputSmsCodeErrorBySmsVerifyLogin_V2:(id)arg1 andErrInfo:(id)arg2 tag:(long long)arg3;
- (void)inputSmsCodeError_v2:(id)arg1 andErrInfo:(id)arg2 tag:(long long)arg3;
- (void)inputSmsCode_v2:(id)arg1 andMbPhoneInfo:(id)arg2 tag:(long long)arg3;
- (_Bool)isExistPasswordSig:(id)arg1;
- (_Bool)isLocalSigValid:(id)arg1 sigType:(unsigned int)arg2;
- (_Bool)isNeedLoginWithPwd:(id)arg1;
- (_Bool)isSigsReady;
- (long long)loadUpdateA2Time:(id)arg1;
- (long long)loadUpdatePSKeyTime:(id)arg1 domain:(id)arg2;
- (long long)loadUpdatePt4tokenTime:(id)arg1 domain:(id)arg2;
- (long long)loadUpdateSKeyTime:(id)arg1;
@property(retain, nonatomic) NSString *loginAccount; // @synthesize loginAccount=_loginAccount;
@property(retain, nonatomic) NSString *loginAccountEx; // @synthesize loginAccountEx=_loginAccountEx;
- (int)loginEx:(id)arg1 andPwd:(id)arg2 tag:(long long *)arg3;
- (int)loginEx:(id)arg1 tag:(long long *)arg2;
- (void)loginFailed_v2:(id)arg1 andRst:(int)arg2 withErrInfo:(id)arg3;
- (void)loginFailed_v2:(id)arg1 andRst:(int)arg2 withErrInfo:(id)arg3 tag:(long long)arg4;
- (void)loginFailed_v2InMainThread:(id)arg1 andRst:(int)arg2 withErrInfo:(id)arg3 tag:(long long)arg4;
- (void)loginSuccessHandle:(int)arg1 tag:(long long)arg2;
- (void)loginSuccessSig_v2:(id)arg1 andSig:(id)arg2 andBaseInfo:(id)arg3;
- (void)loginSuccessSig_v2:(id)arg1 andSig:(id)arg2 andBaseInfo:(id)arg3 tag:(long long)arg4;
- (int)loginWithAccount:(id)arg1;
- (int)loginWithAccount:(id)arg1 andPwd:(id)arg2;
- (int)loginWithAccount:(id)arg1 andUin:(id)arg2;
- (int)loginWithAccountOnReg:(id)arg1 andPwd:(id)arg2;
- (int)loginWithMSFHistorySigs:(id)arg1 andA2:(id)arg2 andD2:(id)arg3 andD2key:(id)arg4;
- (int)loginWithOnlySigCheck:(id)arg1;
- (void)logoutUserAccount;
- (id)makeSmsLoginPhone:(id)arg1 andCountry:(id)arg2;
@property(retain, nonatomic) NSLock *myLock; // @synthesize myLock;
- (void)pushToRefreshSkey;
- (void)quickLoginEnd_v2:(id)arg1 andUrl:(id)arg2 tag:(long long)arg3;
- (void)quickLoginFailed_v2:(id)arg1 andRst:(int)arg2 withErrInfo:(id)arg3 tag:(long long)arg4;
- (void)recordSigItem:(long long)arg1 isLogin:(_Bool)arg2 sigBit:(unsigned int)arg3 thirdPartyAppid:(unsigned int)arg4 reqDomains:(id)arg5;
- (void)recordSigItem:(long long)arg1 isLogin:(_Bool)arg2 sigBit:(unsigned int)arg3 thirdPartyAppid:(unsigned int)arg4 reqDomains:(id)arg5 pt4tokenDomains:(id)arg6;
- (void)recordSigItemOfEx:(long long)arg1 isLogin:(_Bool)arg2 sigBit:(unsigned int)arg3 thirdPartyAppid:(unsigned int)arg4 reqDomains:(id)arg5 pt4tokenDomains:(id)arg6;
- (void)recordSigItemOnReg:(long long)arg1 isLogin:(_Bool)arg2 sigBit:(unsigned int)arg3 thirdPartyAppid:(unsigned int)arg4 reqDomains:(id)arg5 pt4tokenDomains:(id)arg6;
@property(nonatomic) int regLoginType; // @synthesize regLoginType=_regLoginType;
- (void)removeSigItem:(long long)arg1;
- (int)requestSigByBit:(unsigned int)arg1;
- (int)requestSigByBit:(unsigned int)arg1 otherAppId:(unsigned int)arg2;
- (int)requestSig_DA2;
- (int)requestSig_OPENKEY:(unsigned int)arg1;
- (int)requestSig_PSKEY:(_Bool)arg1 SKey:(_Bool)arg2 pt4Token:(_Bool)arg3 withDomain:(id)arg4;
- (int)requestSig_SKEY;
- (int)requestSig_STWEB;
- (int)requestSig_ST_Appid:(unsigned int)arg1;
- (void)saveAllUpdatePSKeyTimeOnSigOk:(id)arg1 domain:(id)arg2;
- (void)saveAllUpdatePt4tokenTimeOnSigOk:(id)arg1 domain:(id)arg2;
- (void)saveUpdateA2Time:(id)arg1;
- (void)saveUpdatePSKeyTime:(id)arg1 domain:(id)arg2;
- (void)saveUpdatePt4tokenTime:(id)arg1 domain:(id)arg2;
- (void)saveUpdateSKeyTime:(id)arg1;
- (void)showPicture_v2:(id)arg1 andPicData:(id)arg2;
- (void)showPicture_v2:(id)arg1 andPicData:(id)arg2 andWording:(id)arg3;
- (void)showPicture_v2:(id)arg1 andPicData:(id)arg2 andWording:(id)arg3 tag:(long long)arg4;
- (void)showWebVerify:(id)arg1 andUrl:(id)arg2 tag:(long long)arg3;
- (int)smsLoginWithPhone:(id)arg1 andCountry:(id)arg2;
- (int)smsLoginWithPhoneAfterReg:(id)arg1 andCountry:(id)arg2 isSimplePass:(_Bool)arg3;
- (int)smsLoginWithPhoneEx:(id)arg1 andCountry:(id)arg2 tag:(long long *)arg3;
- (int)smsLoginWithPhoneOnReg:(id)arg1 andCountry:(id)arg2;
- (void)updateDomainList:(id)arg1;
- (void)updatePt4TokenDomainList:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

