//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface QBWebViewAnalyticsInfo : NSObject
{
    _Bool _isSucceed;
    NSString *_eventName;
    NSDictionary *_params;
    long long _elapse;
    long long _size;
}

- (void).cxx_destruct;
@property long long elapse; // @synthesize elapse=_elapse;
@property(retain) NSString *eventName; // @synthesize eventName=_eventName;
@property _Bool isSucceed; // @synthesize isSucceed=_isSucceed;
@property(retain) NSDictionary *params; // @synthesize params=_params;
@property long long size; // @synthesize size=_size;

@end

