//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IAccountMsgModel.h"
#import "NSCoding.h"

@class NSData, NSString;

@interface QLoginAccountUnreadInfo : NSObject <NSCoding, IAccountMsgModel>
{
    int _msgFlag;
    int _msgNum;
    int _lastMsgTime;
    NSString *_nick;
    long long _uin;
    NSData *_A2;
    NSData *_lastReadedCookie;
    NSData *_currentMsgCookie;
}

@property(retain, nonatomic) NSData *A2; // @synthesize A2=_A2;
@property(retain, nonatomic) NSData *currentMsgCookie; // @synthesize currentMsgCookie=_currentMsgCookie;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)duplicate;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) int lastMsgTime; // @synthesize lastMsgTime=_lastMsgTime;
@property(retain, nonatomic) NSData *lastReadedCookie; // @synthesize lastReadedCookie=_lastReadedCookie;
@property(nonatomic) int msgFlag; // @synthesize msgFlag=_msgFlag;
@property(nonatomic) int msgNum; // @synthesize msgNum=_msgNum;
@property(retain, nonatomic) NSString *nick; // @synthesize nick=_nick;
@property(nonatomic) long long uin; // @synthesize uin=_uin;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

