//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQViewController.h"

#import "QQTextFieldDelegate.h"

@class NSArray, NSMutableDictionary, NSString, QQActivateFriendsIconLayout, QQTextField, UILabel, UIView;

@interface QQActivateFriendsSendMessage : QQViewController <QQTextFieldDelegate>
{
    UIView *_transparentBar;
    UILabel *_label;
    QQTextField *_textField;
    NSArray *_friendModels;
    UIView *_friendsContentView;
    NSMutableDictionary *_friendIconViews;
    QQActivateFriendsIconLayout *_friendIconLayout;
}

- (void).cxx_destruct;
- (_Bool)QQGrowingTextView:(id)arg1 exceedMaxLength:(long long)arg2;
- (void)cancelSendMessage;
@property(retain, nonatomic) QQActivateFriendsIconLayout *friendIconLayout; // @synthesize friendIconLayout=_friendIconLayout;
- (void)growingTextViewDidChange:(id)arg1;
- (void)growingTextViewDidSendEmptyContent:(id)arg1;
- (id)initWithFriends:(id)arg1;
- (void)layoutFriends;
- (void)loadFriendsContentView;
- (void)loadView;
- (void)loadWithFriends;
- (long long)maxInputLenghtInQQGrowingTextView:(id)arg1;
- (void)resetFriendContentView;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) NSMutableDictionary *friendIconViews; // @dynamic friendIconViews;
@property(retain, nonatomic) NSArray *friendModels; // @dynamic friendModels;
@property(retain, nonatomic) UIView *friendsContentView; // @dynamic friendsContentView;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UILabel *label; // @dynamic label;
@property(readonly) Class superclass;
@property(retain, nonatomic) QQTextField *textField; // @dynamic textField;
@property(retain, nonatomic) UIView *transparentBar; // @dynamic transparentBar;

@end

