//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQModel.h"

#import "NSCopying.h"

@class NSData, NSString;

@interface QQAccountsModel : QQModel <NSCopying>
{
    NSString *_uin;
    NSString *_nick;
    NSString *_loginAccount;
    NSString *_icon;
    int _pwd;
    NSString *_sig;
    int _sex;
    int _birs;
    int _country;
    int _prov;
    int _city;
    int _profileSex;
    double loginTime;
    double getMsgTime;
    _Bool login;
    long long onlineStatus;
    _Bool _bSavePwd;
    _Bool _bAutoLogin;
    _Bool _bRecvGroupMsg;
    int head;
    _Bool _bKeepPcOnline;
    _Bool _bKeepBackGroundOnLine;
    NSData *_cookie;
    NSData *_syncCookie;
    _Bool _hasUsedDataLine;
    NSString *_sCountry;
    NSString *_sProvince;
    NSString *_sCity;
    _Bool _shownViewOnlineFriendTips;
    _Bool _isVip;
    _Bool _isSuperVip;
    NSString *_chatAvatarID;
    unsigned int _themeId;
    NSString *_themeVersion;
    _Bool _bThemeAuth;
    _Bool _bUseTabSound;
    int _level;
    int _lastUpdateLevelTime;
    int _isShowXMan;
    int _loginDay;
    int _phoneQQXManDay;
    int _lastUpdateQQXManTime;
    _Bool _bXManIconClick;
    _Bool _bOpenLoginDays;
    _Bool _bindAccountTipsShow;
    int _vipLevel;
    int _svipLevel;
    int _vipTimeType;
    int _diyBubbleTextID;
    NSString *_dateNick;
    unsigned int _lastThemeId;
    long long _avatarPendantID;
    unsigned int _pendantDiyInfoId;
    unsigned int _vipFontID;
    unsigned int _colorRingID;
    unsigned int _comeRingID;
    NSString *_vipCenterUrl;
    _Bool _magicFontOpenFlag;
    int _customVoteId;
    unsigned int _gameAppId;
    unsigned int _gameLastLoginTime;
    unsigned int _colorfulFloatingScreenId;
    int _xo;
    unsigned int _lastThemeSuitId;
    unsigned int _themeSuitId;
    unsigned int _gameIconShowFlag;
    unsigned int _gameRank;
    NSString *_voiceBubbleId;
}

@property(nonatomic) long long avatarPendantID; // @synthesize avatarPendantID=_avatarPendantID;
@property(nonatomic) _Bool bAutoLogin; // @synthesize bAutoLogin=_bAutoLogin;
@property(nonatomic) _Bool bKeepBackGroundOnLine; // @synthesize bKeepBackGroundOnLine=_bKeepBackGroundOnLine;
@property(nonatomic) _Bool bKeepPcOnline; // @synthesize bKeepPcOnline=_bKeepPcOnline;
@property(nonatomic) _Bool bOpenLoginDays; // @synthesize bOpenLoginDays=_bOpenLoginDays;
@property(nonatomic) _Bool bRecvGroupMsg; // @synthesize bRecvGroupMsg=_bRecvGroupMsg;
@property(nonatomic) _Bool bSavePwd; // @synthesize bSavePwd=_bSavePwd;
@property(nonatomic) _Bool bThemeAuth; // @synthesize bThemeAuth=_bThemeAuth;
@property(nonatomic) _Bool bUseTabSound; // @synthesize bUseTabSound=_bUseTabSound;
@property(nonatomic) _Bool bXManIconClick; // @synthesize bXManIconClick=_bXManIconClick;
@property(nonatomic) _Bool bindAccountTipsShow; // @synthesize bindAccountTipsShow=_bindAccountTipsShow;
@property(nonatomic) int birs; // @synthesize birs=_birs;
@property(retain, nonatomic) NSString *chatAvatarID; // @synthesize chatAvatarID=_chatAvatarID;
@property(nonatomic) int city; // @synthesize city=_city;
@property(nonatomic) unsigned int colorRingID; // @synthesize colorRingID=_colorRingID;
@property(nonatomic) unsigned int colorfulFloatingScreenId; // @synthesize colorfulFloatingScreenId=_colorfulFloatingScreenId;
@property(nonatomic) unsigned int comeRingID; // @synthesize comeRingID=_comeRingID;
@property(retain, nonatomic) NSData *cookie; // @synthesize cookie=_cookie;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) int country; // @synthesize country=_country;
@property(nonatomic) int customVoteId; // @synthesize customVoteId=_customVoteId;
@property(retain, nonatomic) NSString *dateNick; // @synthesize dateNick=_dateNick;
- (void)dealloc;
- (id)description;
@property(nonatomic) int diyBubbleTextID; // @synthesize diyBubbleTextID=_diyBubbleTextID;
@property(nonatomic) unsigned int gameAppId; // @synthesize gameAppId=_gameAppId;
@property(nonatomic) unsigned int gameIconShowFlag; // @synthesize gameIconShowFlag=_gameIconShowFlag;
@property(nonatomic) unsigned int gameLastLoginTime; // @synthesize gameLastLoginTime=_gameLastLoginTime;
@property(nonatomic) unsigned int gameRank; // @synthesize gameRank=_gameRank;
@property(nonatomic) double getMsgTime; // @synthesize getMsgTime;
- (id)getNickForQzone;
@property(nonatomic) _Bool hasUsedDataLine; // @synthesize hasUsedDataLine=_hasUsedDataLine;
@property(nonatomic) int head; // @synthesize head;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
- (id)init;
- (id)initWithModel:(id)arg1;
- (_Bool)isEqualToModel:(id)arg1;
@property(nonatomic) int isShowXMan; // @synthesize isShowXMan=_isShowXMan;
@property(nonatomic) _Bool isSuperVip; // @synthesize isSuperVip=_isSuperVip;
@property(nonatomic) _Bool isVip; // @synthesize isVip=_isVip;
@property(nonatomic) unsigned int lastThemeId; // @synthesize lastThemeId=_lastThemeId;
@property(nonatomic) unsigned int lastThemeSuitId; // @synthesize lastThemeSuitId=_lastThemeSuitId;
@property(nonatomic) int lastUpdateLevelTime; // @synthesize lastUpdateLevelTime=_lastUpdateLevelTime;
@property(nonatomic) int lastUpdateQQXManTime; // @synthesize lastUpdateQQXManTime=_lastUpdateQQXManTime;
@property(nonatomic) int level; // @synthesize level=_level;
@property(nonatomic) _Bool login; // @synthesize login;
@property(retain, nonatomic) NSString *loginAccount; // @synthesize loginAccount=_loginAccount;
@property(nonatomic) int loginDay; // @synthesize loginDay=_loginDay;
@property(nonatomic) double loginTime; // @synthesize loginTime;
@property(nonatomic) _Bool magicFontOpenFlag; // @synthesize magicFontOpenFlag=_magicFontOpenFlag;
@property(retain, nonatomic) NSString *nick;
- (void)notifyDrawerOfDataChanged;
@property(nonatomic) long long onlineStatus; // @synthesize onlineStatus;
@property(nonatomic) unsigned int pendantDiyInfoId; // @synthesize pendantDiyInfoId=_pendantDiyInfoId;
@property(nonatomic) int phoneQQXManDay; // @synthesize phoneQQXManDay=_phoneQQXManDay;
@property(nonatomic) int profileSex; // @synthesize profileSex=_profileSex;
@property(nonatomic) int prov; // @synthesize prov=_prov;
@property(nonatomic) int pwd; // @synthesize pwd=_pwd;
@property(retain, nonatomic) NSString *sCity; // @synthesize sCity=_sCity;
@property(retain, nonatomic) NSString *sCountry; // @synthesize sCountry=_sCountry;
@property(retain, nonatomic) NSString *sProvince; // @synthesize sProvince=_sProvince;
@property(nonatomic) int sex; // @synthesize sex=_sex;
@property(nonatomic) _Bool shownViewOnlineFriendTips; // @synthesize shownViewOnlineFriendTips=_shownViewOnlineFriendTips;
@property(retain, nonatomic) NSString *sig; // @synthesize sig=_sig;
- (void)setSuperVip:(_Bool)arg1;
@property(nonatomic) int svipLevel; // @synthesize svipLevel=_svipLevel;
@property(retain, nonatomic) NSData *syncCookie; // @synthesize syncCookie=_syncCookie;
@property(nonatomic) unsigned int themeId; // @synthesize themeId=_themeId;
@property(nonatomic) unsigned int themeSuitId; // @synthesize themeSuitId=_themeSuitId;
@property(retain, nonatomic) NSString *themeVersion; // @synthesize themeVersion=_themeVersion;
@property(retain, nonatomic) NSString *uin; // @synthesize uin=_uin;
- (void)setVip:(_Bool)arg1;
@property(retain, nonatomic) NSString *vipCenterUrl; // @synthesize vipCenterUrl=_vipCenterUrl;
@property(nonatomic) unsigned int vipFontID; // @synthesize vipFontID=_vipFontID;
@property(nonatomic) int vipLevel; // @synthesize vipLevel=_vipLevel;
@property(nonatomic) int vipTimeType; // @synthesize vipTimeType=_vipTimeType;
@property(retain, nonatomic) NSString *voiceBubbleId; // @synthesize voiceBubbleId=_voiceBubbleId;

@end

