//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQActivity : NSObject
{
}

+ (long long)activityCategory;
- (id)activityImage;
- (id)activityTitle;
- (_Bool)isButtonDisabled;
- (_Bool)isButtonHide;
- (void)prepareWithActivityItems:(id)arg1;
- (long long)showSareOrAction;

@end

