//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QQFaceKeyBoardDelegate.h"

@class NSOperationQueue, NSString, QQAIOMarioPanelView;

@interface QQAIOMarioViewController : NSObject <QQFaceKeyBoardDelegate>
{
    QQAIOMarioPanelView *_keyboard;
    NSOperationQueue *_queue;
    _Bool _isShow;
    unsigned long long _maxCount;
    struct CGRect _qqtextfieldFrame;
}

- (void).cxx_destruct;
- (void)addOperationTaskToQueue:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (_Bool)attachMainView:(id)arg1;
- (void)cancelAllOperations;
- (void)cancelDelayHidePanel;
- (void)cellDidTapped:(id)arg1 onKeyBoard:(id)arg2;
- (void)dealloc;
- (void)delayHidePanel;
- (void)hidePanel;
- (id)initWithEmojis:(id)arg1 textfieldFrame:(struct CGRect)arg2;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
- (void)loadFace;
@property(nonatomic) unsigned long long maxCount; // @synthesize maxCount=_maxCount;
@property(nonatomic) struct CGRect qqtextfieldFrame; // @synthesize qqtextfieldFrame=_qqtextfieldFrame;
- (void)reloadWithEmojis:(id)arg1 textfieldFrame:(struct CGRect)arg2;
- (void)removePanel;
- (void)setKeyboardDelegate:(id)arg1;
- (void)setMarioPanelOriginY:(double)arg1;
- (void)showPanel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

