//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQAIOMsgModel.h"

#import "NSXMLParserDelegate.h"

@class ArkAppMsgConfig, ArkUIView, NSString, QQAIOArkAppCellView;

@interface QQAIOArkAppModel : QQAIOMsgModel <NSXMLParserDelegate>
{
    _Bool _init;
    id <ArkAppLoadDelegate> _delegate;
    _Bool _showSender;
    _Bool _isResident;
    int _errorCode;
    ArkAppMsgConfig *_msgConfig;
    ArkUIView *_arkView;
    NSString *_errorText;
    QQAIOArkAppCellView *_cellView;
    NSString *_appName;
    NSString *_appView;
    NSString *_appVersion;
    NSString *_appDesc;
    NSString *_metaStr;
    NSString *_prompt;
    struct ArkAppViewInfo _arkAppInfo;
}

+ (id)modelWithMessageModel:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appDesc; // @synthesize appDesc=_appDesc;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain, nonatomic) NSString *appView; // @synthesize appView=_appView;
@property(nonatomic) struct ArkAppViewInfo arkAppInfo; // @synthesize arkAppInfo=_arkAppInfo;
@property(retain, nonatomic) ArkUIView *arkView; // @synthesize arkView=_arkView;
- (id)cellClassName;
- (double)cellHeight;
- (id)cellIdentifier;
@property __weak QQAIOArkAppCellView *cellView; // @synthesize cellView=_cellView;
- (id)cellViewClassName;
- (void)createArkView;
- (void)dealloc;
@property(nonatomic) __weak id <ArkAppLoadDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int errorCode; // @synthesize errorCode=_errorCode;
@property(retain) NSString *errorText; // @synthesize errorText=_errorText;
- (id)eventHandleClassName;
- (struct CGSize)getSizeCache;
- (void)initArkView;
- (void)initViewSize;
- (id)initWithMessageModel:(id)arg1;
@property(nonatomic) _Bool isResident; // @synthesize isResident=_isResident;
@property(retain, nonatomic) NSString *metaStr; // @synthesize metaStr=_metaStr;
@property(retain, nonatomic) ArkAppMsgConfig *msgConfig; // @synthesize msgConfig=_msgConfig;
@property(retain, nonatomic) NSString *prompt; // @synthesize prompt=_prompt;
- (void)releaseArkView;
- (void)reloadArkView;
@property(nonatomic) _Bool showSender; // @synthesize showSender=_showSender;
- (void)setSizeCache:(struct CGSize)arg1;
- (_Bool)shouldDisplaySelfNick;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

