//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQAIOTextModel.h"

@class NSString;

@interface QQAIORomTextModel : QQAIOTextModel
{
    NSString *_content;
}

+ (id)createAIOModelWithMessageModel:(id)arg1;
- (void).cxx_destruct;
- (double)cellHeight;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
- (id)initWithMessageModel:(id)arg1;
- (_Bool)isLongSplitMessage;

@end

