//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQAIORichCellView.h"

#import "QQEmotionLabelDelegate.h"
#import "UITableViewDelegate.h"

@class NSString, QQAIORichModel, QQEmotionLabel, UIButton;

@interface QQAIORichMixCellView : QQAIORichCellView <QQEmotionLabelDelegate, UITableViewDelegate>
{
    QQEmotionLabel *_contentLabel;
    QQEmotionLabel *_contentLabel2;
    QQAIORichModel *_richModel;
    UIButton *_urlBtn;
}

- (void).cxx_destruct;
- (double)GetHeadOffset;
- (double)GetMaxWidth:(double)arg1 height:(double)arg2;
- (struct CGRect)GetTextBottomRect;
- (struct CGRect)GetTextTopRect;
- (void)clickDetailUrl;
- (void)dealloc;
- (void)drawContent:(struct CGRect)arg1;
- (void)emotionLabelHandleEmail:(id)arg1;
- (void)emotionLabelHandleIDNumber:(id)arg1;
- (void)emotionLabelHandleLongPress:(id)arg1;
- (void)emotionLabelHandlePhoneNumber:(id)arg1;
- (void)emotionLabelHandleQQNumber:(id)arg1;
- (void)emotionLabelHandleSensContent:(id)arg1;
- (void)emotionLabelHandleUrl:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 chatViewTable:(id)arg2;
- (void)layoutViewsAsReceiver;
- (void)layoutViewsAsSender;
- (void)onNotifyRevealBankCard:(id)arg1;
- (void)prepareForReuse;
- (void)preparePaopao:(id)arg1;
- (void)rePlayAnimation;
- (void)reciveFontActivedNotification:(id)arg1;
- (void)reloadAppearance;
- (void)reloadLayoutResult:(long long)arg1 needUpdateUI:(_Bool)arg2;
- (void)setAioModel:(id)arg1;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)voiceSetData:(id)arg1;
- (void)willDrawBubble;
- (void)wordSegmentUpdateDicFinished:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

