//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQFaceKeyBoard.h"

@class NSArray, UIImage;

@interface QQAIOMarioPanelView : QQFaceKeyBoard
{
    NSArray *_marioImages;
    struct CGRect _qqtextfieldFrame;
    UIImage *_cutImage;
    id _pannelController;
}

- (void).cxx_destruct;
- (void)cancelDelayHidePanel;
- (unsigned long long)columnPerPage;
@property(retain, nonatomic) UIImage *cutImage; // @synthesize cutImage=_cutImage;
- (void)delayHidePanel;
- (id)initWithEmojis:(id)arg1 textfieldFrame:(struct CGRect)arg2;
- (void)loadFace;
@property(retain, nonatomic) NSArray *marioImages; // @synthesize marioImages=_marioImages;
@property(nonatomic) __weak id pannelController; // @synthesize pannelController=_pannelController;
@property struct CGRect qqtextfieldFrame; // @synthesize qqtextfieldFrame=_qqtextfieldFrame;
- (void)reloadWithEmojis:(id)arg1 textfieldFrame:(struct CGRect)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)willDismiss;

@end

