//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQFaceFrameCollectionView.h"

@class NSArray, NSString, UIImage;

@interface QQAIODouTuFrameView : QQFaceFrameCollectionView
{
    UIImage *_cutAIOViewImage;
    NSArray *_associateEmojis;
    NSArray *_maxEmojis;
    int _xo;
    int _lastDownloadedPage;
    NSArray *_doutuImages;
    NSString *_keyword;
    unsigned long long _maxCount;
    NSString *_selectEmojiID;
}

- (void).cxx_destruct;
- (void)addFaceCellWithInfo:(id)arg1;
- (id)cellForTouchPoint:(struct CGPoint)arg1;
- (struct CGRect)cellFrameByIndex:(unsigned long long)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(retain, nonatomic) UIImage *cutAIOViewImage; // @synthesize cutAIOViewImage=_cutAIOViewImage;
- (void)dealloc;
@property(retain, nonatomic) NSArray *doutuImages; // @synthesize doutuImages=_doutuImages;
- (void)downloadPage:(int)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)getCells;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isSupportRightDragToGoBack;
@property(copy, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
- (id)loadFace:(id)arg1;
@property(nonatomic) unsigned long long maxCount; // @synthesize maxCount=_maxCount;
@property(retain, nonatomic) NSArray *maxEmojis; // @synthesize maxEmojis=_maxEmojis;
@property(copy, nonatomic) NSString *selectEmojiID; // @synthesize selectEmojiID=_selectEmojiID;
- (_Bool)showImageWithCell:(id)arg1 withImageView:(id)arg2;
- (void)showKeyBoardIfNeed;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)updateCellsFrame;

@end

