//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQAIORichModel.h"

@interface QQAIORichMixModel : QQAIORichModel
{
    long long _lastFrameIndex;
}

- (id)cellClassName;
- (double)cellHeight;
- (id)cellViewClassName;
@property(nonatomic) long long lastFrameIndex; // @synthesize lastFrameIndex=_lastFrameIndex;
- (id)makeLayoutResultWithContent:(id)arg1 andFontId:(long long)arg2;
- (void)reloadLayoutResult:(long long)arg1;
- (id)voiceOverText;

@end

