//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class QQAIOVideoCellTipsView;

@interface QQAIOStoryShareTipsView : UIView
{
    QQAIOVideoCellTipsView *_failTipsView;
}

- (void)dealloc;
- (id)getFailTipsView;
- (id)getStatusView;
- (id)getStatusViewImageName;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutAsReceiver;
- (void)layoutAsSender;
- (void)setFailTipsText:(id)arg1;
- (void)setStatutusHidden:(_Bool)arg1;
- (void)setupUI;

@end

