//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQAIOTextCellView.h"

@class ArkCardsListView, UIButton;

@interface QQAIOTextArkCellView : QQAIOTextCellView
{
    _Bool _arkButtonInited;
    _Bool _isDisableInput;
    _Bool _isCardShowInMsg;
    UIButton *_arkButton;
    ArkCardsListView *_cardListView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *arkButton; // @synthesize arkButton=_arkButton;
- (void)arkButtonDidTap:(id)arg1;
@property(retain, nonatomic) ArkCardsListView *cardListView; // @synthesize cardListView=_cardListView;
- (void)checkArkAIButton;
- (void)checkCardListView;
- (void)closeArkViewWithKeywordRange:(struct _NSRange)arg1;
- (void)createArkButton;
- (void)displayArkView;
- (void)drawContent:(struct CGRect)arg1;
- (void)emotionLabelHandleArkKeyWord:(struct _NSRange)arg1;
- (void)initArkAIUI:(id)arg1 appName:(id)arg2 equalInputText:(_Bool)arg3 contextMatchType:(int)arg4;
@property(nonatomic) _Bool isCardShowInMsg; // @synthesize isCardShowInMsg=_isCardShowInMsg;
@property(nonatomic) _Bool isDisableInput; // @synthesize isDisableInput=_isDisableInput;
- (_Bool)needParseArkAI;
- (void)onScrollEndAnimation:(id)arg1;
- (void)prepareForReuse;
- (void)reportKeywordClickedWithCardModel:(_Bool)arg1 cardModel:(id)arg2;
- (void)scrollToSelectedCardWithKeywordRange:(struct _NSRange)arg1 cardModels:(id)arg2;
- (void)setAioModel:(id)arg1;
- (void)showArkViewWithKeywordRange:(struct _NSRange)arg1 fromIcon:(_Bool)arg2;
- (void)updateArkButtonImage:(id)arg1;
- (void)willDrawBubble;

@end

