//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQAIOModel.h"

@class NSMutableAttributedString, NSString, QQGrayTipsExtInfo;

@interface QQAIOGrayTipModel : QQAIOModel
{
    struct CGRect _bgRect;
    struct CGRect _textRect;
    QQGrayTipsExtInfo *_grayTipsExtInfo;
    NSString *_content;
    _Bool _isNickNotReady;
    NSMutableAttributedString *_string;
}

+ (id)getNIAttributedLabel;
+ (id)modelWithMessageModel:(id)arg1;
- (void).cxx_destruct;
- (id)TextContentCoverToImage:(id)arg1 font:(id)arg2 maxWidth:(double)arg3;
@property(readonly, nonatomic) struct CGRect bgRect; // @synthesize bgRect=_bgRect;
- (void)calLayout;
- (id)cellClassName;
- (double)cellHeight;
- (id)cellViewClassName;
- (id)eventHandleClassName;
@property(readonly, nonatomic) QQGrayTipsExtInfo *grayTipsExtInfo; // @synthesize grayTipsExtInfo=_grayTipsExtInfo;
- (id)initWithMessageModel:(id)arg1;
- (void)insertIcon:(id)arg1 tipLabel:(id)arg2;
@property(nonatomic) _Bool isNickNotReady; // @synthesize isNickNotReady=_isNickNotReady;
- (_Bool)isWalletGrayTips;
- (void)parseGrayTipsExtInfo;
- (id)rangesWithShift:(long long)arg1 oldRanges:(id)arg2 minLocation:(unsigned long long)arg3 maxLength:(unsigned long long)arg4;
- (void)setMsgModel:(id)arg1;
@property(retain, nonatomic) NSMutableAttributedString *string; // @synthesize string=_string;
- (_Bool)shouldShowTimeline;
- (unsigned char)textAlignment;
@property(readonly, nonatomic) struct CGRect textRect; // @synthesize textRect=_textRect;

@end

