//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQModel.h"

@class FragmentConfig, NSString;

@interface QQARFragmentModel : QQModel
{
    _Bool _playing;
    int _algorithmType;
    int _playedCount;
    long long _trackMode;
    long long _arType;
    NSString *_colorConfig;
    FragmentConfig *_fragmentConfig;
    NSString *_Url;
    long long _fileSize;
    NSString *_Md5;
    NSString *_fileLocalPath;
    long long _repeatCount;
    long long _connectType;
    NSString *_tips;
    NSString *_keyingConfig;
    NSString *_videoLayout;
    NSString *_paramstring;
    QQARFragmentModel *_before;
    QQARFragmentModel *_next;
}

- (void).cxx_destruct;
@property(retain) NSString *Md5; // @synthesize Md5=_Md5;
@property(retain) NSString *Url; // @synthesize Url=_Url;
@property(nonatomic) int algorithmType; // @synthesize algorithmType=_algorithmType;
@property long long arType; // @synthesize arType=_arType;
@property(retain) QQARFragmentModel *before; // @synthesize before=_before;
@property(retain) NSString *colorConfig; // @synthesize colorConfig=_colorConfig;
@property long long connectType; // @synthesize connectType=_connectType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
@property(retain) NSString *fileLocalPath; // @synthesize fileLocalPath=_fileLocalPath;
@property long long fileSize; // @synthesize fileSize=_fileSize;
@property(retain) FragmentConfig *fragmentConfig; // @synthesize fragmentConfig=_fragmentConfig;
- (_Bool)isSameFragment:(id)arg1;
@property(retain) NSString *keyingConfig; // @synthesize keyingConfig=_keyingConfig;
- (id)localVideoPath;
@property(retain) QQARFragmentModel *next; // @synthesize next=_next;
@property(retain, nonatomic) NSString *paramstring; // @synthesize paramstring=_paramstring;
- (void)play;
@property int playedCount; // @synthesize playedCount=_playedCount;
@property _Bool playing; // @synthesize playing=_playing;
@property long long repeatCount; // @synthesize repeatCount=_repeatCount;
@property(retain) NSString *tips; // @synthesize tips=_tips;
@property long long trackMode; // @synthesize trackMode=_trackMode;
@property(retain) NSString *videoLayout; // @synthesize videoLayout=_videoLayout;
- (void)stop;

@end

