//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQARResourceManager : NSObject
{
}

+ (id)GetInstance;
- (_Bool)downloadResource:(id)arg1 recogType:(int)arg2;
- (void)downloadResourceFail:(id)arg1 err:(id)arg2 recogType:(int)arg3;
- (void)downloadResourceFeatureSuccess:(id)arg1 recogType:(int)arg2;
- (void)downloadResourceSuccess:(id)arg1 recogType:(int)arg2;
- (id)loadResourceWithData:(id)arg1 recogType:(int)arg2 jsonOrXml:(_Bool)arg3 fromMap:(_Bool)arg4 uploadTaskId:(unsigned long long)arg5;

@end

