//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSMutableDictionary, UIButtonForAVControlBar;

@interface QQAVChatControlBar : UIView
{
    NSMutableArray *_currentPresentBtInfoArray;
    int _currentBusinessType;
    UIView *_backGroundView;
    NSMutableDictionary *_OutSideInfoDic;
    int _cuttentControlBarStlye;
    UIButtonForAVControlBar *_toggleCamera;
    int _speakerState;
    UIButtonForAVControlBar *_roomManagerEx;
    _Bool NeedToFit4s;
    _Bool isTroopAudio;
    _Bool isP2PShare;
    _Bool isSpeakerHighLighted;
    _Bool isPhoneCallEnable;
    _Bool isSupportFunChat;
    _Bool _isSmartDevice;
    id <QQAVChatControlBarDelegate> _delegate;
    double vmargin;
}

- (void)AVControlbuttonPressed:(id)arg1;
@property(nonatomic) _Bool NeedToFit4s; // @synthesize NeedToFit4s;
@property(nonatomic) id <QQAVChatControlBarDelegate> _delegate; // @synthesize _delegate;
- (void)addBackground;
- (void)bindingReddotWithButton:(int)arg1 withPath:(id)arg2;
- (void)dealloc;
- (void)flashButton:(int)arg1 interval:(double)arg2 count:(int)arg3 withObject:(id)arg4 withSelector:(SEL)arg5;
- (int)getButtonState:(int)arg1;
- (id)getButtonWithId:(int)arg1;
- (int)getCurrentBusinssType;
- (struct CGRect)getTemplateFrame:(int)arg1;
- (id)getTemplateRectArray:(int)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 BusinessType:(int)arg2 isNeedTofit4s:(_Bool)arg3 animatied:(_Bool)arg4 info:(id)arg5;
- (id)initWithFrame:(struct CGRect)arg1 isNeedTofit4s:(_Bool)arg2;
- (void)insertButtonWith:(id)arg1 atIndex:(int)arg2 animatied:(_Bool)arg3 template:(int)arg4;
- (_Bool)isNeedToFit4s;
@property(nonatomic) _Bool isP2PShare; // @synthesize isP2PShare;
- (_Bool)isPhoneCallDisplay;
@property(nonatomic) _Bool isPhoneCallEnable; // @synthesize isPhoneCallEnable;
@property(nonatomic) _Bool isSmartDevice; // @synthesize isSmartDevice=_isSmartDevice;
@property(nonatomic) _Bool isSpeakerHighLighted; // @synthesize isSpeakerHighLighted;
@property(nonatomic) _Bool isSupportFunChat; // @synthesize isSupportFunChat;
@property(nonatomic) _Bool isTroopAudio; // @synthesize isTroopAudio;
- (_Bool)onCamera:(id)arg1;
- (_Bool)onClose:(id)arg1;
- (void)onManageRoom:(id)arg1;
- (void)onMemAdd:(id)arg1;
- (_Bool)onMute:(id)arg1;
- (_Bool)onPhoneCall:(id)arg1;
- (_Bool)onSpeaker:(id)arg1;
- (_Bool)onTextReplyMsg:(id)arg1;
- (_Bool)onToggleCamera:(id)arg1;
- (void)removeBackgroud;
- (void)removeButton:(int)arg1;
- (void)removeButtonatIndex:(int)arg1 animatied:(_Bool)arg2 template:(int)arg3;
- (void)repalceWith:(id)arg1 atIndex:(int)arg2 animatied:(_Bool)arg3;
- (void)setBusinessType:(int)arg1 animatied:(_Bool)arg2 info:(id)arg3;
- (void)setButtonWithBaseInfo:(id)arg1 LayoutInfo:(id)arg2 animated:(_Bool)arg3;
- (void)setGRoupGameGuildCommon:(_Bool)arg1;
- (void)setGroupCommonAnimatied:(_Bool)arg1;
- (void)setGroupVideo:(_Bool)arg1;
- (void)setGroup_EncounterReqiestingAnimated:(_Bool)arg1;
- (void)setNoAnswerAnimatied:(_Bool)arg1;
- (void)setP2P_AudioRequestingAnimatied:(_Bool)arg1;
- (void)setP2P_CommonAudioAnimatied:(_Bool)arg1;
- (void)setP2P_CommonRecevRequestAnimatied:(_Bool)arg1;
- (void)setP2P_VideoAnimatied:(_Bool)arg1;
- (void)setP2P_VideoRecvreQuestAnimatied:(_Bool)arg1;
- (void)setP2P_VideoRequestingAnimatied:(_Bool)arg1;
- (void)setPhoneCallButtonStyle:(id)arg1;
- (void)setRejected;
- (void)setTextReplyForFunCall;
- (void)setTextReplyForP2PVideo;
- (id)showbutton:(int)arg1 frame:(int)arg2;
- (void)updateAllButtons;
@property(readonly, nonatomic) double vmargin; // @synthesize vmargin;

@end

