//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SAMRequestItem.h"

@class NSArray;

@interface QQAvatarJceRequestItem : SAMRequestItem
{
    NSArray *_phoneNums;
    NSArray *_groupCodes;
}

- (void).cxx_destruct;
- (id)description;
- (char *)getRequestBuffer;
@property(readonly, nonatomic) NSArray *groupCodes; // @synthesize groupCodes=_groupCodes;
- (id)initWithGroupCodes:(id)arg1;
- (id)initWithPhoneNums:(id)arg1;
- (id)notifyRespBuffer:(const char *)arg1 len:(int)arg2 seq:(int)arg3;
@property(readonly, nonatomic) NSArray *phoneNums; // @synthesize phoneNums=_phoneNums;
- (id)serviceCmd;

@end

