//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface qqBizAgentReportInfo : NSObject
{
    NSString *_pluginID;
    NSString *_log;
    long long _clickCount;
    unsigned long long _uin;
    int _xo;
}

- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(nonatomic) long long clickCount; // @dynamic clickCount;
@property(copy, nonatomic) NSString *log; // @dynamic log;
@property(copy, nonatomic) NSString *pluginID; // @dynamic pluginID;
@property(nonatomic) unsigned long long uin; // @dynamic uin;

@end

