//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "QQUnReadAnimationDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSString, QQAPNGImageView, UIImageView, UILabel;

@interface QQButton : UIControl <QQUnReadAnimationDelegate, UIGestureRecognizerDelegate>
{
    UIImageView *_imageView;
    UIImageView *_fgImageView;
    UILabel *_titleLabel;
    QQAPNGImageView *_apngImageView;
    struct CGRect _selfFrame;
    struct CGPoint _touchBegin;
    struct CGPoint _touchNow;
    struct CGRect _originFrame;
    struct CGPoint _touchCenter;
    struct CGRect _lastLookAtFrame;
    _Bool _initedFrame;
    _Bool _canAnimate;
    int _animationType;
    id touchDelegate;
    id _unreadAnimationDelegate;
    double _fgMaxOffset;
    double _bgMaxOffset;
}

- (_Bool)_needTabAnimations;
- (void)_startBackwardAnimation;
- (void)_startMove:(double)arg1 offsetY:(double)arg2;
@property(nonatomic) int animationType; // @synthesize animationType=_animationType;
@property(retain, nonatomic) QQAPNGImageView *apngImageView; // @synthesize apngImageView=_apngImageView;
@property(nonatomic) double bgMaxOffset; // @synthesize bgMaxOffset=_bgMaxOffset;
@property(nonatomic) _Bool canAnimate; // @synthesize canAnimate=_canAnimate;
- (void)dealThemeAnimateTabWithSelected:(_Bool)arg1;
- (void)dealloc;
- (void)endDrag;
@property(retain, nonatomic) UIImageView *fgImageView; // @synthesize fgImageView=_fgImageView;
@property(nonatomic) double fgMaxOffset; // @synthesize fgMaxOffset=_fgMaxOffset;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (void)handleSwipeGesture:(id)arg1;
- (void)handleTapGesture:(id)arg1;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool initedFrame; // @synthesize initedFrame=_initedFrame;
- (void)layoutSubviews;
- (void)removeApngAnimateView;
- (void)setSelected:(_Bool)arg1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) id touchDelegate; // @synthesize touchDelegate;
@property(nonatomic) id unreadAnimationDelegate; // @synthesize unreadAnimationDelegate=_unreadAnimationDelegate;
- (void)startDragFromPoint:(struct CGPoint)arg1 toPoint:(struct CGPoint)arg2;
- (void)startLookAtAnimation:(_Bool)arg1;
- (void)startScaleAnimation;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

