//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface QQCampusCollege : NSObject
{
    unsigned long long _collegeId;
    NSString *_name;
    NSString *_desc;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long collegeId; // @synthesize collegeId=_collegeId;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;

@end

