//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, NSString, NSTimer, UIButton;

@interface QQCallBackView : UIView
{
    NSTimer *_timer;
    int _index;
    NSLayoutConstraint *_lightDotLeftContraint;
    UIView *_centerView;
    UIButton *_endButton;
    UIView *_maskView;
    NSString *_chatName;
    CDUnknownBlockType _endCallBackBlock;
}

- (void)cleanup;
- (void)dismissWithCompletion:(CDUnknownBlockType)arg1;
- (void)endCallBackAction:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType endCallBackBlock; // @synthesize endCallBackBlock=_endCallBackBlock;
- (id)init;
- (id)initWithChatName:(id)arg1;
- (void)onTimer:(id)arg1;
- (void)showElements;
- (void)showMaskImmediatelyWithWithCompletion:(CDUnknownBlockType)arg1;
- (void)showMaskWithCompletion:(CDUnknownBlockType)arg1;

@end

