//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQViewController.h"

@interface QQContactsIssueViewController : QQViewController
{
    int _issueType;
    int _issueCount;
}

- (void)buttonPressed:(id)arg1;
- (id)init;
@property(nonatomic) int issueCount; // @synthesize issueCount=_issueCount;
@property(nonatomic) int issueType; // @synthesize issueType=_issueType;
- (void)loadView;
- (void)setupViews;

@end

