//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseFileCell.h"

#import "UIActionSheetDelegate.h"

@class NSString, QQDataLineModel;

@interface QQDataLineCell : QQBaseFileCell <UIActionSheetDelegate>
{
    QQDataLineModel *_model;
    id <QQDataLineCellDelegate> _delegate;
}

- (void)OnFileRecordUpdate:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addObserver;
- (void)alertViewClicked:(long long)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)dealloc;
@property(nonatomic) id <QQDataLineCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didActionButtonTouch;
- (void)forwardTo:(id)arg1;
- (id)getAccessibilityValue;
- (id)getBaseChatViewController;
- (void)getFileIconWithBlock:(CDUnknownBlockType)arg1;
- (void)getFileImage:(int)arg1 block:(CDUnknownBlockType)arg2;
- (void)getHeadImageWithBlock:(CDUnknownBlockType)arg1;
- (id)getMenuItems;
- (id)getMultiPicTitle;
- (void)getTransferInfoWithBlock:(CDUnknownBlockType)arg1;
- (void)menuActionAddToFace:(id)arg1;
@property(retain, nonatomic) QQDataLineModel *model; // @synthesize model=_model;
- (void)onFavorite:(id)arg1;
- (void)saveToWeiyun:(id)arg1;
- (void)setAioModel:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

