//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, QQFaceCell, UICollectionView, UITouch, UIView;

@protocol QQFaceEmojiCollectionViewDelegate <NSObject>
- (void)QQFaceEmojiCollectionView:(UICollectionView *)arg1 didSelectItemAtIndexPath:(NSIndexPath *)arg2;
- (void)addQutuSettingButtonOnClick;
- (void)customFaceSettingButtonOnClick;
- (void)moveToPoint:(UITouch *)arg1 view:(UIView *)arg2;
- (void)stopAtPoint:(UITouch *)arg1 data:(id)arg2 view:(UIView *)arg3;

@optional
- (void)QQFaceEmojiCollectionView:(QQFaceCell *)arg1;
@end

