//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQMutipleImageHandler.h"

@class NSArray;

@interface QQForwardMutipleImageHandler : QQMutipleImageHandler
{
    NSArray *_picInfoArray;
    NSArray *_checkedArray;
}

+ (id)createPicInfoByMessageModel:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *checkedArray; // @synthesize checkedArray=_checkedArray;
- (void)compressOriginalImage:(id)arg1;
- (void)createPicInfoArray;
- (void)handlerWillCallbackSuccessfully;
@property(retain, nonatomic) NSArray *picInfoArray; // @synthesize picInfoArray=_picInfoArray;
- (void)prepareForwardByMessageModelArray:(id)arg1;
- (id)prepareNeedDownloadArray;

@end

