//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQSearchBaseViewController.h"

#import "GroupListViewDelegate.h"
#import "QQCreateGroupAuthorityDelegate.h"
#import "QQPopMenuDelegate.h"
#import "QQSearchResultClickResponding.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class GroupListViewNew, NSString, NSTimer, ODRefreshControl, QQPopMenu;

@interface QQGroupListViewController : QQSearchBaseViewController <QQSearchResultClickResponding, UITableViewDataSource, UITableViewDelegate, GroupListViewDelegate, QQPopMenuDelegate, QQCreateGroupAuthorityDelegate>
{
    GroupListViewNew *_groupListView;
    ODRefreshControl *_refreshControl;
    int _getGroupListSeq;
    NSTimer *_refreshListTimer;
    QQPopMenu *_popupMenu;
    _Bool _hideCellAccessory;
}

- (void)addGroup;
- (void)createGroup;
- (void)createPopupMenu;
- (void)dealloc;
- (void)delayEndRefreshing:(_Bool)arg1;
- (void)didMenuClick:(int)arg1;
- (void)dropViewDidBeginRefreshing:(id)arg1;
- (void)groupListViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)groupListViewDidScroll:(id)arg1;
- (void)groupMsgSetting;
@property(nonatomic) _Bool hideCellAccessory; // @synthesize hideCellAccessory=_hideCellAccessory;
- (id)init;
- (_Bool)isSupportFullScreenLayout;
- (void)leftButtonClick:(id)arg1;
- (void)loadView;
- (void)onGetCreateGroupAuthority:(int)arg1 groupCode:(unsigned int)arg2 groupUin:(unsigned int)arg3 sign:(id)arg4 svrErrorCode:(int)arg5;
- (void)onResultCellClick:(id)arg1;
- (void)prepareRightBtnForAnimat;
- (void)refreshGroupList;
- (void)refreshGroupListResult:(id)arg1;
- (void)refreshGroupListSuccess;
- (void)refreshListTimeout;
- (void)resetGroupHeadRequestState;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)showCommonGroupSettingLimitation:(id)arg1;
- (void)showPopupMenu;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

