//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQAIOCommonCellView.h"

@class QQGroupFileAIOModel, QQGroupFileInfo, QQGroupFileTask, UIButton, UIView;

@interface QQGroupFileCellView : QQAIOCommonCellView
{
    UIView *_contentView;
    UIButton *_bottomButton;
    QQGroupFileAIOModel *_groupFileAIOModel;
}

- (void).cxx_destruct;
- (id)accessibilityValue;
- (void)actionAskForMore:(id)arg1;
- (void)bottomButtonAction;
- (void)bubbleAction;
- (_Bool)canCancelDownload;
- (_Bool)canCancelUpload;
- (_Bool)canDownload;
- (_Bool)canFavorite;
- (_Bool)canForward;
- (_Bool)canForwardWeiyun;
- (_Bool)canPause;
- (_Bool)canReply;
- (_Bool)canResume;
- (_Bool)canSendToPC;
- (void)cancelDownload:(id)arg1;
- (void)cancelUpload:(id)arg1;
- (void)didTapFailIcon:(id)arg1;
- (_Bool)didTouchEnded:(id)arg1 withEvent:(id)arg2;
- (void)download:(id)arg1;
@property(readonly, nonatomic) QQGroupFileInfo *fileInfo;
- (void)forwardTo:(id)arg1;
- (void)forwardToWeiyun:(id)arg1;
- (id)getMenuItems;
@property(retain, nonatomic) QQGroupFileAIOModel *groupFileAIOModel; // @synthesize groupFileAIOModel=_groupFileAIOModel;
- (_Bool)hasMoreMemu;
- (id)initWithFrame:(struct CGRect)arg1 chatViewTable:(id)arg2;
- (void)loadBubbleInfo;
- (void)onFavorite:(id)arg1;
- (void)pause:(id)arg1;
- (void)preparePaopao:(id)arg1;
- (void)refreshProgress;
- (void)refreshStatus;
- (void)reply:(id)arg1;
- (id)reportReversed3;
- (void)resume:(id)arg1;
- (void)sendFailViewAction;
- (void)sendToPC:(id)arg1;
- (_Bool)shouldDisplayMsgSendFail;
@property(readonly, nonatomic) QQGroupFileTask *task;
- (void)willDrawBubble;

@end

