//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQPublishViewHandler.h"

#import "QQGTTaskUploadBatchManagerDelegate.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, QQGTCachePhotoOnlineManager, QQGTDraftModel, QQGTTaskUploadBatchManager, QQWebViewController;

@interface QQGroupTribePublishViewHandler : QQPublishViewHandler <QQGTTaskUploadBatchManagerDelegate>
{
    int _selectedMediaType;
    NSMutableArray *_mediaContent;
    _Bool _waitPublish;
    NSDictionary *passThroughMsg;
    QQGTTaskUploadBatchManager *_picBatchMgr;
    QQGTCachePhotoOnlineManager *_onlineCacheManager;
    NSString *_curBid;
    NSDictionary *_publishContent;
    QQWebViewController *_webviewController;
    NSString *_callback;
    NSString *_title;
    _Bool _needToSaveDraft;
    QQGTDraftModel *_draftModel;
    int _fromFlag;
    _Bool _isFirstCall;
    int _defaultCategory;
    NSArray *_thirdAppImagePaths;
    int _sourceType;
    int _groupType;
    NSString *_groupUin;
    CDUnknownBlockType _cancelCallBack;
    CDUnknownBlockType _confirmCallBack;
}

- (void)GTTaskUploadBatchManagerOnFinishFileUpload:(id)arg1 imagetag:(long long)arg2 info:(id)arg3;
- (void)callbackToWeb:(int)arg1 result:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType cancelCallBack; // @synthesize cancelCallBack=_cancelCallBack;
- (_Bool)checkRecordFileUpload;
- (void)clearSendMedia;
@property(copy, nonatomic) CDUnknownBlockType confirmCallBack; // @synthesize confirmCallBack=_confirmCallBack;
- (id)currentOpEnter;
- (void)dataReport:(int)arg1 withInfor:(id)arg2;
- (void)dealloc;
- (void)doSomethingBeforeDisappear;
- (void)downloadAIOPic:(id)arg1;
- (int)enterSourceForPublish;
- (void)fixTribeArgument;
- (id)generateMergeInfoFromCGIResponse:(id)arg1;
- (id)getCurrentPhotoTask;
- (id)getPublishOtherParams;
- (id)getUploadPhotoInfo;
- (void)handleAIOOrignalImageDownloadStateNotification:(id)arg1;
- (void)hasDefaultCategory:(int)arg1;
- (id)initWithParam:(id)arg1;
- (_Bool)loadInfoFromThirdApp;
- (void)preUploadRecordFileSendRequest:(_Bool)arg1;
- (void)publishViewDidChangeBid:(id)arg1 newCondition:(id)arg2;
- (void)publishViewDidClickCancleBtn:(id)arg1;
- (void)publishViewDidClickConfirmBtn:(id)arg1;
- (void)publishViewDidDeleteCell:(int)arg1;
- (void)publishViewDidLoad;
- (void)publishViewDidLoadForDownload:(_Bool)arg1;
- (void)publishViewDidSelectImage:(id)arg1 isSelected:(_Bool)arg2;
- (void)publishViewDidSelectRecord:(id)arg1 isSelected:(_Bool)arg2;
- (void)publishViewDidSimplyChangeBidUsingSuggestTribe:(id)arg1;
- (void)reportWhenTopicPublishIsFail:(id)arg1 reserve3:(id)arg2;
- (void)requestAIOImageTimeout;
- (void)saveTheCurrentDraft;
- (void)sendPublishRequest;
- (void)uniformLogForGroupWithOpName:(id)arg1 reserve2:(id)arg2;
- (void)uniformLogWithOpName:(id)arg1 reserve2:(id)arg2;
- (void)uniformLogWithOpName:(id)arg1 reserve2:(id)arg2 reserve3:(id)arg3;
- (void)unilogExpPublish;
- (void)unilogSuccessPublish;
- (void)updateBid:(id)arg1;
- (void)updateByDraftData;
- (void)uploadRecordFile:(id)arg1;

// Remaining properties
@property(retain, nonatomic) NSString *callback; // @dynamic callback;
@property(retain, nonatomic) NSString *curBid; // @dynamic curBid;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSMutableArray *mediaContent; // @dynamic mediaContent;
@property(copy, nonatomic) NSDictionary *publishContent; // @dynamic publishContent;
@property(readonly) Class superclass;
@property(retain, nonatomic) QQWebViewController *webviewController; // @dynamic webviewController;

@end

