//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEngineDispatchDelegate.h"

@class NSMutableArray, NSString;

@interface qqha1sacdb : NSObject <IEngineDispatchDelegate>
{
    struct _QQSecDtHandler *_ha4g12jlad;
    NSMutableArray *_llc34ja21d;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)ac2da7fc;
- (void)dealloc;
- (void)didRecievedMsg:(CDStruct_7895f40e)arg1;
@property(nonatomic) struct _QQSecDtHandler *ha4g12jlad; // @synthesize ha4g12jlad=_ha4g12jlad;
- (id)init;
@property(retain, nonatomic) NSMutableArray *llc34ja21d; // @synthesize llc34ja21d=_llc34ja21d;
- (void)lmg11ta5:(id)arg1;
- (void)notifyError:(id)arg1;
- (void)ta9bcd32:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

