//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AutoPbModel.h"

@class GetAuthDataRsp;

@interface QQHotchatAutoInfoRsp : AutoPbModel
{
    GetAuthDataRsp *_authData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GetAuthDataRsp *authData; // @synthesize authData=_authData;
- (id)getPropertyInfos;

@end

