//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NearbyBaseViewController.h"

#import "NIAttributedLabelDelegate.h"
#import "NearByBannerTipViewDelegate.h"
#import "NearByBannerViewDelegate.h"
#import "NearbyAlmnusBannerViewDelegate.h"
#import "NearbyBannerTipManageDelegate.h"
#import "NearbyFriendTableViewDelegate.h"
#import "QQLbsLoginHeartTipWindowDelegate.h"
#import "QUIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"

@class BannerModel, CUserData, NMFeedListLBSDenyView, NSArray, NSData, NSDictionary, NSMutableArray, NSString, NearbyAlumnusBannerStorage, NearbyAlumnusModel, NearbyBannerTipManager, NearbyFaceScoreEntranceView, NearbyFriendTableView, NearbySelfInfoModel, ODRefreshControl, QQLbsLoginHeartTipWindow, QQNearByFilterModel, QQNobodyView, QQTableFootView, QUIActionSheet, UIButton, UIGestureRecognizer, UILabel, UITapGestureRecognizer, UIView;

@interface QQLbsNearbyFriendViewController : NearbyBaseViewController <QUIActionSheetDelegate, UIAlertViewDelegate, NearbyFriendTableViewDelegate, NIAttributedLabelDelegate, NearByBannerViewDelegate, NearbyAlmnusBannerViewDelegate, NearbyBannerTipManageDelegate, NearByBannerTipViewDelegate, QQLbsLoginHeartTipWindowDelegate>
{
    NSMutableArray *_dataList;
    NearbyFriendTableView *_tableView;
    QQTableFootView *_tableFootView;
    QQNobodyView *_nobodyView;
    UIButton *_downButton;
    _Bool _reloading;
    _Bool _bAutoRefresh;
    ODRefreshControl *_refreshControl;
    double _contentOffset;
    _Bool _locationEnable;
    NSString *_headUin;
    NSData *_coverFileKey;
    UIView *_tableHeaderView;
    _Bool _isDownloadCover;
    NSString *_sig;
    int _lon;
    int _lat;
    NSString *_throughTitle;
    struct CGRect _tableHeaderViewRect;
    struct CGRect _tableRect;
    long long _heartIncreament;
    long long _videoOnlineCount;
    QUIActionSheet *_actionSheet;
    UITapGestureRecognizer *_gesture;
    _Bool firstGet;
    NSArray *_nearbyAdInfo;
    QQNearByFilterModel *_curFilterModel;
    NMFeedListLBSDenyView *_lbsDenyView;
    _Bool _isFirstPageFlag;
    _Bool _isPulldownRefresh;
    int _xo;
    QQNearByFilterModel *_roamFilterModel;
    NearbyAlumnusModel *_nearbyAlumnusModel;
    NearbyAlumnusBannerStorage *_nearbyAlumnusStorage;
    NSMutableArray *_bannerModels;
    long long _predicate;
    UIGestureRecognizer *_tapGesture;
    UILabel *_loadingText;
    _Bool _isListEnd;
    int _alumnusSource;
    CUserData *_userData;
    NearbyBannerTipManager *_bannerTipManager;
    NSDictionary *_nearbyRecommendationInfo;
    BannerModel *_businessBannerModel;
    NearbyFaceScoreEntranceView *_faceScoreEntranceView;
    NSString *_faceScoreUrl;
    NearbySelfInfoModel *_curSelfInfoModel;
    long long _faceLikeCount;
    QQLbsLoginHeartTipWindow *_loginTipWindow;
}

+ (id)lastRequestTimeKey;
- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addFaceScoreEntranceView;
- (void)adjustNobodyViewFrame;
@property(nonatomic) int alumnusSource; // @synthesize alumnusSource=_alumnusSource;
- (void)attributedLabel:(id)arg1 didSelectTextCheckingResult:(id)arg2 atPoint:(struct CGPoint)arg3;
@property(retain, nonatomic) NearbyBannerTipManager *bannerTipManager; // @synthesize bannerTipManager=_bannerTipManager;
@property(retain, nonatomic) BannerModel *businessBannerModel; // @synthesize businessBannerModel=_businessBannerModel;
- (_Bool)canJumpToTinyId;
- (void)cleanBusinessBannerModel;
- (void)clearBannerTipView;
- (void)clearHeartIncreament;
- (void)clearLBSInfoAndPop:(int)arg1;
- (void)clearNobodyView;
- (void)clearVideoOnlineCount;
- (void)closeBtnPressed:(id)arg1;
- (void)closeWindow:(id)arg1;
@property(retain) NearbySelfInfoModel *curSelfInfoModel; // @synthesize curSelfInfoModel=_curSelfInfoModel;
- (void)dealloc;
- (void)deleteAlumnusBanner;
- (void)didModifyPersonProfileNotification:(id)arg1;
- (void)doneLoadingTableViewData:(_Bool)arg1 failTips:(id)arg2;
- (void)dropViewDidBeginRefreshing:(id)arg1;
- (void)encounterV2RequestFail:(id)arg1;
- (void)enterForeground;
@property(nonatomic) long long faceLikeCount; // @synthesize faceLikeCount=_faceLikeCount;
@property(retain, nonatomic) NearbyFaceScoreEntranceView *faceScoreEntranceView; // @synthesize faceScoreEntranceView=_faceScoreEntranceView;
@property(retain, nonatomic) NSString *faceScoreUrl; // @synthesize faceScoreUrl=_faceScoreUrl;
- (void)filterDoneCallback:(id)arg1;
- (id)filterStringForReport:(id)arg1;
- (id)findSamePositionLocalAdModelFor:(id)arg1;
- (id)getBannerArr;
- (id)getBusinessBannerModel;
- (void)getEncounterCallback:(id)arg1 isFirstPage:(_Bool)arg2;
- (void)getFaceScoreConfig;
- (long long)getLikeCount;
- (_Bool)getMoreData:(id)arg1;
- (_Bool)getMoreEncounter;
- (id)getNearbyAlumnusModel;
- (id)getNearbyCurrentFilterModel;
- (void)getNearbyEncounter:(id)arg1 filter:(id)arg2 sourceType:(int)arg3;
- (id)getNobodyView:(int)arg1;
- (long long)heartIncreament;
- (void)hideLoadingIndicator;
- (id)init;
- (id)insertJumpPeopleInfo:(id)arg1;
- (id)insertNearbyAds:(id)arg1;
- (id)insertNearbyRecommendationArray:(id)arg1;
- (_Bool)isHaveBanner;
- (_Bool)isHaveBusinessBanner;
@property(nonatomic) _Bool isListEnd; // @synthesize isListEnd=_isListEnd;
- (_Bool)isNoEncounter;
- (void)jumpToTinyId;
@property(retain, nonatomic) NMFeedListLBSDenyView *lbsDenyView; // @dynamic lbsDenyView;
- (void)loadAdListCache;
- (void)loadAlumnusBanner;
- (void)loadBannerModel;
- (void)loadBusinessBannerModel;
- (void)loadNearbyRecommendationInfoCache;
- (void)loadNearbySelfInfoModelCache;
- (void)loadView;
@property(retain, nonatomic) QQLbsLoginHeartTipWindow *loginTipWindow; // @synthesize loginTipWindow=_loginTipWindow;
- (void)nearbyAlmnusBannerViewDidClicked;
- (void)nearbyAlmnusBannerViewDidClose;
- (void)nearbyBannerTipViewDidClick:(id)arg1;
- (void)nearbyBannerTipViewWillDisplay:(id)arg1;
- (void)nearbyGuideTips;
@property(retain, nonatomic) NSDictionary *nearbyRecommendationInfo; // @synthesize nearbyRecommendationInfo=_nearbyRecommendationInfo;
- (_Bool)needResetControllerTitle;
- (void)needResetFilterModel:(id)arg1;
- (_Bool)needShowBusinessNearbyBanner;
- (_Bool)needShowFaceMateAndVideoChatSection;
- (_Bool)needShowNearByAdBanner;
- (_Bool)needShowNearByAlumnusBanner;
- (void)onFilterButtonClick;
- (void)onFilterDone:(id)arg1;
- (void)onReceive:(id)arg1;
- (void)onUpdateFaceScoreClientConfigure:(id)arg1;
- (void)onUpdatePushBanner;
- (id)parserXmlString:(id)arg1;
- (void)refreshEncounterList;
- (_Bool)refreshTableList:(id)arg1;
- (void)registerNotification;
- (void)reloadAppearance;
@property(nonatomic) _Bool reloading; // @synthesize reloading=_reloading;
- (void)requestCharmInfoChange;
- (void)requestFaceScoreClientConfig;
- (void)requestNearbyEntrance;
- (void)resetContentView:(_Bool)arg1 failTips:(id)arg2;
- (void)resetControllerTitle;
- (id)restoreNearByFilterModel;
- (void)saveAlumnusBanner;
- (void)saveNearByFilterModel;
- (long long)scanMaxNumberForReport;
- (void)scrollContentToTop;
@property(retain, nonatomic) QQNearByFilterModel *curFilterModel; // @dynamic curFilterModel;
- (void)setDefaultNearByFilterModel;
@property(retain, nonatomic) CUserData *userData; // @synthesize userData=_userData;
- (void)showActionSheet;
- (void)showCharmInfoPushViewWithTitle:(id)arg1 score:(int)arg2;
- (void)showLoadingIndicator;
- (void)showLocationFailedView;
- (void)showRightButton;
- (void)showSecurityAlertWithTips:(id)arg1 strSecurityUrl:(id)arg2;
- (void)updateContentView;
- (long long)videoOnlineCount;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSArray *nearbyAdInfo; // @dynamic nearbyAdInfo;
@property(readonly) Class superclass;

@end

