//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface QQMarioImageCacheCenter : NSObject
{
    NSMutableDictionary *_allImageMetas;
    NSString *_metaDir;
}

+ (id)getInstance;
- (void)addOneImage:(id)arg1;
- (void)appDidCrashed;
- (void)appDidEnterBackground;
- (void)appWillTerminate;
- (void)checkValidityOfFilePath:(id)arg1;
- (void)clearAllTmpGifImage;
- (void)clearAllTmpTextImage;
- (void)dealloc;
- (void)deleteAllData:(id)arg1;
- (void)deleteAllImages;
- (void)deleteOneImageMeta:(id)arg1;
- (void)eliminateMetaData;
- (id)getMarioImageMetaDir;
- (id)init;
- (void)initAllMetas;
- (id)judgeIfLocalImageExist:(id)arg1;
- (id)marioImageSavePath;
- (id)marioTmpGifDir;
- (id)marioTmpTextImageDir;
- (void)saveAllMetas;
- (void)saveMetaDatas:(id)arg1 path:(id)arg2;

@end

