//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQMultimediaPreEditComponent.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSArray, NSString, UICollectionView, UILabel, UIView;

@interface QQMultimediaEditBeautyComponent : QQMultimediaPreEditComponent <UICollectionViewDelegateFlowLayout, UICollectionViewDataSource>
{
    UIView *_beautyPanel;
    UILabel *_label;
    UICollectionView *_collectView;
    NSArray *_data;
    _Bool _hasAddPendantKVO;
    _Bool _isFirst;
    id <QQMultimediaEditBeautyDelegate> _beautyDelegate;
}

- (void).cxx_destruct;
- (void)addPendantKVO;
@property(nonatomic) __weak id <QQMultimediaEditBeautyDelegate> beautyDelegate; // @synthesize beautyDelegate=_beautyDelegate;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)createBeautyPanel;
- (void)createCollectView;
- (void)createLabel;
- (void)dealloc;
- (id)initWithCaptureEditMode:(long long)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onClickBeautyLevel:(long long)arg1;
- (void)onSwitchCamera:(long long)arg1;
- (void)refreshComponentParam;
- (void)removePendantKVO;
- (void)setLastBeauty;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

