//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationBar.h"

@interface QQNavigationBar : UINavigationBar
{
}

- (struct CGRect)getThroughPassTouchResponseRect;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)isExistRightButtonItems;
- (void)layoutCustomViewForLeftBarButtonItem;
- (void)layoutCustomViewForRightBarButtonItem;
- (void)layoutCustomViewForRightBarButtonItems;
- (void)layoutSubviews;
- (void)layoutTitleView;
- (void)removeShadowLine;
- (void)setBackgroundImage:(id)arg1 forBarMetrics:(long long)arg2;

@end

