//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSRecursiveLock;

@interface QQObjectSubPool : NSObject
{
    NSRecursiveLock *_dictLock;
    NSMutableDictionary *_objectDict;
    int _type;
    const struct _RecoverConfig *_config;
    unsigned long long _curTime;
}

- (void)UpdateCurrentTime:(unsigned long long)arg1;
- (id)allKeys;
- (unsigned long long)count;
- (unsigned long long)currentTime;
- (void)dealloc;
- (id)getObjectDict;
- (const struct _RecoverConfig *)getRecoverConfig;
- (id)initWithType:(int)arg1;
- (void)lock;
- (id)objectDictionary;
- (id)objectForKey:(id)arg1;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (int)subPoolType;
- (void)unlock;

@end

