//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEngineDispatchDelegate.h"

@class NSMutableDictionary, NSString;

@interface QQOpenGroupMgr : NSObject <IEngineDispatchDelegate>
{
    NSMutableDictionary *_openGroupModelDict;
    NSMutableDictionary *_reqPendingGroupDict;
    NSMutableDictionary *_recvNotJoinOpenGroupMsgSendExitCmd;
}

+ (id)getInstance;
- (void)addPendingGroupSeq:(int)arg1 groupCode:(id)arg2 reqType:(unsigned int)arg3;
- (void)changeAccount;
- (void)cmdError:(int)arg1 r:(int)arg2;
- (void)dealloc;
- (void)didRecievedMsg:(CDStruct_7895f40e)arg1;
- (id)getAndRemovePendingGroupSeq:(int)arg1;
- (id)getMemberModelWith:(id)arg1 memUin:(id)arg2;
- (id)getOpenGroupModel:(id)arg1;
- (void)getTroopMemberResult:(id)arg1;
- (id)init;
- (_Bool)isHasGroup:(id)arg1;
- (_Bool)isJoinOpenGroup:(id)arg1;
- (_Bool)isOpenGroupMember:(id)arg1 memUin:(id)arg2;
- (void)notifyError:(id)arg1;
- (_Bool)openGroupMessageProcess:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *openGroupModelDict; // @synthesize openGroupModelDict=_openGroupModelDict;
- (void)parsePbBuffer:(char *)arg1 size:(int)arg2 seq:(int)arg3;
- (_Bool)parsePbBufferInner:(id)arg1 seq:(int)arg2;
@property(retain, nonatomic) NSMutableDictionary *recvNotJoinOpenGroupMsgSendExitCmd; // @synthesize recvNotJoinOpenGroupMsgSendExitCmd=_recvNotJoinOpenGroupMsgSendExitCmd;
- (void)recvNotJoinOpenGroupMsgSendExitCmd:(id)arg1;
- (void)recvOpenGroupKickedPush:(id)arg1;
- (void)recvOpenGroupSettingPush:(id)arg1 settingType:(int)arg2;
@property(retain, nonatomic) NSMutableDictionary *reqPendingGroupDict; // @synthesize reqPendingGroupDict=_reqPendingGroupDict;
- (_Bool)requestOpenGroup:(id)arg1 join:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

