//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIActionSheetDelegate.h"

@class NSArray, NSString, QQPACardViewController;

@interface QQPACardActionSheetHandler : NSObject <UIActionSheetDelegate>
{
    NSArray *_shareItemArray;
    QQPACardViewController *_cardVC;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(nonatomic) __weak QQPACardViewController *cardVC; // @synthesize cardVC=_cardVC;
- (void)dealloc;
- (void)handleRightBtnEvent:(long long)arg1;
- (void)handleSetting:(id)arg1 index:(long long)arg2;
- (id)initWithCardVC:(id)arg1;
- (void)showMsgSettingSheetWithDic:(id)arg1;
- (void)showShareSheetNeedMore:(unsigned long long)arg1;
- (void)showUnfollowConfirmSheet;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

