//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

#import "MCTempManagerDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class MCGridVideoItem, NSMutableArray, NSString, UICollectionViewFlowLayout;

@interface QQPendantItemPanel : UICollectionView <UICollectionViewDelegate, UICollectionViewDataSource, MCTempManagerDelegate>
{
    NSMutableArray *_reloadIndexPaths;
    NSMutableArray *_pendantArray;
    long long _classificationID;
    NSString *_categoryName;
    UICollectionViewFlowLayout *_pendantLayout;
    NSMutableArray *_downloadArray;
    MCGridVideoItem *_unLoadSelectedItem;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *categoryName; // @synthesize categoryName=_categoryName;
@property(nonatomic) long long classificationID; // @synthesize classificationID=_classificationID;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (_Bool)collectionView:(id)arg1 shouldDeselectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
@property(retain, nonatomic) NSMutableArray *downloadArray; // @synthesize downloadArray=_downloadArray;
- (void)downloadResource:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
@property(retain, nonatomic) NSMutableArray *pendantArray; // @synthesize pendantArray=_pendantArray;
@property(retain, nonatomic) UICollectionViewFlowLayout *pendantLayout; // @synthesize pendantLayout=_pendantLayout;
- (void)reloadData;
- (void)removeItemByID:(id)arg1;
- (void)selectTmplItem:(id)arg1 temState:(long long)arg2;
- (id)setSelectedID:(id)arg1;
@property(retain, nonatomic) MCGridVideoItem *unLoadSelectedItem; // @synthesize unLoadSelectedItem=_unLoadSelectedItem;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

