//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface QQPluginObject : NSObject
{
    NSString *_pluginId;
    NSArray *_pluginServiceNames;
    _Bool _needCheckUpdate;
    int _pluginType;
    id _pluginService;
}

- (_Bool)cleanMemory;
- (void)dealloc;
- (id)getDependentServices;
- (id)getServices;
- (long long)getVersion;
- (void)initParam;
- (_Bool)initPluginService;
- (id)initWithClassName:(id)arg1;
- (id)initWithPluginId:(id)arg1;
- (id)invokeService:(id)arg1 withParam:(id)arg2;
- (_Bool)isAvailable;
- (_Bool)isSuportService:(id)arg1;
@property(nonatomic) _Bool needCheckUpdate; // @synthesize needCheckUpdate=_needCheckUpdate;
@property(retain, nonatomic) NSString *pluginId; // @synthesize pluginId=_pluginId;
@property(retain, nonatomic) id pluginService; // @synthesize pluginService=_pluginService;
@property(nonatomic) int pluginType; // @synthesize pluginType=_pluginType;

@end

