//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface QQPluginFeedCountManager : NSObject
{
    NSString *_uin;
    NSMutableDictionary *_feedCountMap;
}

+ (id)feedCountPathname;
+ (id)instance;
- (void)dealloc;
- (id)getFeedCountWithPluginID:(int)arg1;
- (id)init;
- (void)load;
- (void)resetFeedCountWithPluginID:(int)arg1;
- (void)save;
- (void)setFeedCount:(id)arg1;
- (void)setFeedCount:(id)arg1 withPluginID:(int)arg2;
@property(retain, nonatomic) NSString *uin; // @synthesize uin=_uin;
- (void)updateFeedCount:(id)arg1 withPluginID:(int)arg2;

@end

