//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, QQAIOMsgModel, QQRecentMessageModel;

@interface QQPublicAccountFolderModel : NSObject
{
    _Bool _isInTopState;
    int _setTopStateTime;
    NSString *_uin;
    NSString *_nick;
    NSString *_timeString;
    long long _unreadCount;
    NSString *_contentText;
    NSString *_contentImage;
    NSString *_contentWebUrl;
    QQRecentMessageModel *_accountModel;
    QQAIOMsgModel *_latestMsgModel;
    unsigned long long _latestMsgType;
    unsigned long long _msgTime;
}

@property(retain, nonatomic) QQRecentMessageModel *accountModel; // @synthesize accountModel=_accountModel;
- (id)changeToSmallSizeUrlWithCoverUrl:(id)arg1;
@property(copy, nonatomic) NSString *contentImage; // @synthesize contentImage=_contentImage;
@property(copy, nonatomic) NSString *contentText; // @synthesize contentText=_contentText;
@property(copy, nonatomic) NSString *contentWebUrl; // @synthesize contentWebUrl=_contentWebUrl;
- (void)dealloc;
- (void)generateContentWithAIOMsgModel:(id)arg1;
- (id)getLatestMessage:(id)arg1;
- (unsigned long long)getMessageType:(id)arg1;
- (id)initWithAccountModel:(id)arg1;
@property(nonatomic) _Bool isInTopState; // @synthesize isInTopState=_isInTopState;
@property(retain, nonatomic) QQAIOMsgModel *latestMsgModel; // @synthesize latestMsgModel=_latestMsgModel;
@property(nonatomic) unsigned long long latestMsgType; // @synthesize latestMsgType=_latestMsgType;
@property(nonatomic) unsigned long long msgTime; // @synthesize msgTime=_msgTime;
@property(copy, nonatomic) NSString *nick; // @synthesize nick=_nick;
@property(nonatomic) int setTopStateTime; // @synthesize setTopStateTime=_setTopStateTime;
@property(copy, nonatomic) NSString *timeString; // @synthesize timeString=_timeString;
@property(copy, nonatomic) NSString *uin; // @synthesize uin=_uin;
@property(nonatomic) long long unreadCount; // @synthesize unreadCount=_unreadCount;

@end

