//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQModel.h"

#import "IQQModelLabel.h"

@class NSArray, NSMutableArray, NSString;

@interface QQPublicAccountModel : QQModel <IQQModelLabel>
{
    long long _uin;
    NSString *_name;
    NSString *_summary;
    _Bool _recvMsg;
    unsigned int _certifyGrade;
    int _priority;
    NSString *_pinyinStr;
    NSString *_sortkeyStr;
    struct _NSRange _matchRange;
    _Bool _isMatchUIN;
    _Bool _isEnglishName;
    int _classifyID;
    int _showFlag;
    _Bool _isHidden;
    long long _accountType;
    long long _mappingUin;
    long long _accountPolicy;
    NSMutableArray *_rangeArr;
    int _xo;
    _Bool _bOffLine;
    _Bool _bSubscribed;
    NSString *_displayNumber;
    NSString *_simplePinyinStr;
    NSArray *_tags;
    unsigned long long _ind;
    unsigned long long _enterTime;
    unsigned long long _noEnterDays;
    unsigned long long _clickCount;
    unsigned long long _clickPercent;
    long long _account_flag;
}

+ (void)setSearchModelPriority:(int)arg1;
- (void).cxx_destruct;
@property(nonatomic) long long account_flag; // @synthesize account_flag=_account_flag;
@property(nonatomic) _Bool bOffLine; // @synthesize bOffLine=_bOffLine;
@property(nonatomic) _Bool bSubscribed; // @synthesize bSubscribed=_bSubscribed;
@property unsigned int certifyGrade; // @synthesize certifyGrade=_certifyGrade;
@property int classifyID; // @synthesize classifyID=_classifyID;
@property(nonatomic) unsigned long long clickCount; // @synthesize clickCount=_clickCount;
@property(nonatomic) unsigned long long clickPercent; // @synthesize clickPercent=_clickPercent;
- (long long)compareByNick:(id)arg1;
- (long long)compareLabel:(id)arg1;
- (long long)comparebyPriorityAndNick:(id)arg1;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) NSString *displayNumber; // @synthesize displayNumber=_displayNumber;
@property(nonatomic) unsigned long long enterTime; // @synthesize enterTime=_enterTime;
- (id)getModelLabel;
- (struct _NSRange)getModelLabelMatchRange;
@property(retain, nonatomic, getter=getPinYinStr) NSString *pinyinStr; // @synthesize pinyinStr=_pinyinStr;
- (id)getRemarkLabel;
- (int)getSearchModelPriority;
- (int)getSearchModelType;
@property(retain, nonatomic, getter=getSimplePinYinStr) NSString *simplePinyinStr; // @synthesize simplePinyinStr=_simplePinyinStr;
@property(retain, nonatomic, getter=getSortkeyStr) NSString *sortkeyStr; // @synthesize sortkeyStr=_sortkeyStr;
@property(nonatomic) unsigned long long ind; // @synthesize ind=_ind;
- (_Bool)isMatchString:(id)arg1;
- (_Bool)isString:(id)arg1 matchString:(id)arg2;
@property long long mappingUin; // @synthesize mappingUin=_mappingUin;
@property(nonatomic) unsigned long long noEnterDays; // @synthesize noEnterDays=_noEnterDays;
@property(retain, nonatomic) NSMutableArray *rangeArr; // @synthesize rangeArr=_rangeArr;
@property _Bool recvMsg; // @synthesize recvMsg=_recvMsg;
@property int showFlag; // @synthesize showFlag=_showFlag;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property long long uin; // @synthesize uin=_uin;

// Remaining properties
@property(nonatomic) long long accountType; // @dynamic accountType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isEnglishName; // @dynamic isEnglishName;
@property(nonatomic) _Bool isHidden; // @dynamic isHidden;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) int priority; // @dynamic priority;
@property(retain, nonatomic) NSString *summary; // @dynamic summary;
@property(readonly) Class superclass;

@end

