//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQSearchBaseLogicEngine.h"

@class NSArray, NSMutableArray;

@interface QQRelationLogicEngine : QQSearchBaseLogicEngine
{
    NSMutableArray *_groupList;
    NSMutableArray *_discussGroupList;
    NSMutableArray *_pubAccountList;
    NSMutableArray *_searchResult;
    NSMutableArray *_countArray;
    _Bool _isReloadingGroupList;
    long long _seqFollowList;
    NSMutableArray *_pubAccountListInContactList;
    long long _uinNeededFilterPubAcctMsg;
    _Bool _pubAcctListReady;
}

+ (id)getInstance;
- (void)dealloc;
@property(readonly, nonatomic) NSArray *discussGroupList; // @synthesize discussGroupList=_discussGroupList;
- (id)getGroupModelByUin:(unsigned long long)arg1;
- (id)getPublicAccountModel:(unsigned long long)arg1;
@property(readonly) NSArray *groupList; // @synthesize groupList=_groupList;
- (void)handlePublicAccountNotification:(id)arg1;
- (void)handleQQAccountLogoutNotification:(id)arg1;
- (id)init;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(readonly, nonatomic) NSArray *pubAccountList; // @synthesize pubAccountList=_pubAccountList;
@property(readonly, nonatomic) NSArray *pubAccountListInContactList; // @synthesize pubAccountListInContactList=_pubAccountListInContactList;
- (void)refreshPublicAccountList;
- (void)refreshPublicAccountListAfterDelay;
- (void)refreshPublicAccountListAtOnce;
- (id)relationSearchResultCell:(id)arg1 indexPath:(id)arg2;
- (void)relationSearchResultDidSelectRow:(id)arg1;
- (void)relationSearchResultDidSelectRowCommonProcess:(id)arg1;
- (void)reloadDiscussGroupListData;
- (void)reloadDiscussGroupListDataAfterDelay;
- (void)reloadFriendListData;
- (void)reloadFriendListDataAfterDelay;
- (void)reloadGroupListData;
- (void)reloadGroupListDataAfterDelay;
- (void)reloadPublicAcountList;
- (void)reloadPublicAcountListAfterDelay;
- (void)reloadSearchTableData:(id)arg1 filterType:(int)arg2;
- (void)reloadSourceData;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;

@end

