//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQReportBaseModel.h"

#import "QQReportProtocol.h"

@class NSString;

@interface QQReport629Model : QQReportBaseModel <QQReportProtocol>
{
    NSString *_opKey;
    NSString *_opStatus;
}

+ (id)keyList;
- (void).cxx_destruct;
- (_Bool)compare:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)logKey;
- (id)logString;
- (id)merge:(id)arg1;
- (id)modelWithLogString:(id)arg1;
@property(copy, nonatomic) NSString *opKey; // @synthesize opKey=_opKey;
@property(copy, nonatomic) NSString *opStatus; // @synthesize opStatus=_opStatus;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

