//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PhotoBrowserEnhancedViewContoller.h"

@class NSArray, QQMessageModel;

@interface QQReceiptMsgPhotoBrowserViewController : PhotoBrowserEnhancedViewContoller
{
    _Bool _showOriginalButton;
    QQMessageModel *msgModel;
    NSArray *resModels;
}

- (void)cancelOriginalPhotoDownloading;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (id)getToolbarItems;
- (void)handleChatOrignalImageDownloadProgressNotification:(id)arg1;
- (void)handleChatOrignalImageDownloadStateNotification:(id)arg1;
- (id)init;
@property(retain, nonatomic) QQMessageModel *msgModel; // @synthesize msgModel;
@property(retain, nonatomic) NSArray *resModels; // @synthesize resModels;
- (void)resetOriginalButtonState;
@property(nonatomic) _Bool showOriginalButton; // @synthesize showOriginalButton=_showOriginalButton;
- (_Bool)startDownloadOriginalPhoto;
- (void)viewDidLoad;

@end

