//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQReportBaseModel.h"

#import "QQReportProtocol.h"

@class NSString;

@interface QQReport1616Model : QQReportBaseModel <QQReportProtocol>
{
    NSString *_appName;
    NSString *_opType;
    NSString *_opName;
    long long _result;
    long long _entry;
    long long _count;
    long long _usedTime;
    long long _reserve1;
    long long _reserve2;
    NSString *_reserve3;
    NSString *_reserve4;
    long long _os;
}

+ (id)keyList;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *appName; // @synthesize appName=_appName;
- (_Bool)compare:(id)arg1;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(readonly, copy) NSString *description;
@property(nonatomic) long long entry; // @synthesize entry=_entry;
- (id)init;
- (id)logKey;
- (id)logString;
- (id)merge:(id)arg1;
- (id)modelWithLogString:(id)arg1;
@property(copy, nonatomic) NSString *opName; // @synthesize opName=_opName;
@property(copy, nonatomic) NSString *opType; // @synthesize opType=_opType;
@property(readonly, nonatomic) long long os; // @synthesize os=_os;
@property(nonatomic) long long reserve1; // @synthesize reserve1=_reserve1;
@property(nonatomic) long long reserve2; // @synthesize reserve2=_reserve2;
@property(copy, nonatomic) NSString *reserve3; // @synthesize reserve3=_reserve3;
@property(copy, nonatomic) NSString *reserve4; // @synthesize reserve4=_reserve4;
@property(nonatomic) long long result; // @synthesize result=_result;
@property(nonatomic) long long usedTime; // @synthesize usedTime=_usedTime;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

