//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBiuUploadBaseViewController.h"

#import "PhotoBrowserViewControllerDelegate.h"
#import "QQMultiImagePickerControllerDelegate.h"
#import "QQRichMediaPickerControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UINavigationControllerDelegate.h"

@class HotPicInfo, NSDictionary, NSMutableArray, NSString, QQReadInJoyUGCUploadChooseView, QQReadInJoyUGCUploadShowView;

@interface QQReadInJoyUGCUploadViewController : QQBiuUploadBaseViewController <QQMultiImagePickerControllerDelegate, UINavigationControllerDelegate, QQRichMediaPickerControllerDelegate, PhotoBrowserViewControllerDelegate, UIActionSheetDelegate>
{
    int _currentMsfApnNetworkState;
    _Bool _isUseOriginImage;
    int _seqRequest;
    unsigned int _compressPicElapse;
    unsigned int _uploadPicElapse;
    CDUnknownBlockType _ugcResultCallBackBlock;
    CDUnknownBlockType _ugcResultCallBlockBackup;
    NSDictionary *_query;
    QQReadInJoyUGCUploadChooseView *_chooseView;
    QQReadInJoyUGCUploadShowView *_showView;
    NSMutableArray *_selectedPicInfoList;
    NSMutableArray *_compressedPicInfoList;
    double _ugcStartTime;
    long long _selectedOrientation;
    double _uploadPicStartTime;
    unsigned long long _originPicFileSize;
    unsigned long long _compressPicFileSize;
    HotPicInfo *_hotPicInfo;
}

- (void).cxx_destruct;
- (void)QQMultiImagePickerController:(id)arg1 didClickPhoto:(id)arg2 isSelected:(_Bool)arg3;
- (void)QQMultiImagePickerController:(id)arg1 didSelectOriginalPhotoList:(id)arg2;
- (void)QQMultiImagePickerController:(id)arg1 didSelectPhotoList:(id)arg2;
- (void)QQMultiImagePickerController:(id)arg1 didSendEditedPhoto:(id)arg2;
- (void)QQMultiImagePickerControllerDidCancel:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)biuArticleView;
- (void)cancelUpload;
- (void)chooseImage;
@property(retain, nonatomic) QQReadInJoyUGCUploadChooseView *chooseView; // @synthesize chooseView=_chooseView;
@property(nonatomic) unsigned int compressPicElapse; // @synthesize compressPicElapse=_compressPicElapse;
@property(nonatomic) unsigned long long compressPicFileSize; // @synthesize compressPicFileSize=_compressPicFileSize;
@property(retain, nonatomic) NSMutableArray *compressedPicInfoList; // @synthesize compressedPicInfoList=_compressedPicInfoList;
- (void)createNewSociallizeInfoIfEmpty;
- (void)dealChooseImage:(_Bool)arg1 didSelectPhotoList:(id)arg2;
- (void)dealloc;
- (void)delayCheckCommitState:(id)arg1;
- (void)didReceiveMemoryWarning;
- (unsigned long long)getBiuClickType;
- (struct CGRect)getRealImageFrame:(struct CGRect)arg1 andImageSize:(struct CGSize)arg2;
- (id)getUploadImageURL:(id)arg1;
- (void)handleImageUploadFinish:(id)arg1;
@property(retain, nonatomic) HotPicInfo *hotPicInfo; // @synthesize hotPicInfo=_hotPicInfo;
- (id)init;
- (id)initWithJSWebQuery:(id)arg1;
- (_Bool)isMyUploadImageResponse:(id)arg1;
- (_Bool)isSendBtnShouldEnable;
@property(nonatomic) _Bool isUseOriginImage; // @synthesize isUseOriginImage=_isUseOriginImage;
- (id)normalizedImage:(id)arg1;
- (void)onBiuClick:(id)arg1;
- (void)onClickCancelUpload;
- (void)onClickExpressionBtn;
- (void)onClickHotPicBtn;
- (void)onLeftButton:(id)arg1;
@property(nonatomic) unsigned long long originPicFileSize; // @synthesize originPicFileSize=_originPicFileSize;
- (void)photoBrowserViewContoller:(id)arg1 didSelectImage:(id)arg2;
- (void)popQQController:(_Bool)arg1;
- (void)presentInViewController:(id)arg1;
@property(retain, nonatomic) NSDictionary *query; // @synthesize query=_query;
- (void)refreshArticleViewLayout;
- (void)refreshEditViewMaxHeightWithMaxY:(double)arg1;
- (void)richMediaPickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)richMediaPickerControllerDidCancel:(id)arg1;
@property(nonatomic) long long selectedOrientation; // @synthesize selectedOrientation=_selectedOrientation;
@property(retain, nonatomic) NSMutableArray *selectedPicInfoList; // @synthesize selectedPicInfoList=_selectedPicInfoList;
- (void)sendHotPicGifImgUseForward:(id)arg1;
- (void)sendUGC;
@property(nonatomic) int seqRequest; // @synthesize seqRequest=_seqRequest;
- (void)setSendResultCallBackBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) QQReadInJoyUGCUploadShowView *showView; // @synthesize showView=_showView;
@property(copy, nonatomic) CDUnknownBlockType ugcResultCallBackBlock; // @synthesize ugcResultCallBackBlock=_ugcResultCallBackBlock;
@property(copy, nonatomic) CDUnknownBlockType ugcResultCallBlockBackup; // @synthesize ugcResultCallBlockBackup=_ugcResultCallBlockBackup;
@property(nonatomic) double ugcStartTime; // @synthesize ugcStartTime=_ugcStartTime;
@property(nonatomic) unsigned int uploadPicElapse; // @synthesize uploadPicElapse=_uploadPicElapse;
@property(nonatomic) double uploadPicStartTime; // @synthesize uploadPicStartTime=_uploadPicStartTime;
- (void)showPreviewImage:(id)arg1;
- (_Bool)uploadImage:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

