//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVCaptureDeviceFormat, AVFrameRateRange;

@interface QQRichDeviceFormat : NSObject
{
    AVCaptureDeviceFormat *_format;
    AVFrameRateRange *_frameRateRange;
}

+ (id)formatWithDeviceFormat:(id)arg1 frameRateRange:(id)arg2;
- (void)dealloc;
- (id)description;
@property(retain, nonatomic) AVCaptureDeviceFormat *format; // @synthesize format=_format;
@property(retain, nonatomic) AVFrameRateRange *frameRateRange; // @synthesize frameRateRange=_frameRateRange;

@end

