//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSRecursiveLock, NSString;

@interface QQRichMediaConfigManager : NSObject
{
    NSArray *_filterData;
    NSArray *_dummyFilterData;
    NSRecursiveLock *_filterDataLock;
    NSString *_currentFilterUin;
}

+ (id)getInstance;
- (void).cxx_destruct;
- (_Bool)QQAppReviewConfig;
- (id)QQFilterConfigWithStatus:(long long)arg1;
- (id)QQPendantConfig;
- (void)asynQQFilterConfig:(CDUnknownBlockType)arg1;
- (void)checkFilterPreDownload;
- (void)converDummyFilterToModels:(id)arg1;
- (id)converFilterConfigToModels:(id)arg1;
- (id)dirForFilter;
- (void)downloadFilterItem:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (id)getDefaultPendantList;
- (id)getFilterModelWithName:(id)arg1;
- (id)getPandentList:(_Bool)arg1;
- (id)init;
- (_Bool)isFilterResReady:(id)arg1;
- (void)loadDefaultFilterConfig;
- (id)pathForFilterItem:(id)arg1 exist:(_Bool *)arg2;
- (void)saveFilterRedDotConfig:(id)arg1;
- (void)savePendantRedDotConfig:(id)arg1;
- (void)saveQQAppReviewConfig:(id)arg1;
- (void)saveQQFilterConfig:(id)arg1;
- (void)saveQQPendantConfig:(id)arg1;

@end

