//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TBStrokeStylePickerViewDelegate.h"

@class NSString, TBExtendedHitButton, TBStrokeStylePickerView;

@interface QQRichTinyVideoGraffitiEditView : UIView <TBStrokeStylePickerViewDelegate>
{
    long long _switchColorTimes;
    id <QQRichTinyVideoGraffitiEditViewDelegate> _delegate;
    TBExtendedHitButton *_undoBtn;
    TBStrokeStylePickerView *_sliderColorView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <QQRichTinyVideoGraffitiEditViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)onUndoButtonClear:(id)arg1;
- (void)onUndoButtonClick:(id)arg1;
- (void)setDoodleColorAtItemIndex:(int)arg1;
@property(retain, nonatomic) TBStrokeStylePickerView *sliderColorView; // @synthesize sliderColorView=_sliderColorView;
@property(retain, nonatomic) TBExtendedHitButton *undoBtn; // @synthesize undoBtn=_undoBtn;
- (void)setUndoBtnColor:(id)arg1;
- (void)strokeStylePickerView:(id)arg1 pickColor:(id)arg2 drawStep:(unsigned long long)arg3 resourceInfo:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

