//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FtnModel, NSString, QQStarUploadTask, TXVideoRequestModel;

@interface QQStarUploadEngine : NSObject
{
    _Bool _isUploading;
    _Bool _isStopUpload;
    int _uploadStatus;
    int _uploadRetryCounts;
    long long _uploadSpeed;
    long long _uploadProgress;
    QQStarUploadTask *_task;
    NSString *_urlString;
    FtnModel *_model;
    CDUnknownBlockType _uploadBlock;
    CDUnknownBlockType _uploadProgressBlock;
    TXVideoRequestModel *_videoParams;
    double _uploadTime;
    long long _uploadCurrentOffset;
    long long _uploadNextOffset;
}

- (void).cxx_destruct;
- (long long)calcUploadSpeed:(long long)arg1;
- (void)cancelUpload;
- (void)dealloc;
- (id)initWithVideoParamsModel:(id)arg1;
@property(nonatomic) _Bool isStopUpload; // @synthesize isStopUpload=_isStopUpload;
@property(nonatomic) _Bool isUploading; // @synthesize isUploading=_isUploading;
- (_Bool)isUploadingTask;
@property(retain, nonatomic) FtnModel *model; // @synthesize model=_model;
- (void)scheduleUploadDataForTask;
- (void)setProgressBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) QQStarUploadTask *task; // @synthesize task=_task;
@property(copy, nonatomic) CDUnknownBlockType uploadBlock; // @synthesize uploadBlock=_uploadBlock;
@property(nonatomic) long long uploadCurrentOffset; // @synthesize uploadCurrentOffset=_uploadCurrentOffset;
@property(nonatomic) long long uploadNextOffset; // @synthesize uploadNextOffset=_uploadNextOffset;
@property(nonatomic) long long uploadProgress; // @synthesize uploadProgress=_uploadProgress;
@property(copy, nonatomic) CDUnknownBlockType uploadProgressBlock; // @synthesize uploadProgressBlock=_uploadProgressBlock;
@property(nonatomic) int uploadRetryCounts; // @synthesize uploadRetryCounts=_uploadRetryCounts;
@property(nonatomic) long long uploadSpeed; // @synthesize uploadSpeed=_uploadSpeed;
@property(nonatomic) int uploadStatus; // @synthesize uploadStatus=_uploadStatus;
@property(nonatomic) double uploadTime; // @synthesize uploadTime=_uploadTime;
@property(copy, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(retain, nonatomic) TXVideoRequestModel *videoParams; // @synthesize videoParams=_videoParams;
- (void)stopUpload;
- (void)uploadCodeConnect;
- (void)uploadMp4:(id)arg1 thumbnail:(id)arg2 timeout:(long long)arg3 block:(CDUnknownBlockType)arg4;
- (void)uploadVideoWithblock:(CDUnknownBlockType)arg1;

@end

