//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "QQStorySGVideoSelectorItemViewDelegate.h"
#import "TBBizNetworkLogicDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSMutableArray, NSString, QQStorySGVideoSelectorCellModel;

@interface QQStorySGVideoSelectorListView : UIScrollView <UIScrollViewDelegate, QQStorySGVideoSelectorItemViewDelegate, TBBizNetworkLogicDelegate>
{
    _Bool _isDragLeftToEnd;
    NSMutableArray *_reusableItems;
    NSMutableArray *_visibleItems;
    NSMutableArray *_totalModels;
    unsigned long long _seq;
    QQStorySGVideoSelectorCellModel *_model;
    id <QQStorySGVideoSelectorListViewActionDelegate> _actionDelegate;
}

@property(nonatomic) id <QQStorySGVideoSelectorListViewActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (void)addItems:(id)arg1;
- (void)appendModels:(id)arg1;
- (void)clearItems;
- (void)dealloc;
- (id)dequeueReusableItem;
- (void)didClickShareGroupVideo:(id)arg1;
- (void)didReceivedData:(unsigned long long)arg1 requestModel:(id)arg2 classModel:(id)arg3;
- (void)didRequestFail:(unsigned long long)arg1 requestModel:(id)arg2 error:(id)arg3;
- (_Bool)didSelectShareGroupVideo:(id)arg1;
- (void)enqueueReusableItem:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handleSimpleInfoList:(id)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)loadItem:(id)arg1;
- (void)loadItemsInRange:(struct _NSRange)arg1;
@property(retain, nonatomic) QQStorySGVideoSelectorCellModel *model; // @synthesize model=_model;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)reloadVideoModels;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

