//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQStoryViewController.h"

#import "IAsynDownloadImageObserver.h"
#import "QQVideoCaptureViewControllerDelegate.h"

@class HeadButtonLongPress, NSString;

@interface QQStoryTopTabViewController : QQStoryViewController <QQVideoCaptureViewControllerDelegate, IAsynDownloadImageObserver>
{
    HeadButtonLongPress *_headButton;
}

- (void).cxx_destruct;
- (id)avatarAnimateView;
- (_Bool)configurationDiscoveryBtn;
- (_Bool)configurationDiscoveryBtnV720;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)downloadImageFinished:(id)arg1;
- (id)exitAnimationView;
@property(retain, nonatomic) HeadButtonLongPress *headButton; // @synthesize headButton=_headButton;
- (void)onHeadButtonClick;
- (void)pushDiscovery:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

