//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQTwinkleCircleProgressView.h"

@class NSArray, NSTimer;

@interface QQStoryFakeProgressView : QQTwinkleCircleProgressView
{
    NSTimer *_fakeProgressTimer;
    NSArray *_fakeProgressMaxPercentage;
    unsigned long long _fakeStageTotalCount;
    unsigned long long _fakeStageCurrentCount;
    double _currentProgress;
    _Bool _didShow;
}

- (void)addFakeProgressTimer;
- (void)dealloc;
- (void)initFakeMaxPercentage;
- (void)initFakeProgressArgu;
- (_Bool)isShow;
- (double)maxCurrentPercentageForState:(unsigned long long)arg1;
- (double)maxCurrentStatePercentage;
- (double)progress;
- (void)setFakeProgressAction;
- (void)setProgress:(double)arg1 animated:(_Bool)arg2;
- (void)startFakeProgress;
- (void)startNextState;
- (void)startTwinkle:(_Bool)arg1;
- (void)stopFakeProgressTimer;
- (void)stopTwinkle:(_Bool)arg1;

@end

