//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQViewController.h"

#import "MQZoneTableFootLoadingViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSMutableArray, NSString, QQStorySGMemberFooter, UICollectionView;

@interface QQStorySGMemberViewController : QQViewController <UICollectionViewDelegate, UICollectionViewDataSource, MQZoneTableFootLoadingViewDelegate>
{
    NSString *_groupID;
    _Bool _hasJoin;
    _Bool _isEnd;
    unsigned int _totalCount;
    id <QQStorySGMemberViewControllerDelegate> _delegate;
    UICollectionView *_collectionView;
    NSMutableArray *_unionIDList;
    QQStorySGMemberFooter *_footer;
    NSString *_cookie;
}

+ (void)prepareMemberListDataWithGroupId:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
@property(retain, nonatomic) NSString *cookie; // @synthesize cookie=_cookie;
- (void)dealloc;
@property(nonatomic) __weak id <QQStorySGMemberViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
- (void)didReceivedData:(unsigned long long)arg1 requestModel:(id)arg2 classModel:(id)arg3;
- (void)didRequestFail:(unsigned long long)arg1 requestModel:(id)arg2 error:(id)arg3;
- (void)failedToConnect;
@property(retain, nonatomic) QQStorySGMemberFooter *footer; // @synthesize footer=_footer;
@property(nonatomic) _Bool hasJoin; // @synthesize hasJoin=_hasJoin;
- (id)initWithGroupID:(id)arg1 pageType:(unsigned long long)arg2;
@property(nonatomic) _Bool isEnd; // @synthesize isEnd=_isEnd;
- (_Bool)isSupportRightDragToGoBack;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)refreshAppenedMemberList;
- (void)refreshDataRequest;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setNavigationBarTheme;
@property(nonatomic) unsigned int totalCount; // @synthesize totalCount=_totalCount;
@property(retain, nonatomic) NSMutableArray *unionIDList; // @synthesize unionIDList=_unionIDList;
- (void)stopFooterLoading;
- (void)tableFootLoadingViewDidTriggerLoading:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

