//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class QQVipComicExpandButton, QQVipComicVideoPlayer, QQVipComicVideoProgress, QQVipFunctionBlurView, TVKLitePlayer, UIButton;

@interface QQVipComicVideoPlayerBar : UIView
{
    _Bool _isPlaying;
    _Bool _isSliding;
    TVKLitePlayer *_player;
    QQVipComicVideoPlayer *_comicVideoPlayer;
    QQVipFunctionBlurView *_blurBackground;
    QQVipComicExpandButton *_playButton;
    QQVipComicExpandButton *_playNextButton;
    UIButton *_selectButton;
    QQVipComicVideoProgress *_progressView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) QQVipFunctionBlurView *blurBackground; // @synthesize blurBackground=_blurBackground;
- (void)comicPlayer:(id)arg1 notifyCurrent:(double)arg2 notifyTotoal:(double)arg3 notifyCache:(double)arg4;
- (void)comicPlayer:(id)arg1 notifyState:(int)arg2;
@property(nonatomic) __weak QQVipComicVideoPlayer *comicVideoPlayer; // @synthesize comicVideoPlayer=_comicVideoPlayer;
- (void)comicVideoPlayerStateChange:(id)arg1;
- (void)commonInit;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)nextButtonClick:(id)arg1;
@property(retain, nonatomic) QQVipComicExpandButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) QQVipComicExpandButton *playNextButton; // @synthesize playNextButton=_playNextButton;
- (void)playbuttonClick:(id)arg1;
@property(nonatomic) __weak TVKLitePlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) QQVipComicVideoProgress *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIButton *selectButton; // @synthesize selectButton=_selectButton;
- (void)selectButtonClick:(id)arg1;
- (void)setIsTouching:(_Bool)arg1;
- (void)sliderEndTouch:(id)arg1;
- (void)sliderValueChange:(id)arg1;
- (id)timeFormatted:(int)arg1;
- (void)updatePlayButtonState:(_Bool)arg1;

@end

