//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface QQWaitingView : UIView
{
    id _delegate;
}

@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
- (void)endActivityLoading;
- (void)hiddenWaitingTextLabel;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setIndicatorViewStyle:(long long)arg1;
- (void)starActivityLoading;

@end

