//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class QQWalletBasic;

@interface QQWalletBankExtraInfo : JceObjectV2
{
    QQWalletBasic *_jcev2_p_0_o_basic;
}

+ (id)jceType;
- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic, getter=jce_basic, setter=setJce_basic:) QQWalletBasic *jcev2_p_0_o_basic; // @synthesize jcev2_p_0_o_basic=_jcev2_p_0_o_basic;

@end

