//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQWebViewPluginQQBizBase.h"

#import "UIActionSheetDelegate.h"

@class NSString, TwoDimensionBarcodeManager, UIActionSheet, UILongPressGestureRecognizer;

@interface QQWebviewImageOptimizePlugin : QQWebViewPluginQQBizBase <UIActionSheetDelegate>
{
    TwoDimensionBarcodeManager *_qrcodeMgr;
    NSString *_scanResult;
    UILongPressGestureRecognizer *_longPressRecognizer;
    _Bool _hasQRCode;
    UIActionSheet *webViewAction;
    NSString *_imagePath;
    NSString *_srcUrl;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)creatHttpClientSession:(_Bool)arg1;
- (void)dealloc;
- (float)getFreeMemory;
- (struct CGSize)getProperlySize:(struct CGSize)arg1;
- (_Bool)handleEvent:(int)arg1 userInfo:(id)arg2;
- (void)handleLongPressToSave:(id)arg1;
- (void)handleQRCode;
- (id)init;
- (void)loadGesture;
- (id)qrcodeDecode:(struct CGImage *)arg1;
@property(retain, nonatomic) TwoDimensionBarcodeManager *qrcodeMgr; // @synthesize qrcodeMgr=_qrcodeMgr;
- (id)scaleToSize:(id)arg1 size:(struct CGSize)arg2;
@property(retain, nonatomic) NSString *srcUrl; // @synthesize srcUrl=_srcUrl;
- (_Bool)shouldScanQRCode;
- (void)showActionSheet;
- (void)showActionSheet:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

