//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, QQHttpClientSession;

@interface QQWhiteListFileMgr : NSObject
{
    NSDate *_updateTime;
    QQHttpClientSession *_session;
}

+ (id)getInstance;
- (void)clearConnState;
- (void)dealloc;
- (_Bool)downConfigFromPb;
- (id)getLocalWhiteListWithKey:(id)arg1;
- (void)handleWhiteListContentLoaded:(id)arg1;
- (id)init;
- (void)loadLocalConfig;
- (void)onDownloadConfigFromPbFail:(id)arg1;
- (void)onDownloadConfigFromPbSuccess:(id)arg1;
- (void)qqHttpSessionDidLoad:(id)arg1 result:(id)arg2;
- (void)qqHttpSessionError:(id)arg1 error:(id)arg2;
- (void)registerNotifications;
- (void)reportHttpStatusWhenResponse:(long long)arg1;
- (void)saveConfig:(id)arg1 forResultKey:(id)arg2 andSaveKey:(id)arg3 action:(_Bool)arg4;
- (void)saveConfigToLocalFile:(id)arg1;
@property(retain, nonatomic) QQHttpClientSession *session; // @synthesize session=_session;
@property(retain, nonatomic) NSDate *updateTime; // @synthesize updateTime=_updateTime;
- (void)unregisterNotifications;
- (_Bool)updateWhiteList;

@end

