//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEngineDispatchDelegate.h"

@class IEngineDispatchDelegateNonRetian, NSDictionary, NSMutableArray, NSMutableDictionary, NSRecursiveLock, NSString, NSTimer, QQWifiLRUCache;

@interface QQWifiNodeManager : NSObject <IEngineDispatchDelegate>
{
    IEngineDispatchDelegateNonRetian *_csDelegate;
    _Bool _hasWifiNodeReq;
    _Bool _needUpdateLBS;
    double _lastLBSTime;
    NSTimer *_delayReqTimer;
    NSMutableArray *_delayReqObjSet;
    NSRecursiveLock *_lbsLock;
    NSRecursiveLock *_delayReqLock;
    NSRecursiveLock *_callbackLock;
    QQWifiLRUCache *_wifiNodeLRUCache;
    QQWifiLRUCache *_apNodeInfoLRUCache;
    NSDictionary *_lbsCfg;
    NSMutableDictionary *_gpsCfg;
    NSMutableDictionary *_dictCallback;
}

+ (id)sharedInstance;
- (void)addDelayReqWifiNodeSet:(id)arg1 delegate:(id)arg2 enableTimer:(_Bool)arg3;
- (void)addLbsNotification;
@property(retain, nonatomic) QQWifiLRUCache *apNodeInfoLRUCache; // @synthesize apNodeInfoLRUCache=_apNodeInfoLRUCache;
@property(retain, nonatomic) NSRecursiveLock *callbackLock; // @synthesize callbackLock=_callbackLock;
- (_Bool)checkApNodeConfig;
- (void)clearDelayReqTimer;
- (void)dealloc;
@property(retain, nonatomic) NSRecursiveLock *delayReqLock; // @synthesize delayReqLock=_delayReqLock;
@property(retain, nonatomic) NSMutableArray *delayReqObjSet; // @synthesize delayReqObjSet=_delayReqObjSet;
@property(retain, nonatomic) NSTimer *delayReqTimer; // @synthesize delayReqTimer=_delayReqTimer;
@property(retain, nonatomic) NSMutableDictionary *dictCallback; // @synthesize dictCallback=_dictCallback;
- (void)didRecievedMsg:(CDStruct_7895f40e)arg1;
- (id)findWifiNode:(id)arg1 signalStrength:(double)arg2;
- (void)getGPSLocation;
- (void)getGPSLocationInternal;
@property(retain, nonatomic) NSMutableDictionary *gpsCfg; // @synthesize gpsCfg=_gpsCfg;
- (void)handleDelayReqWifiNodeSet;
- (void)handleGPSLocationRequest;
- (void)handleGetApNodeInfoList_Failed:(int)arg1;
- (void)handleGetApNodeInfoList_Succ:(CDStruct_7895f40e)arg1;
- (void)handleGetApNodeInfo_Failed:(int)arg1;
- (void)handleGetApNodeInfo_Succ:(CDStruct_7895f40e)arg1;
- (void)handleGetLocFieldSucc:(id)arg1;
- (void)handleGetLocationFail:(id)arg1;
- (void)handleGetLocationSucc:(id)arg1;
- (void)handleRequestTimeout:(id)arg1;
- (void)handleUpdateLocationEnd:(id)arg1;
- (void)handleWifiNodeFragment:(int)arg1;
- (void)handleWifiNodeNextFragment;
@property _Bool hasWifiNodeReq; // @synthesize hasWifiNodeReq=_hasWifiNodeReq;
- (id)init;
@property double lastLBSTime; // @synthesize lastLBSTime=_lastLBSTime;
@property(retain, nonatomic) NSDictionary *lbsCfg; // @synthesize lbsCfg=_lbsCfg;
@property(retain, nonatomic) NSRecursiveLock *lbsLock; // @synthesize lbsLock=_lbsLock;
@property _Bool needUpdateLBS; // @synthesize needUpdateLBS=_needUpdateLBS;
- (void)notifyApNodeInfoListCallBack:(int)arg1 isSuccess:(_Bool)arg2 ApNodeCheckResult:(id)arg3;
- (void)notifyApNodeInfoListCallBack_GetApNodeInfo:(_Bool)arg1 delegates:(id)arg2 reqExtra:(id)arg3 ApNodeCheckResult:(id)arg4;
- (void)notifyApNodeInfoListCallBack_GetApNodeInfoList:(_Bool)arg1 delegates:(id)arg2 reqExtra:(id)arg3 ApNodeCheckResult:(id)arg4;
- (void)notifyError:(id)arg1;
- (void)onDelayReqTimer;
- (void)onNotifyMSFLoginSucc:(id)arg1;
- (id)parseAPNodeCheckResp:(char *)arg1 bufferLength:(int)arg2;
- (void)parseXmlAsync:(id)arg1;
- (_Bool)queryApNodeInfo:(id *)arg1 BSSID:(id)arg2 SSID:(id)arg3;
- (long long)queryApNodeState:(id)arg1 SSID:(id)arg2;
- (void)removeLbsNotification;
- (void)requestApNodeInfo:(id)arg1 delegate:(id)arg2;
- (void)requestApNodeInfo:(id)arg1 delegates:(id)arg2;
- (void)requestApNodeInfos:(id)arg1 delegate:(id)arg2;
- (_Bool)requestApNodeInfosInternal:(id)arg1 delegates:(id)arg2;
@property(retain, nonatomic) QQWifiLRUCache *wifiNodeLRUCache; // @synthesize wifiNodeLRUCache=_wifiNodeLRUCache;
- (void)shouldHandleDelayReqWifiNodeSet;
- (void)startDelayReqTimer:(unsigned long long)arg1;
- (void)startParseXml_lbs:(id)arg1;
- (void)updateWifiNodeSet:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

