//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQXMLMessageBaseView.h"

#import "QQChatImageMetaInfoObserver.h"

@class NSString, QQChatImageMetaInfo, UIActivityIndicatorView, UIImage;

@interface QQXMLMessagePictureView : QQXMLMessageBaseView <QQChatImageMetaInfoObserver>
{
    NSString *_coverUrl;
    UIImage *_coverImage;
    struct CGSize _maxSize;
    QQChatImageMetaInfo *_metaInfo;
    UIActivityIndicatorView *_indicatorView;
    id <NSObject> _scrollObserver;
}

- (void)addScrollObserver:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (_Bool)disableDrawWhenScroll;
- (void)drawRect:(struct CGRect)arg1;
- (id)getChatViewTable;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) struct CGSize maxSize; // @synthesize maxSize=_maxSize;
- (void)onImageDownloadResult:(id)arg1;
- (void)removeScrollObserver;
- (void)setCoverUrl:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

