//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IC2BFileTransferDelegate.h"
#import "QUIAlertViewDelegate.h"

@class NSString, NSTimer, UILabel;

@interface QQYPC2BFileUploadView : UIView <IC2BFileTransferDelegate, QUIAlertViewDelegate>
{
    unsigned long long _fileUploadTaskId;
    UIView *_blackBg;
    UILabel *_percentLabel;
    UILabel *_tipWordingLabel;
    UILabel *_cancelLabel;
    NSTimer *_timer;
    long long _tickCount;
    _Bool _responseTipWordingTap;
    double _lastProgress;
    id <QQYPC2BFileUploadViewDelegate> _delegate;
    NSString *_tipWording;
    NSString *_uploadFilePath;
}

- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dealloc;
@property(nonatomic) id <QQYPC2BFileUploadViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)directStartUpload;
- (void)handleMSFNetworkApnStateNotification:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 tipWording:(id)arg2 uploadFilePath:(id)arg3 delegate:(id)arg4;
- (_Bool)isNeedRemindUser;
- (void)layoutSubviews;
- (void)notifyUploadFailed:(long long)arg1 uploadDetail:(id)arg2 error:(id)arg3;
- (void)notifyUploadProcess:(long long)arg1 uploadDetail:(id)arg2 progress:(float)arg3;
- (void)notifyUploadSuccess:(long long)arg1 uploadDetail:(id)arg2;
- (void)notifyUploadTimeout:(long long)arg1 uploadDetail:(id)arg2;
- (void)onTapTipWordingLabel:(id)arg1;
- (void)onTimer:(id)arg1;
@property(copy, nonatomic) NSString *tipWording; // @synthesize tipWording=_tipWording;
@property(copy, nonatomic) NSString *uploadFilePath; // @synthesize uploadFilePath=_uploadFilePath;
- (void)startTimer;
- (void)startUpload;
- (void)stopTimer;
- (void)stopUpload;
- (void)updateProgress;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

