//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class QRBatchChapterCellData, UIButton, UILabel;

@interface QRBatchChapterCell : UITableViewCell
{
    _Bool _isDayMode;
    UILabel *_titleLabel;
    UILabel *_priceLabel;
    UIButton *_selectButton;
    UILabel *_alreadyDownloadLabel;
    QRBatchChapterCellData *_data;
    id <QRBatchChapterCellDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)buySuccessHandler:(id)arg1;
@property(retain, nonatomic) QRBatchChapterCellData *data; // @synthesize data=_data;
- (void)dealloc;
@property(nonatomic) id <QRBatchChapterCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)flushPayLabelInMainThread;
- (id)initWithDayMode:(_Bool)arg1 width:(double)arg2;
- (void)selectButtonClicked:(id)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;

@end

