//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QRChapterDownloaderDelegate.h"
#import "QRCoverDownloaderDelegate.h"

@class NSCache, NSMutableArray, NSString, OnlineTag;

@interface QROnlineReadingModule : NSObject <QRChapterDownloaderDelegate, QRCoverDownloaderDelegate>
{
    NSMutableArray *_onlineIps;
    NSCache *_cachedChapters;
    NSCache *_cachedOnlineChapterInfos;
    OnlineTag *_readingOnlineTag;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)Finished:(id)arg1 bookInfo:(id)arg2;
- (void)canResetChapterID;
- (void)chapterDownloadFailed:(id)arg1 request:(id)arg2 message:(id)arg3;
- (void)chapterDownloadFinished:(id)arg1 request:(id)arg2 response:(id)arg3;
- (id)chapterInfoListWithBookId:(id)arg1;
- (void)chapterRequest:(id)arg1 downloadFailedWithMessage:(id)arg2 withErrorType:(int)arg3 andErrorValue:(long long)arg4;
- (void)chapterRequest:(id)arg1 downloadSuccessWithResponse:(id)arg2;
- (void)chapterRequest:(id)arg1 downloadSuspendWithResponse:(id)arg2;
- (void)clearChapterCacheForBook:(id)arg1;
- (void)coverDownloadFailed:(id)arg1;
- (void)downloadChapter:(long long)arg1;
- (void)downloadChapter:(long long)arg1 andPay:(_Bool)arg2;
- (void)downloadCover:(id)arg1;
- (id)getOnlineReadFileSavePathByBookId:(id)arg1 bookName:(id)arg2 chapterId:(int)arg3;
- (id)init;
- (id)onlineChapterInfoListWithBookId:(id)arg1;
- (void)onlineReadingChapterNeedBuy:(id)arg1;
- (void)onlineReadingTotalBookNeedBuy:(id)arg1;
- (void)preLoading;
- (long long)readOnlineBookWithTag:(id)arg1;
- (long long)readOnlineBookWithTag:(id)arg1 andPay:(_Bool)arg2;
- (void)requestCoverImage:(id)arg1;
- (void)resetCharpterID;
- (void)updateShelfStatus:(int)arg1 BookInfo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

