//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

#import "QZPhotoThumbDelegate.h"

@class NSObject, NSString, QZDrawItemImage, QZFeedPhoto, UIImage;

@interface QZFeedPhotoView : UIImageView <QZPhotoThumbDelegate>
{
    UIImageView *_maskView;
    UIImageView *_videoIconImageView;
    _Bool _fade;
    _Bool _picDownLoadFinish;
    _Bool _maskImageRoundCorner_TopLeftRight;
    id <QZPhotoThumbViewDelegate> _delegate;
    QZFeedPhoto *_feedPhoto;
    UIImage *_maskImage;
    NSObject *_data;
    QZDrawItemImage *_drawItem;
}

- (void).cxx_destruct;
- (void)checkShowVideoIcon:(long long)arg1 canShowOnThumbView:(_Bool)arg2;
@property(retain, nonatomic) NSObject *data; // @synthesize data=_data;
- (void)dealloc;
@property(nonatomic) __weak id <QZPhotoThumbViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didFeedPhotoNeedLayout;
- (void)didPhotoThumbDownloadFailed:(id)arg1 userInfo:(id)arg2;
- (void)didPhotoThumbDownloadSuccess:(id)arg1 isCache:(_Bool)arg2 userInfo:(id)arg3;
- (void)didPhotoThumbNeedDisplay;
@property(retain, nonatomic) QZDrawItemImage *drawItem; // @synthesize drawItem=_drawItem;
@property(nonatomic) _Bool fade; // @synthesize fade=_fade;
@property(retain, nonatomic) QZFeedPhoto *feedPhoto; // @synthesize feedPhoto=_feedPhoto;
@property(nonatomic, getter=getPicDownLoadFinish) _Bool picDownLoadFinish; // @synthesize picDownLoadFinish=_picDownLoadFinish;
- (void)initPublicPhotoViewParam;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithParam:(id)arg1;
@property(retain, nonatomic) UIImage *maskImage; // @synthesize maskImage=_maskImage;
@property(nonatomic) _Bool maskImageRoundCorner_TopLeftRight; // @synthesize maskImageRoundCorner_TopLeftRight=_maskImageRoundCorner_TopLeftRight;
- (struct CGRect)pictureFullRect;
- (void)reset;
- (void)setFrame:(struct CGRect)arg1;
- (void)setImage:(id)arg1;
- (void)setPhotoUrl:(id)arg1;
- (void)smartUpdateOpaque;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

