//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QZVideoPlayerSlider;

@protocol QZFullScreenVideoControlToVideoState <NSObject>
- (double)getDuration;
- (void)openHD;
- (void)pause:(_Bool)arg1;
- (_Bool)play;
- (_Bool)playBySeek;
- (_Bool)rePlay;
- (void)seek:(double)arg1;
- (void)sliderBeginSeek;
- (void)sliderEndSeek;
- (void)sliderValueChanged:(QZVideoPlayerSlider *)arg1;
- (void)stop;
@end

