//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QZGDTCanvasBaseComponentInfo.h"

@class NSMutableDictionary;

@interface QZGDTCanvasButtonComponentInfo : QZGDTCanvasBaseComponentInfo
{
    NSMutableDictionary *_buttonComponentData;
}

- (void).cxx_destruct;
- (id)buttonComponentData;
- (double)componentHight;
- (double)componentPaddingBottom;
- (double)componentPaddingTop;
- (void)fillAdCanvasComponentData:(id)arg1 withBasicWidth:(double)arg2 basicFontSize:(long long)arg3;
- (void)fillBtnInfoWithBtn:(id)arg1;

@end

