//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QZGDTCanvasBaseComponentInfo : NSObject
{
    long long _type;
    _Bool _exposured;
}

- (_Bool)available;
- (double)componentHight;
- (double)componentPaddingBottom;
- (double)componentPaddingTop;
- (_Bool)exposured;
- (void)fillAdCanvasComponentData:(id)arg1 withBasicWidth:(double)arg2 basicFontSize:(long long)arg3;
- (void)setExposured:(_Bool)arg1;
- (long long)type;

@end

