//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSString;

@interface QZJFeedsMobileEventTagsReq : JceObjectV2
{
}


// Remaining properties
@property(nonatomic, getter=jce_count, setter=setJce_count:) int jcev2_p_0_o_count; // @dynamic jcev2_p_0_o_count;
@property(retain, nonatomic, getter=jce_content, setter=setJce_content:) NSString *jcev2_p_1_o_content; // @dynamic jcev2_p_1_o_content;
@property(nonatomic, getter=jce_recom_type, setter=setJce_recom_type:) int jcev2_p_2_o_recom_type; // @dynamic jcev2_p_2_o_recom_type;
@end

