//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class QZJNsQmallCoverAlbumThemeSkin;

@interface QZJNsQmallCoverPhotoAlbumQzmallDeco : JceObjectV2
{
    QZJNsQmallCoverAlbumThemeSkin *_jcev2_p_0_o_stAlbumSkin;
}

+ (id)jceType;
- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic, getter=jce_stAlbumSkin, setter=setJce_stAlbumSkin:) QZJNsQmallCoverAlbumThemeSkin *jcev2_p_0_o_stAlbumSkin; // @synthesize jcev2_p_0_o_stAlbumSkin=_jcev2_p_0_o_stAlbumSkin;

@end

