//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface QZLVQREventParamsModel : NSObject
{
    int _cameraID;
    int _voiceDataDelay;
    double _time_cost;
    long long _ret_code;
    long long _errType;
    NSString *_url;
    NSString *_client_ip;
    NSString *_server_ip;
    NSString *_appid;
    NSString *_refer;
    unsigned long long _chnlID;
    NSString *_errorDesc;
    NSString *_opPath;
    unsigned long long _memberNum;
    long long _setRoomType;
    double _playbackDuration;
    NSString *_videoPlayID;
    NSString *_descForStartPlay;
    NSString *_specialRoomID;
    NSDictionary *_busiParam;
    double _specialDuration;
    long long _specialRetCode;
    double _cpuRate;
    NSString *_downloadSpeed;
    NSString *_uploadRate;
}

- (void).cxx_destruct;
- (void)appendOpPath:(id)arg1;
@property(retain) NSString *appid; // @synthesize appid=_appid;
@property(retain) NSDictionary *busiParam; // @synthesize busiParam=_busiParam;
@property int cameraID; // @synthesize cameraID=_cameraID;
@property unsigned long long chnlID; // @synthesize chnlID=_chnlID;
@property(retain) NSString *client_ip; // @synthesize client_ip=_client_ip;
@property double cpuRate; // @synthesize cpuRate=_cpuRate;
@property(retain) NSString *descForStartPlay; // @synthesize descForStartPlay=_descForStartPlay;
@property(retain) NSString *downloadSpeed; // @synthesize downloadSpeed=_downloadSpeed;
@property long long errType; // @synthesize errType=_errType;
@property(retain) NSString *errorDesc; // @synthesize errorDesc=_errorDesc;
@property unsigned long long memberNum; // @synthesize memberNum=_memberNum;
@property(retain) NSString *opPath; // @synthesize opPath=_opPath;
@property double playbackDuration; // @synthesize playbackDuration=_playbackDuration;
@property(retain) NSString *refer; // @synthesize refer=_refer;
@property long long ret_code; // @synthesize ret_code=_ret_code;
@property(retain) NSString *server_ip; // @synthesize server_ip=_server_ip;
@property long long setRoomType; // @synthesize setRoomType=_setRoomType;
@property double specialDuration; // @synthesize specialDuration=_specialDuration;
@property long long specialRetCode; // @synthesize specialRetCode=_specialRetCode;
@property(retain) NSString *specialRoomID; // @synthesize specialRoomID=_specialRoomID;
@property double time_cost; // @synthesize time_cost=_time_cost;
@property(retain) NSString *uploadRate; // @synthesize uploadRate=_uploadRate;
@property(retain) NSString *url; // @synthesize url=_url;
@property(retain) NSString *videoPlayID; // @synthesize videoPlayID=_videoPlayID;
@property int voiceDataDelay; // @synthesize voiceDataDelay=_voiceDataDelay;

@end

