//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface QzoneDataCacheHelper : NSObject
{
    NSString *_dataBasePath;
    NSString *_resourcesBasePath;
    id <QzoneDataCacheStrategyProtocol> _strategy;
    long long _currentUin;
}

- (void).cxx_destruct;
- (void)clearDataPath;
- (void)clearResourcePath;
@property(readonly, nonatomic) NSString *commonDataFullPath;
@property(readonly, nonatomic) NSString *commonResourecesFullPath;
- (id)createDictionary:(id)arg1;
@property(nonatomic) long long currentUin; // @synthesize currentUin=_currentUin;
- (id)initWithCacheStrategy:(id)arg1;
@property(nonatomic) __weak id <QzoneDataCacheStrategyProtocol> strategy; // @synthesize strategy=_strategy;
@property(readonly, nonatomic) NSString *userDataFullPath;
@property(readonly, nonatomic) NSString *userResourcesFullPath;

@end

