//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QzoneFeedRenderEngine : NSObject
{
}

+ (void)cacheLayoutInfo:(id)arg1 withImage:(id)arg2;
+ (id)cachedImageList;
+ (id)cachedImageWithLayoutInfo:(id)arg1;
+ (id)cachedKeyArray;
+ (void)checkMemoryForDeleteImages;
+ (long long)computeCacheImageBytes;
+ (long long)getDeviceLevel;
+ (void)memoryLow:(id)arg1;
+ (void)releaseMem;
+ (id)renderQueue;
+ (id)sharedInstance;
- (void)preRenderWithFeedModel:(id)arg1;
- (id)renderImageWithLayoutInfo:(id)arg1 inRect:(struct CGRect)arg2 async:(_Bool)arg3 useCache:(_Bool)arg4 complition:(CDUnknownBlockType)arg5;
- (id)renderLayoutInfo:(id)arg1 inRect:(struct CGRect)arg2;

@end

