//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDate, NSString;

@interface QzoneDataCacheNode : NSObject <NSCoding>
{
    _Bool _isResource;
    _Bool _needEncrypt;
    _Bool _alreadyWriteDisk;
    id <NSCoding> _data;
    NSString *_key;
    NSDate *_expiredDate;
    long long _accessTimes;
    long long _uin;
}

+ (id)cacheNodeWithKey:(id)arg1 isResource:(_Bool)arg2 uin:(long long)arg3 helper:(id)arg4;
+ (id)localPathWithKey:(id)arg1 isResource:(_Bool)arg2 uin:(long long)arg3 helper:(id)arg4;
- (void).cxx_destruct;
@property(nonatomic) long long accessTimes; // @synthesize accessTimes=_accessTimes;
@property(nonatomic) _Bool alreadyWriteDisk; // @synthesize alreadyWriteDisk=_alreadyWriteDisk;
@property(retain, nonatomic) id <NSCoding> data; // @synthesize data=_data;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSDate *expiredDate; // @synthesize expiredDate=_expiredDate;
- (id)initWithCoder:(id)arg1;
- (id)initWithData:(id)arg1 key:(id)arg2 isResource:(_Bool)arg3 uin:(long long)arg4 needEncrypt:(_Bool)arg5 expiredDate:(id)arg6;
- (_Bool)isExpiredNode;
@property(nonatomic) _Bool isResource; // @synthesize isResource=_isResource;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (id)localFullPath:(id)arg1;
@property(nonatomic) _Bool needEncrypt; // @synthesize needEncrypt=_needEncrypt;
@property(nonatomic) long long uin; // @synthesize uin=_uin;

@end

