//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QzoneLibUtil : NSObject
{
}

+ (id)ParagraphStyle;
+ (void)addJobToSendBoxWithPath:(id)arg1;
+ (id)cStringWithFirstLevel:(const char *)arg1 andSecondLevel:(const char *)arg2;
+ (void)cacheData:(id)arg1 forKey:(id)arg2 isResource:(_Bool)arg3 forCurrentUin:(_Bool)arg4;
+ (id)colorFromString:(id)arg1;
+ (id)convertTextAsReadable:(id)arg1;
+ (void)creatPath:(id)arg1;
+ (id)createVideoBreakImgUrl:(id)arg1 breakTime:(double)arg2;
+ (id)decodedImageWithCGImageRef:(struct CGImage *)arg1 viewSize:(struct CGSize)arg2 scale:(double)arg3;
+ (_Bool)doesDeviceCanAutoPlayFeedCommentGif;
+ (_Bool)doesDeviceCanAutoPlayFeedMultiGif;
+ (_Bool)doesDeviceCanAutoPlayGif:(const char *)arg1;
+ (_Bool)doesDeviceCanAutoPlayGifInFeed;
+ (id)emotionLabelToString:(id)arg1;
+ (id)emotionURL:(id)arg1;
+ (id)filterSecurityInfoOfUrl:(id)arg1;
+ (struct CGRect)fixNanRect:(struct CGRect)arg1;
+ (id)fontWithType:(long long)arg1;
+ (id)formatDayToYMD:(id)arg1 simple:(_Bool)arg2;
+ (id)formatToYearAndMonth:(id)arg1;
+ (id)formattedNumber:(long long)arg1;
+ (id)getCurrentNickname;
+ (double)getCurrentTimeInterval;
+ (id)getDateComponentWithDate:(id)arg1;
+ (long long)getDateMonth:(id)arg1;
+ (long long)getDateYear:(id)arg1;
+ (id)getDeviceName;
+ (int)getDeviceType;
+ (id)getTimeStr:(double)arg1 absolute:(_Bool)arg2;
+ (void)getUpdateFeedWithFeedList:(id)arg1 reqType:(int)arg2;
+ (id)getUserPath;
+ (id)getyyyyMMddHHmmssStringFromDate:(id)arg1;
+ (_Bool)hasDataFor:(id)arg1 isResource:(_Bool)arg2 forCurrentUin:(_Bool)arg3;
+ (_Bool)hasPassiveMessage;
+ (id)imageWithData:(id)arg1 index:(int)arg2 viewSize:(struct CGSize)arg3;
+ (_Bool)isLegalPrefix:(id)arg1;
+ (_Bool)isQzoneDeviceJailBroken;
+ (id)loadDataForKey:(id)arg1 isResource:(_Bool)arg2 forCurrentUin:(_Bool)arg3;
+ (void)modelToJce:(id)arg1 andWriteToFile:(id)arg2;
+ (void)postBannerPrompt:(id)arg1;
+ (id)privacyTypeDescription:(long long)arg1;
+ (void)removeDataFor:(id)arg1 isResource:(_Bool)arg2 forCurrentUin:(_Bool)arg3;
+ (id)stringWithFirstLevel:(id)arg1 andSecondLevel:(id)arg2;
+ (id)voiceOverTextStringWithEmotion:(id)arg1;

@end

