//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QZIntelligenceBannerBaseView.h"

@class CALayer, NSMutableArray, UIImageView, UILabel, UIView;

@interface QZPassiveBannerView : QZIntelligenceBannerBaseView
{
    UILabel *_desLabel;
    NSMutableArray *_avatarViewArray;
    UIView *_avatarViews;
    UIImageView *_backgroundView;
    UIImageView *_arrowView;
    CALayer *_backgroundAnimLayer;
}

+ (id)passiveBannerInfoKey;
- (void)reportClick;

@end

