//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class CAGradientLayer, CALayer, NSArray, NSDictionary, NSMutableArray, NSString, QZDrawItemInteractionRect, QZDrawItemTextWrapper, QzoneCommSparkleWord, UIColor, UIFont, UIImage;

@interface QZRichTextLabel : UIControl
{
    NSArray *_colorChangeColorList;
    double _colorChangeDuration;
    double _colorChangeRepeatCount;
    _Bool _isNeedLayout;
    QZDrawItemTextWrapper *_richText;
    UIImage *_animationMaskImage;
    int _xo;
    NSMutableArray *_emotionImageViewArray;
    _Bool _redrawAfterFontLoaded;
    _Bool _userInteractionEnabledInPlainText;
    int _textVerticalAlignment;
    int _textHorizontalAlignment;
    long long _normalTextOnly;
    QZDrawItemInteractionRect *_backgroundArea;
    id <QZFeedCellDelegate> _feedDelegate;
    id <QZRichTextLabelDelegate> _touchDelegate;
    QzoneCommSparkleWord *_sparkleword;
    unsigned long long _touchEventType;
    NSDictionary *_touchParam;
    CALayer *_colorChangeLayer;
    CAGradientLayer *_mGradientLayer;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) QZDrawItemInteractionRect *backgroundArea; // @synthesize backgroundArea=_backgroundArea;
@property(readonly, copy, nonatomic) NSArray *colorChangeColorList; // @synthesize colorChangeColorList=_colorChangeColorList;
@property(readonly, nonatomic) double colorChangeDuration; // @synthesize colorChangeDuration=_colorChangeDuration;
@property(retain, nonatomic) CALayer *colorChangeLayer; // @synthesize colorChangeLayer=_colorChangeLayer;
@property(readonly, nonatomic) double colorChangeRepeatCount; // @synthesize colorChangeRepeatCount=_colorChangeRepeatCount;
- (id)createAnimationMaskImage;
- (void)createCornerBackgroundWithColor:(id)arg1 needCorner:(_Bool)arg2;
- (void)dealloc;
- (void)destroyAnimation;
- (void)drawAnimation;
- (void)drawCAGradientLayer;
- (void)drawEmotion;
- (void)drawRect:(struct CGRect)arg1;
- (void)etFontChanged:(id)arg1;
@property(readonly, nonatomic) long long etFontId;
@property(readonly, nonatomic) long long etFontType;
@property(readonly, copy, nonatomic) NSString *etFontUrl;
- (void)eventTouchCancel:(id)arg1 forEvent:(id)arg2;
- (void)eventTouchDown:(id)arg1 forEvent:(id)arg2;
- (void)eventTouchUp:(id)arg1 forEvent:(id)arg2;
@property(nonatomic) __weak id <QZFeedCellDelegate> feedDelegate; // @synthesize feedDelegate=_feedDelegate;
@property(readonly, nonatomic) UIFont *font; // @dynamic font;
- (_Bool)hasAnimation;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layerWillDraw:(id)arg1;
@property(readonly, nonatomic) double lineSpace; // @dynamic lineSpace;
@property(retain, nonatomic) CAGradientLayer *mGradientLayer; // @synthesize mGradientLayer=_mGradientLayer;
@property(nonatomic) long long normalTextOnly; // @synthesize normalTextOnly=_normalTextOnly;
@property(readonly, nonatomic) long long numberOfLines; // @dynamic numberOfLines;
- (double)realWidth;
@property(nonatomic) _Bool redrawAfterFontLoaded; // @synthesize redrawAfterFontLoaded=_redrawAfterFontLoaded;
- (void)removeSubLayer;
- (void)reset;
- (_Bool)resetAnimationWhenHasColorFont;
- (void)setBackgroundColor:(id)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setColorChangeAnimation:(id)arg1 colorChangeDuration:(double)arg2 colorChangeRepeatCount:(double)arg3;
- (void)setFrame:(struct CGRect)arg1;
- (void)setRichText:(id)arg1 andAnimationMaskImage:(id)arg2;
@property(retain, nonatomic) QzoneCommSparkleWord *sparkleword; // @synthesize sparkleword=_sparkleword;
- (void)setText:(id)arg1 font:(id)arg2 textColor:(id)arg3 numberOfLines:(long long)arg4 etFontId:(long long)arg5 etFontUrl:(id)arg6 etFontType:(long long)arg7 lineSpace:(double)arg8 useParagraph:(_Bool)arg9 truncationNotShowMore:(_Bool)arg10;
- (void)setText:(id)arg1 font:(id)arg2 textColor:(id)arg3 numberOfLines:(long long)arg4 etFontId:(long long)arg5 etFontUrl:(id)arg6 etFontType:(long long)arg7 lineSpace:(double)arg8 useParagraph:(_Bool)arg9 truncationNotShowMore:(_Bool)arg10 backgroundImage:(id)arg11;
- (void)setText:(id)arg1 maxLine:(long long)arg2 font:(id)arg3 color:(id)arg4;
- (void)setText:(id)arg1 maxLine:(long long)arg2 font:(id)arg3 color:(id)arg4 backgroundImage:(id)arg5;
@property(nonatomic) int textHorizontalAlignment; // @synthesize textHorizontalAlignment=_textHorizontalAlignment;
@property(nonatomic) int textVerticalAlignment; // @synthesize textVerticalAlignment=_textVerticalAlignment;
@property(nonatomic) __weak id <QZRichTextLabelDelegate> touchDelegate; // @synthesize touchDelegate=_touchDelegate;
@property(nonatomic) unsigned long long touchEventType; // @synthesize touchEventType=_touchEventType;
@property(retain, nonatomic) NSDictionary *touchParam; // @synthesize touchParam=_touchParam;
@property(nonatomic) _Bool userInteractionEnabledInPlainText; // @synthesize userInteractionEnabledInPlainText=_userInteractionEnabledInPlainText;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)startAnimation;
- (void)stopAnimation;
@property(readonly, copy, nonatomic) NSString *text; // @dynamic text;
@property(readonly, nonatomic) UIColor *textColor; // @dynamic textColor;
- (double)totalHeight;
@property(readonly, nonatomic) _Bool truncationNotShowMore; // @dynamic truncationNotShowMore;
@property(readonly, nonatomic) _Bool useParagraph; // @dynamic useParagraph;

// Remaining properties
@property(nonatomic) _Bool isNeedLayout; // @dynamic isNeedLayout;
@property(readonly, nonatomic) QZDrawItemTextWrapper *richText; // @dynamic richText;

@end

