//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSURL, UIColor;

@interface QZTextLinkHelper : NSObject
{
    NSMutableDictionary *linkAttributes_;
    struct _NSRange _range;
}

+ (id)linkHelperWithAttributes:(id)arg1;
- (void).cxx_destruct;
- (id)description;
- (id)generateCoreTextAttributes;
- (id)getAttribute:(id)arg1;
- (id)initWithAttributes:(id)arg1;
@property(retain, nonatomic) id linkAction;
@property(readonly, nonatomic) __weak NSDictionary *linkAttributes;
@property(retain, nonatomic) UIColor *linkTextColor;
@property(nonatomic) long long linkType;
@property(retain, nonatomic) NSURL *linkUrl;
@property(retain, nonatomic) UIColor *linkedBgColor;
@property(retain, nonatomic) UIColor *linkedTextColor;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;
- (void)setAttribute:(id)arg1 value:(id)arg2;

@end

