//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray, NSTimer, UIColor, UIImageView;

@interface QZVideoProgressBar : UIView
{
    UIColor *_foregroundColor;
    UIColor *_previewBgColor;
    UIColor *_fixedMarkerColor;
    UIColor *_markerColor;
    UIColor *_borderColor;
    _Bool _needsBottomBorder;
    _Bool _needsCursor;
    double _referenceValue;
    double _previewReferenceValue;
    double _currentValue;
    UIColor *_lastSegmentColor;
    double _lastSegmentSize;
    _Bool _previewMode;
    double _foregroundMargin;
    int _xo;
    struct {
        unsigned int topBorder:1;
        unsigned int bottomBorder:1;
    } _extraStyleFlags;
    NSArray *_fixedMarks;
    UIImageView *_cursor;
    NSTimer *_cursorAnimationTimer;
    double _currentProgress;
    NSMutableArray *_marks;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double currentProgress; // @synthesize currentProgress=_currentProgress;
- (void)dealloc;
- (void)doCursorAnimation:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) NSMutableArray *marks; // @synthesize marks=_marks;
@property(nonatomic) _Bool needsBottomBorder; // @dynamic needsBottomBorder;
- (void)removeFromSuperview;
@property(nonatomic) double currentValue; // @dynamic currentValue;
@property(retain, nonatomic) UIColor *fixedMarkerColor; // @dynamic fixedMarkerColor;
@property(retain, nonatomic) UIColor *foregroundColor; // @dynamic foregroundColor;
@property(nonatomic) double lastSegmentSize; // @dynamic lastSegmentSize;
- (void)setMark;
@property(retain, nonatomic) UIColor *markerColor; // @dynamic markerColor;
@property(nonatomic) _Bool needsCursor; // @dynamic needsCursor;
@property(nonatomic) _Bool previewMode; // @dynamic previewMode;
@property(nonatomic) double referenceValue; // @dynamic referenceValue;

// Remaining properties
@property(retain, nonatomic) UIColor *borderColor; // @dynamic borderColor;
@property(nonatomic) double foregroundMargin; // @dynamic foregroundMargin;
@property(retain, nonatomic) UIColor *lastSegmentColor; // @dynamic lastSegmentColor;
@property(nonatomic) double previewReferenceValue; // @dynamic previewReferenceValue;

@end

