//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ReadInJoyDataUtil : NSObject
{
}

+ (id)constructStructMsgByQzoneVideoModel:(id)arg1;
+ (id)constructStructMsgByVideoModel:(id)arg1;
+ (id)constructStructMsgByVideoModel:(id)arg1 videoView:(id)arg2;
+ (_Bool)feedsRedReminder;
+ (void)fillTitleBriefOfMsgWrigter:(id)arg1 withTitle:(id)arg2 busiType:(int)arg3;
+ (id)formatReadInJoyPublishTime:(unsigned long long)arg1 dateFormat:(id)arg2;
+ (id)formatReadInJoyVideoTime:(double)arg1;
+ (void)getContentOfMsgWriter:(id)arg1 withVideoModel:(id)arg2 isVideoTypeThird:(_Bool)arg3;
+ (id)getGuideInfo;
+ (void)getLocalInterestLabelId:(id)arg1;
+ (id)getNewGuideWording;
+ (id)getReadInJoyFormatTimeNew:(long long)arg1;
+ (id)getReadInJoyFormatTimeNew:(long long)arg1 withDetailTime:(_Bool)arg2;
+ (id)getReadInJoyFromSearchRefreshTime;
+ (id)getReadInJoyFromSubscribeRefreshTime;
+ (id)getReadInJoyVideoChannelRefreshTime;
+ (id)getRefreshHistory;
+ (id)getRefreshTipShownTime;
+ (_Bool)haveNewInDynamic;
+ (_Bool)haveNewInReadInJoy;
+ (_Bool)haveReadInJoyChannel;
+ (_Bool)isLocalSelectedLabelId:(id)arg1;
+ (_Bool)isRecommandChaneMayChanged;
+ (long long)makeVideoStartPositon:(long long)arg1 duration:(long long)arg2;
+ (_Bool)mergeFeeds;
+ (void)removeGuideInfo;
+ (void)removeGuideWordingStorage;
+ (void)saveLastAlertViewShowTime:(double)arg1;
+ (void)saveLastCloseSuggestTime;
+ (void)saveReadInJoyFromSearchRefreshTime:(id)arg1;
+ (void)saveReadInJoyFromSuggestRefreshTime:(double)arg1;
+ (void)saveReadInJoyVideoChannelRefreshTime:(double)arg1;
+ (void)saveRefreshHistory:(id)arg1;
+ (void)setGuideInfo:(id)arg1;
+ (void)setInterestTipsShowed;
+ (void)setNewGuideWording:(id)arg1;
+ (void)setNewInDynamic:(_Bool)arg1;
+ (void)setNewInReadInJoy:(_Bool)arg1;
+ (void)setNewReadInJoyGuideShowed;
+ (void)setRecommandChaneMayChanged:(_Bool)arg1;
+ (void)setRrefreshTipShownTime:(double)arg1;
+ (_Bool)shareToNews;
+ (_Bool)shouldShowAlertView;
+ (_Bool)shouldShowSuggestSubscribe;
+ (_Bool)showReadInJoyInSubs;
+ (_Bool)showedInterestTips;
+ (_Bool)showedNewReadInJoyGuide;
+ (_Bool)syncToQZone;

@end

