//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEngineDispatchDelegate.h"

@class NSString, RichStateHistoryReq;

@interface RichStateServiceImpl : NSObject <IEngineDispatchDelegate>
{
    id <RichStateServiceImplCallback> _callback;
    RichStateHistoryReq *_historyReq;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <RichStateServiceImplCallback> callback; // @synthesize callback=_callback;
- (void)dealloc;
- (void)didRecievedMsg:(CDStruct_7895f40e)arg1;
- (void)getMyRichSigReqBuffer:(id)arg1 bufStart:(char **)arg2 bufEnd:(char **)arg3;
@property(retain, nonatomic) RichStateHistoryReq *historyReq; // @synthesize historyReq=_historyReq;
- (id)init;
- (void)notifyError:(id)arg1;
- (int)requestDeleteRichHistory:(int)arg1 withArray:(id)arg2;
- (int)requestDeleteRichSignatures;
- (int)requestGetHotRichState;
- (int)requestGetRichSignatures:(id)arg1;
- (int)requestRichStateSyncShuoshuo:(unsigned long long)arg1 write:(_Bool)arg2 sync:(_Bool)arg3;
- (int)requestSetRichSignatures:(id)arg1 forUin:(id)arg2 sourceID:(int)arg3;
- (void)requestSuccessForAuthSetRichStateWithMsg:(CDStruct_7895f40e)arg1;
- (int)requestgetRichHistoryList:(unsigned long long)arg1 startTime:(int)arg2 endTime:(int)arg3 pageNum:(int)arg4 friendType:(int)arg5 isFirstTime:(_Bool)arg6;
- (void)resetHistoryReq;
- (void)respDeleteRichHistory:(char *)arg1 dataLen:(int)arg2 seq:(int)arg3;
- (void)respDeleteRichSig:(char *)arg1 dataLen:(int)arg2 seq:(int)arg3;
- (void)respGetHotRichState:(char *)arg1 dataLen:(int)arg2 seq:(int)arg3;
- (void)respGetRichSig:(char *)arg1 dataLen:(int)arg2 seq:(int)arg3;
- (void)respRichHistory:(char *)arg1 dataLen:(int)arg2 seq:(int)arg3;
- (void)respRichStateSyncShuoshuo:(char *)arg1 dataLen:(int)arg2 seq:(int)arg3;
- (void)respSetRichSig:(basic_string_075b6133)arg1 seq:(int)arg2;
- (void)resqLevelAcceleration:(char *)arg1 dataLength:(int)arg2 seq:(int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

