//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SDCGICommonHead : NSObject
{
    unsigned int _pid;
    unsigned int _seq;
    unsigned int _flag;
    unsigned long long _din;
    unsigned long long _tinyid;
    NSString *_sn;
}

- (void).cxx_destruct;
@property unsigned long long din; // @synthesize din=_din;
@property unsigned int flag; // @synthesize flag=_flag;
@property unsigned int pid; // @synthesize pid=_pid;
@property unsigned int seq; // @synthesize seq=_seq;
@property(copy, nonatomic) NSString *sn; // @synthesize sn=_sn;
@property unsigned long long tinyid; // @synthesize tinyid=_tinyid;
@property(readonly) unsigned int uin;
@property(readonly, nonatomic) NSString *uinA2;
@property(readonly, nonatomic) NSString *version;

@end

