//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SmobaGameInfoModel, UILabel;

@interface SmobaGameInfoView : UIView
{
    SmobaGameInfoModel *_model;
    UILabel *_titleLabel;
    UILabel *_countLabel;
    UILabel *_unitsLabel;
    CDUnknownBlockType _designSizeBlock;
    CDUnknownBlockType _colorBlock;
}

- (void).cxx_destruct;
- (void)_loadCountLabel;
- (void)_loadTitleLabel;
- (void)_loadUnitsLabel;
@property(copy, nonatomic) CDUnknownBlockType colorBlock; // @synthesize colorBlock=_colorBlock;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(copy, nonatomic) CDUnknownBlockType designSizeBlock; // @synthesize designSizeBlock=_designSizeBlock;
- (id)init;
- (void)layoutSubviews;
@property(retain, nonatomic) SmobaGameInfoModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *unitsLabel; // @synthesize unitsLabel=_unitsLabel;

@end

