//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, SPDYOrigin, SPDYOriginEndpoint;

@interface SPDYOriginEndpointManager : NSObject
{
    NSMutableArray *_endpointList;
    long long _endpointIndex;
    struct __CFRunLoopSource *_autoConfigRunLoopSource;
    NSMutableArray *_autoConfigRunLoopModes;
    CDUnknownBlockType _resolveCallback;
    _Bool _authRequired;
    int _proxyStatus;
    SPDYOrigin *_origin;
}

- (void).cxx_destruct;
- (void)_addFallback;
- (void)_addRunLoopSource;
- (void)_finalizeResolveEndpoints;
- (id)_getOriginUrlForProxy;
- (void)_handleExecuteCallback:(id)arg1 error:(id)arg2;
- (void)_proxyAddSupportedFrom:(id)arg1 executeAutoConfig:(_Bool)arg2;
- (void)_proxyExecuteAutoConfigURL:(id)arg1;
- (id)_proxyGetListFromSettings:(id)arg1;
- (id)_proxyGetSystemSettings;
- (void)_removeRunLoopSource;
@property(nonatomic) _Bool authRequired; // @synthesize authRequired=_authRequired;
- (void)dealloc;
@property(readonly, nonatomic) SPDYOriginEndpoint *endpoint;
- (id)initWithOrigin:(id)arg1;
- (id)moveToNextEndpoint;
@property(readonly, nonatomic) SPDYOrigin *origin; // @synthesize origin=_origin;
@property(readonly, nonatomic) int proxyStatus; // @synthesize proxyStatus=_proxyStatus;
@property(readonly, nonatomic) unsigned long long remaining;
- (void)resolveEndpointsWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

