//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SpriteGameBtnModel : NSObject
{
    _Bool _disableGameMsg;
    int _btnId;
    int _type;
    NSString *_normalBgUrl;
    NSString *_playingBgUrl;
}

@property(nonatomic) int btnId; // @synthesize btnId=_btnId;
- (void)dealloc;
@property(nonatomic) _Bool disableGameMsg; // @synthesize disableGameMsg=_disableGameMsg;
- (id)initGameBtnWithDic:(id)arg1;
@property(retain, nonatomic) NSString *normalBgUrl; // @synthesize normalBgUrl=_normalBgUrl;
@property(retain, nonatomic) NSString *playingBgUrl; // @synthesize playingBgUrl=_playingBgUrl;
@property(nonatomic) int type; // @synthesize type=_type;

@end

