//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SpritePushItemDrawerInfo.h"

@class NSString;

@interface SpriteS2CDrawerInfoModel : SpritePushItemDrawerInfo
{
    int _messageID;
    NSString *_wording;
}

- (void)dealloc;
- (id)initWithDict:(id)arg1;
@property(nonatomic) int messageID; // @synthesize messageID=_messageID;
@property(retain, nonatomic) NSString *wording; // @synthesize wording=_wording;
- (id)toDictionary;

@end

