//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray;

@interface SpriteBusinessRedDotModel : NSObject <NSCoding>
{
    _Bool _redPointShowed;
    unsigned long long _busId;
    NSArray *_dotList;
}

@property(nonatomic) unsigned long long busId; // @synthesize busId=_busId;
- (void)dealloc;
@property(retain, nonatomic) NSArray *dotList; // @synthesize dotList=_dotList;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
@property(nonatomic) _Bool redPointShowed; // @synthesize redPointShowed=_redPointShowed;

@end

