//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface SpriteActionSet : NSObject <NSCopying>
{
    _Bool _isFavorManagerEntry;
    int _actionId;
    int _textType;
    unsigned int _diySoundId;
    unsigned int _diyPlayOriginalAudio;
    NSString *_text;
    double _diySoundBeginTs;
    long long _seq;
}

@property(nonatomic) int actionId; // @synthesize actionId=_actionId;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
@property(nonatomic) unsigned int diyPlayOriginalAudio; // @synthesize diyPlayOriginalAudio=_diyPlayOriginalAudio;
@property(nonatomic) double diySoundBeginTs; // @synthesize diySoundBeginTs=_diySoundBeginTs;
@property(nonatomic) unsigned int diySoundId; // @synthesize diySoundId=_diySoundId;
- (id)getFavDictionary;
- (id)initFavWithDictionay:(id)arg1;
- (id)initWithDict:(id)arg1;
@property(nonatomic) _Bool isFavorManagerEntry; // @synthesize isFavorManagerEntry=_isFavorManagerEntry;
@property(nonatomic) long long seq; // @synthesize seq=_seq;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) int textType; // @synthesize textType=_textType;

@end

