//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IAsynDownloadImageObserver.h"

@class NSString, SpritePackageModel, UIImageView;

@interface SpritePanelTabItem : UIView <IAsynDownloadImageObserver>
{
    UIImageView *_imageView;
    SpritePackageModel *_packageModel;
    int _state;
    UIImageView *_redPoint;
    long long timeVer;
    id <SpritePanelTabItemDelegate> _delegate;
}

+ (id)keyForHasClickedRedDotWithPkgId:(int)arg1 timeVer:(long long)arg2;
- (void)checkNeedShowRedDot;
- (void)dataReportForHidingRedDot;
- (void)dataReportForShowingRedDot;
- (void)dealloc;
@property(nonatomic) id <SpritePanelTabItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void)downloadImageFinished:(id)arg1;
- (id)entranceStrForDataReport;
- (void)hiddenRed;
- (id)initWithFrame:(struct CGRect)arg1 PackageModel:(id)arg2;
- (_Bool)isRedShow;
@property(readonly, nonatomic) SpritePackageModel *packageModel; // @synthesize packageModel=_packageModel;
- (id)resStrForDataReport;
- (void)setState:(int)arg1;
- (void)showRed;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

