//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAudioPlayer, SpriteActionModle, SpriteInstance;

@protocol SpriteMultiImgDelegate <NSObject>

@optional
- (void)onSpriteInstanceBubbleClicked:(SpriteInstance *)arg1;
- (void)onSpriteInstanceClicked:(SpriteInstance *)arg1;
- (void)onSpriteInstanceLongPressed:(SpriteInstance *)arg1;
- (void)spriteAudioPlayerDidFinishPlaying:(AVAudioPlayer *)arg1 successfully:(_Bool)arg2;
- (void)spriteMultiImgView:(SpriteInstance *)arg1 actionDidFinish:(CDStruct_6778d593)arg2 isSucc:(_Bool)arg3;
- (void)spriteMultiImgView:(SpriteInstance *)arg1 actionDidFinishDownload:(SpriteActionModle *)arg2 isSucc:(_Bool)arg3;
- (void)spriteMultiImgView:(SpriteInstance *)arg1 actionDidStart:(CDStruct_6778d593)arg2 isSucc:(_Bool)arg3;
- (void)spriteMultiImgView:(SpriteInstance *)arg1 bubbleDidFinishDownload:(long long)arg2 isSucc:(_Bool)arg3;
- (void)spriteMultiImgView:(SpriteInstance *)arg1 roleAndDressDidFinishLoad:(_Bool)arg2 isDressSucc:(_Bool)arg3;
@end

