//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQViewController.h"

#import "QQAppIconImageDelegate.h"
#import "RequestDelegate.h"
#import "SSoUserInfoViewDelegate.h"
#import "SimpleAlertViewDelegate.h"
#import "SimpleHeadMgrDelegate.h"
#import "SimpleLoginDelegate.h"

@class AuthorizationRequest, NSArray, NSData, NSDate, NSDictionary, NSString, SSoUserInfoView, UIActivityIndicatorView, UIButton, UIImage, UILabel, UIScrollView, UITableView;

@interface SSoAuthorizationViewController : QQViewController <SimpleHeadMgrDelegate, QQAppIconImageDelegate, RequestDelegate, SimpleLoginDelegate, SSoUserInfoViewDelegate, SimpleAlertViewDelegate>
{
    UIButton *_accountChangeBtn;
    UIButton *_confirmBtn;
    UILabel *_listLabel;
    SSoUserInfoView *_userInfoView;
    long long _uin;
    NSString *_nickName;
    NSData *_sKEY;
    NSString *_appName;
    NSArray *_authInfoList;
    AuthorizationRequest *_authorizationRequest;
    UITableView *_authorizationListTableView;
    NSDictionary *_loginInfoForThirdPart;
    UIActivityIndicatorView *_indicatorView;
    UIScrollView *_scrollView;
    UIImage *_head;
    NSData *_a2;
    NSData *_d2;
    unsigned long long _d2Key;
    NSDictionary *_key;
    UILabel *_loadingLabel;
    long long _redirectTime;
    _Bool _isWebQLoginClicked;
    _Bool _isGetAuthInfoList;
    _Bool _isAccountBtnTouch;
    _Bool _isAutoLogin;
    _Bool _loginA2D2;
    _Bool _isGetAuthorizationInfo;
    _Bool _isNeedChangeAccount;
    AuthorizationRequest *_auhtotizationIconRequest;
    NSDate *_timeCount;
    NSDate *_getIconTimeCount;
    long long _step;
    NSDate *_startAuthTime;
}

- (void).cxx_destruct;
- (void)GetAppIconDelegate:(id)arg1 errorcode:(id)arg2 dicInfo:(id)arg3 errorMsg:(id)arg4;
- (void)GetAuthorizationInfoDelegate:(id)arg1 dicinfo:(id)arg2 data:(id)arg3 errorMsg:(id)arg4;
- (void)RequestFailed:(id)arg1;
- (void)RequestSvrErrorCode:(id)arg1;
- (void)RequestSystemNetError:(id)arg1;
- (void)SetAuthorizationDelegate:(id)arg1 dicinfo:(id)arg2 errorMsg:(id)arg3;
- (void)accountChangeBtnClick:(id)arg1;
- (void)addChangeAccountButton;
- (void)addConfirmBottonView;
- (void)buttonClick:(id)arg1 atIndex:(int)arg2;
- (void)confirmBtnLoading;
- (void)confirmLogin:(id)arg1;
- (void)createUserInfoView:(id)arg1;
- (void)dealloc;
- (void)doLogin;
- (void)doLoginWithPwd;
- (void)downLoadImageFail:(id)arg1;
- (void)downloadImageFinished:(id)arg1;
- (void)enable:(_Bool)arg1 text:(id)arg2;
- (int)endCountGetIconTime;
- (int)endCountTime;
- (void)getAppAdInfo:(id)arg1;
- (void)getAppInfo;
- (void)getAppInfoForQuickLogin;
- (id)getAppInfo_AppIconUrl;
- (id)getAppInfo_AppName;
- (void)getHeadDelegate:(id)arg1;
@property(retain, nonatomic) NSDate *getIconTimeCount; // @synthesize getIconTimeCount=_getIconTimeCount;
- (void)getImageWithUrl:(id)arg1 downloadCompletion:(CDUnknownBlockType)arg2;
- (void)getSKeyAfterCheckSKeyFail;
- (_Bool)gotoAuthorizationWithUin:(unsigned int)arg1 andNickName:(id)arg2 andSkey:(id)arg3;
- (void)handleAppearanceReloadNotification:(id)arg1;
- (id)init;
- (void)leftButtonClick:(id)arg1;
- (void)loginFailed:(int)arg1 withMsg:(id)arg2 loginType:(int)arg3;
- (void)loginSucceed:(id)arg1 Uin:(unsigned int)arg2 Nickname:(id)arg3 loginType:(int)arg4;
- (void)onChangeAccountBtnTouch;
- (void)qRcodeLoginFailed:(id)arg1;
- (void)qRcodeLoginSucceed;
- (void)quickLoginEnd;
- (void)quickLoginFailed:(id)arg1;
- (void)reportBeforeAuthTotalTime;
- (void)reportGetIconInfo:(int)arg1 serverCode:(int)arg2;
- (void)reportNoNetWork:(id)arg1;
- (void)reportSSoInfo:(int)arg1 result:(int)arg2 serverCode:(int)arg3;
- (void)reportWtloginError:(long long)arg1;
- (void)saveCurAccount:(_Bool)arg1 Uin:(unsigned long long)arg2 Nick:(id)arg3 Account:(id)arg4;
- (void)setAuthorization;
@property(retain, nonatomic) NSDate *startAuthTime; // @synthesize startAuthTime=_startAuthTime;
@property(nonatomic) long long step; // @synthesize step=_step;
@property(retain, nonatomic) NSDate *timeCount; // @synthesize timeCount=_timeCount;
- (void)startCountGetIconTime;
- (void)startCountTime;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(retain, nonatomic) NSData *a2; // @dynamic a2;
@property(retain, nonatomic) AuthorizationRequest *auhtotizationIconRequest; // @dynamic auhtotizationIconRequest;
@property(retain, nonatomic) NSArray *authInfoList; // @dynamic authInfoList;
@property(retain, nonatomic) AuthorizationRequest *authorizationRequest; // @dynamic authorizationRequest;
@property(retain, nonatomic) NSData *d2; // @dynamic d2;
@property(nonatomic) unsigned long long d2Key; // @dynamic d2Key;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UIImage *head; // @dynamic head;
@property(nonatomic) _Bool isAutoLogin; // @dynamic isAutoLogin;
@property(nonatomic) _Bool isNeedChangeAccount; // @dynamic isNeedChangeAccount;
@property(retain, nonatomic) NSDictionary *key; // @dynamic key;
@property(nonatomic) _Bool loginA2D2; // @dynamic loginA2D2;
@property(retain, nonatomic) NSDictionary *loginInfoForThirdPart; // @dynamic loginInfoForThirdPart;
@property(retain, nonatomic) NSString *nickName; // @dynamic nickName;
@property(retain, nonatomic) NSData *sKEY; // @dynamic sKEY;
@property(readonly) Class superclass;
@property(nonatomic) long long uin; // @dynamic uin;

@end

