//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SystemAudioService : NSObject
{
    id <audioPlayCompleteDelegate> _delegate;
    int _category;
}

- (void).cxx_destruct;
@property(nonatomic) int category; // @synthesize category=_category;
@property(nonatomic) __weak id <audioPlayCompleteDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned int)soundPlay:(id)arg1 soundPathType:(int)arg2;
- (void)stopPlaySound:(unsigned int)arg1;
- (void)stopVibrate;
- (void)vibratePlay;
- (void)vibratePlay:(int)arg1;

@end

