//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString, UIColor, UIImage, UIImageView, UIView;

@interface TabWithInPageButton : UIButton
{
    UIView *_marker;
    UIImageView *_extraIcon;
    UIImageView *_newIcon;
    NSString *_title;
    _Bool _marked;
    _Bool _pressed;
    _Bool _disableClick;
    UIColor *_normalTitleColor;
    UIColor *_selectedTitleColor;
    UIColor *_disableTitleColor;
    UIImage *_icon;
    _Bool _showNew;
    int _xo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *icon; // @dynamic icon;
- (id)initWithFrame:(struct CGRect)arg1 followTheme:(_Bool)arg2;
- (void)layoutSubviews;
- (void)refreshAppearance;
@property(nonatomic) _Bool disableClick; // @dynamic disableClick;
@property(retain, nonatomic) UIColor *disableTitleColor; // @dynamic disableTitleColor;
@property(nonatomic) _Bool marked; // @dynamic marked;
@property(retain, nonatomic) UIColor *normalTitleColor; // @dynamic normalTitleColor;
@property(nonatomic) _Bool pressed; // @dynamic pressed;
@property(retain, nonatomic) UIColor *selectedTitleColor; // @dynamic selectedTitleColor;
@property(nonatomic) _Bool showNew; // @dynamic showNew;
@property(retain, nonatomic) NSString *title; // @dynamic title;

@end

