//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IQQDBOperationBase.h"

@class NSString;

@interface TBDBTableStoryInfo : NSObject <IQQDBOperationBase>
{
}

- (void)createStoryInfoTable:(id)arg1;
- (void)deleteStoryInfoWithUid:(id)arg1 withPullType:(id)arg2 inDb:(id)arg3;
- (void)deleteStoryInfoWithVid:(id)arg1 inDb:(id)arg2;
- (id)getStoryInfoWithUid:(id)arg1 withPullType:(id)arg2 inDb:(id)arg3;
- (unsigned long long)getTableSign;
- (void)updateStoryInfoWithModel:(id)arg1 withPullType:(id)arg2 withModel:(id)arg3 inDb:(id)arg4;
- (void)updateTable:(id)arg1 inDb:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

