//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface TBDownloadQueueManager : NSObject
{
    long long _maxConcurrentOperationCount;
    NSMutableDictionary *_taskQueue;
    NSMutableArray *_currentDownloadingQueue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)addCurrentDownloadingTask:(id)arg1;
- (void)addDownloadTasks:(id)arg1 withPriority:(int)arg2;
- (id)checkQueueTasksForDownload:(id)arg1 withConcurrentCount:(long long)arg2 withPriority:(int)arg3;
- (void)clearAllTasks;
- (void)clearDownloadTasksQueueWithPriority:(int)arg1;
@property(retain, nonatomic) NSMutableArray *currentDownloadingQueue; // @synthesize currentDownloadingQueue=_currentDownloadingQueue;
- (void)dealloc;
- (void)executionCurrentDownloadingQueque;
- (void)executionTaskQuequeMainThread;
- (id)getExeTaskArrayWithConcurrentCount:(long long)arg1;
- (id)init;
- (void)insertDownloadTasks:(id)arg1 withPriority:(int)arg2;
- (void)insertTasks:(id)arg1 toQueue:(id)arg2;
- (_Bool)isCurrentDownloadingTask:(id)arg1;
@property(nonatomic) long long maxConcurrentOperationCount; // @synthesize maxConcurrentOperationCount=_maxConcurrentOperationCount;
- (void)removeAllTaskFromCurrentDownloadingQueue:(id)arg1;
- (void)removeCurrentDownloadingTask:(id)arg1;
- (void)removeDownloadTasks:(id)arg1;
- (void)removeDownloadTasks:(id)arg1 withPriority:(int)arg2;
@property(retain, nonatomic) NSMutableDictionary *taskQueue; // @synthesize taskQueue=_taskQueue;
- (id)shareDownloadQueue;
- (id)taskWithURL:(id)arg1 destination:(id)arg2 success:(CDUnknownBlockType)arg3 fail:(CDUnknownBlockType)arg4;

@end

