//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSString, TBLineProgressCell, UICollectionView;

@interface TBLineProgress : UIView <UICollectionViewDelegateFlowLayout, UICollectionViewDataSource>
{
    UICollectionView *_collectionView;
    TBLineProgressCell *_curProgressCell;
    double _totalTime;
    double _playedTime;
    unsigned int _totalNum;
    unsigned int _playedNum;
    double _currentTotalTime;
    double _currentPlayedTime;
    unsigned long long _indexSection;
    _Bool _indexStatus;
}

- (void)beginProgressWithPlayedTime:(double)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)dealloc;
- (void)fillProgressCell:(id)arg1 withChange:(_Bool)arg2;
- (void)frameForHeaderForSection;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadIndexPathCell;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)pauseProgress;
- (void)reloadCollectionData;
- (void)setCurProgress;
- (void)setCurrentTotalTime:(double)arg1;
- (void)setIndexPlayNumber:(unsigned int)arg1 withTotalNumber:(unsigned int)arg2;
- (void)showTotalProgress;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

