//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBMultimediaEditComponent.h"

#import "ArtisticFilterScrollViewDelegate.h"
#import "ArtisticFilterViewDelegate.h"

@class ArtisticFilterView, NSString;

@interface TBMultimediaEditArtisticComponent : TBMultimediaEditComponent <ArtisticFilterScrollViewDelegate, ArtisticFilterViewDelegate>
{
    _Bool _isFirstSelected;
    _Bool _isConfirmArtistic;
    float _Max_HeightOrWidth;
    int _status;
    ArtisticFilterView *_artisticfilterview;
    id <TBMultimediaEditArtisticComponentDelegate> _artisticDelegate;
}

- (void).cxx_destruct;
- (void)ArtisticFilterok;
@property(nonatomic) float Max_HeightOrWidth; // @synthesize Max_HeightOrWidth=_Max_HeightOrWidth;
@property(nonatomic) __weak id <TBMultimediaEditArtisticComponentDelegate> artisticDelegate; // @synthesize artisticDelegate=_artisticDelegate;
@property(retain, nonatomic) ArtisticFilterView *artisticfilterview; // @synthesize artisticfilterview=_artisticfilterview;
- (void)buttonClicked;
- (void)clickArtisticFilterCancel:(id)arg1;
- (void)clickArtisticFilterok;
- (void)createArtisticFilterView;
- (void)dealloc;
- (void)dismissArtisticFilter;
- (void)dismissArtisticFilterView;
- (void)getEditActionResult:(id)arg1;
- (void)getPublishInfo:(id)arg1;
- (void)handleArtisticFilterUploadStateNotification:(id)arg1;
- (id)init;
@property(nonatomic) _Bool isConfirmArtistic; // @synthesize isConfirmArtistic=_isConfirmArtistic;
@property(nonatomic) _Bool isFirstSelected; // @synthesize isFirstSelected=_isFirstSelected;
- (void)onResetArtisticFilteredPic:(id)arg1;
- (void)onisConfirmArtistic;
- (void)receiveInfo:(id)arg1;
- (void)recoverGesture;
- (void)reset;
- (void)setImageToCurrentView:(id)arg1;
- (void)setOriginalImageToCurrentView;
@property(nonatomic) int status; // @synthesize status=_status;
- (void)setanimationforview:(_Bool)arg1 view:(id)arg2;
- (id)showArtisticFilterPic:(long long)arg1;
- (void)showArtisticFilterView;
- (void)start;
- (void)stop;
- (void)tapBlankToHidArtisticFilterView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

