//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ITBPBGetData.h"

@class NSArray, NSString, TBShareGroupInfoModel;

@interface TBReqCreateShareGroup : NSObject <ITBPBGetData>
{
    TBShareGroupInfoModel *_shareGroupInfo;
    NSArray *_memberList;
    unsigned long long _createTime;
}

@property(nonatomic) unsigned long long createTime; // @synthesize createTime=_createTime;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)getRequestPBData;
@property(retain, nonatomic) NSArray *memberList; // @synthesize memberList=_memberList;
@property(retain, nonatomic) TBShareGroupInfoModel *shareGroupInfo; // @synthesize shareGroupInfo=_shareGroupInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

