//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ITBPBGetData.h"

@class NSString, TBShareGroupInfoModel;

@interface TBReqEditShareGroup : NSObject <ITBPBGetData>
{
    TBShareGroupInfoModel *_shareGroupInfo;
}

- (void)dealloc;
- (id)getRequestPBData;
@property(retain, nonatomic) TBShareGroupInfoModel *shareGroupInfo; // @synthesize shareGroupInfo=_shareGroupInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

