//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ITBPBParseData.h"

@class NSArray, NSString, TBErrorInfo;

@interface TBRspGetGroupVideoList : NSObject <ITBPBParseData>
{
    unsigned int _isEnd;
    unsigned int _next;
    int _seq;
    TBErrorInfo *_error;
    NSArray *_nodeList;
}

- (void)dealloc;
@property(retain, nonatomic) TBErrorInfo *error; // @synthesize error=_error;
@property(nonatomic) unsigned int isEnd; // @synthesize isEnd=_isEnd;
@property(nonatomic) unsigned int next; // @synthesize next=_next;
@property(retain, nonatomic) NSArray *nodeList; // @synthesize nodeList=_nodeList;
- (_Bool)parsePBData:(char *)arg1 withLength:(int)arg2;
@property(nonatomic) int seq; // @synthesize seq=_seq;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

