//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBRspGeneralModel.h"

@class NSArray, NSString;

@interface TBRspGeneralListModel : TBRspGeneralModel
{
    _Bool _isEnd;
    NSArray *_list;
    NSString *_nextCookie;
}

- (void)dealloc;
- (id)init;
@property(nonatomic) _Bool isEnd; // @synthesize isEnd=_isEnd;
@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
@property(retain, nonatomic) NSString *nextCookie; // @synthesize nextCookie=_nextCookie;
- (_Bool)parsePBData:(char *)arg1 withLength:(int)arg2;

@end

