//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQModel.h"

#import "NSCopying.h"

@interface TBShareGroupExtInfo : QQModel <NSCopying>
{
    _Bool _has_join;
    unsigned int _totalMembers;
    unsigned int _totalVideos;
    unsigned int _ownerType;
}

+ (id)createWithData:(struct CPBMessageDecoder *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)fixWithOldInfo:(id)arg1;
@property(nonatomic) _Bool has_join; // @synthesize has_join=_has_join;
- (_Bool)isValid;
@property(nonatomic) unsigned int ownerType; // @synthesize ownerType=_ownerType;
@property(nonatomic) unsigned int totalMembers; // @synthesize totalMembers=_totalMembers;
@property(nonatomic) unsigned int totalVideos; // @synthesize totalVideos=_totalVideos;

@end

