//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQModel.h"

@class NSString;

@interface TBStoryUsrIcon : QQModel
{
    NSString *_iconPostfix;
    NSString *_jmpPostfix;
}

+ (id)createWithQQStory:(struct CPBMessageDecoder *)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSString *iconPostfix; // @synthesize iconPostfix=_iconPostfix;
- (id)iconURL;
@property(retain, nonatomic) NSString *jmpPostfix; // @synthesize jmpPostfix=_jmpPostfix;
- (id)jumpURL;

@end

