//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBExtendedHitButton.h"

@interface TBStoryPublishCheckView : TBExtendedHitButton
{
    long long _chatBusinessType;
}

+ (id)makeCheckViewWithFrame:(struct CGRect)arg1 richType:(long long)arg2;
- (void)btnDidClicked:(id)arg1;
@property(nonatomic) long long chatBusinessType; // @synthesize chatBusinessType=_chatBusinessType;
- (void)checkSelectedValue:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 config:(id)arg2;
- (_Bool)isChecked;
- (void)saveCheckedValue;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

