//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BDHUploadDelegate.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface TBVideoUpload : NSObject <BDHUploadDelegate>
{
    NSObject<OS_dispatch_queue> *_uploadQueue;
    NSMutableDictionary *_uploadModels;
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)getUploadModelForKey:(id)arg1;
- (id)init;
- (void)notifyBDHCancel:(long long)arg1 uploadDetail:(id)arg2;
- (void)notifyBDHFail:(long long)arg1 uploadDetail:(id)arg2 fail:(id)arg3;
- (void)notifyBDHProgress:(long long)arg1 uploadDetail:(id)arg2 progress:(float)arg3;
- (void)notifyBDHSuccess:(long long)arg1 uploadDetail:(id)arg2;
- (void)p_notifyBDHResult:(long long)arg1 uploadDetail:(id)arg2 fail:(id)arg3;
- (void)publishResultReport:(id)arg1 withBizName:(id)arg2 withFileSize:(unsigned long long)arg3 withErrorInfo:(id)arg4 withVid:(id)arg5;
- (void)remoUploadModelForKey:(id)arg1;
@property(retain) NSMutableDictionary *uploadModels; // @synthesize uploadModels=_uploadModels;
- (void)setUploadMoedel:(id)arg1 forKey:(id)arg2;
- (void)uploadBlock:(id)arg1 withProgress:(double)arg2 withSuccess:(_Bool)arg3 withResult:(id)arg4;
- (void)uploadProgressBlockSuccess:(_Bool)arg1 error:(id)arg2 withSize:(unsigned long long)arg3 startTimeStamp:(unsigned long long)arg4 fileOffset:(id)arg5 uploadPackPercent:(double)arg6 withPath:(id)arg7 withData:(id)arg8;
- (void)uploadVideBDHWithPath:(id)arg1 withSize:(unsigned long long)arg2 withDelegate:(id)arg3 withUserData:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

