//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationBar.h"

@class NSString, UIImage;

@interface UINavigationBar (Custom)
+ (Class)class;
@property(nonatomic) _Bool bUseBasicBackgroundStyle;
@property(nonatomic) long long basicBackgroundStyle;
- (void)reloadAppearance;
- (void)setCurrentThemeAppearance;
- (void)setDefaultThemeAppearance;
@property(retain, nonatomic) UIImage *skinBGImage; // @dynamic skinBGImage;
@property(retain, nonatomic) NSString *skinBackgroundImage; // @dynamic skinBackgroundImage;
@property(retain, nonatomic) NSString *skinShadowImage; // @dynamic skinShadowImage;
@end

