//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UserInfoBaseView.h"

@class QQInfoLabel;

@interface UserInfoItem : UserInfoBaseView
{
    QQInfoLabel *_title;
    QQInfoLabel *_content;
    _Bool _needOnEdgeLine;
    _Bool _needLowerEdgeLine;
}

- (void).cxx_destruct;
@property(retain, nonatomic) QQInfoLabel *content; // @synthesize content=_content;
- (void)drawRect:(struct CGRect)arg1;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setDescribeViewNeedCopied:(_Bool)arg1;
- (double)setItemContent:(id)arg1 cotent:(id)arg2;
- (void)setOnAndLowerEdgeLine:(_Bool)arg1 lowerEdgeLine:(_Bool)arg2;
@property(retain, nonatomic) QQInfoLabel *title; // @synthesize title=_title;

@end

