//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UserSummaryBaseCell.h"

@class NSMutableArray, PrivilegeBaseInfoModel, UILabel;

@interface UserSummaryOtherVipBizCell : UserSummaryBaseCell
{
    UILabel *_simpleTextLabel;
    NSMutableArray *_iconViewArr;
    PrivilegeBaseInfoModel *_privilegeBaseInfoModel;
    _Bool _isMaster;
}

+ (float)heightForPrivilegeBaseInfo:(id)arg1 isMaster:(_Bool)arg2;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)showAllCloseLabel;
- (void)showVipBizIcons;
- (void)updateWithPrivilegeBaseInfo:(id)arg1 isMaster:(_Bool)arg2;

@end

