//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureDevice, AVCaptureDeviceInput, AVCaptureSession, AVCaptureVideoDataOutput, NSString;

@interface VideoCapture : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    AVCaptureVideoDataOutput *_videoOutput;
    long long _frameRate;
    struct dispatch_queue_s *_cameraProcessingQueue;
    AVCaptureSession *_captureSession;
    AVCaptureDevice *_inputCamera;
    AVCaptureDeviceInput *_videoInput;
    id <VideoCaptureDelegate> videoDelegate;
}

- (id)backFacingCamera;
- (id)cameraWithPosition:(long long)arg1;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
- (void)dealloc;
- (id)frontFacingCamera;
- (id)initPreset:(id)arg1 Format:(int)arg2 Fps:(int)arg3 Discard:(_Bool)arg4 position:(long long)arg5;
- (_Bool)isFrontCamera;
- (void)releaseVideo;
- (void)setCamera:(_Bool)arg1;
- (void)setCaptureFrameRate:(int)arg1;
- (void)setDelegate:(id)arg1;
- (void)setFps:(int)arg1;
- (void)setPreset:(id)arg1;
@property(retain, nonatomic) AVCaptureDeviceInput *videoInput; // @synthesize videoInput=_videoInput;
@property(retain, nonatomic) AVCaptureVideoDataOutput *videoOutput; // @synthesize videoOutput=_videoOutput;
- (void)startCapture;
- (void)stopCapture;
- (void)swapFrontAndBackCameras;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

