//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEngineDispatchDelegate.h"
#import "ISCBusinessCallback.h"
#import "ISCListenerCallback.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface VoiceChangeManager : NSObject <IEngineDispatchDelegate, ISCBusinessCallback, ISCListenerCallback>
{
    NSObject<OS_dispatch_queue> *_voiceChangeQueue;
    NSMutableArray *_voiceChangeModels;
    _Bool _isAuthRequesting;
}

+ (id)getInstance;
- (_Bool)canUpdate:(unsigned long long)arg1 scid:(id)arg2;
- (_Bool)createSourcePathIfNoExist:(id)arg1;
- (void)dealloc;
- (_Bool)deleteFiles:(unsigned long long)arg1 scid:(id)arg2;
- (void)didRecievedMsg:(CDStruct_7895f40e)arg1;
- (void)downloadVoiceChangeJsonIfNotEXist;
- (id)getDisplayVoiceChangeModels;
- (_Bool)getItem:(unsigned long long)arg1 scid:(id)arg2 info:(id)arg3;
- (id)init;
- (void)initVoiceChangeModels;
- (_Bool)isFileExists:(unsigned long long)arg1 scid:(id)arg2;
- (_Bool)isVoiceChangeJsonExist;
- (void)notifyError:(id)arg1;
- (void)onCompleted:(unsigned long long)arg1 scid:(id)arg2 cfgScid:(id)arg3 from:(id)arg4 result:(int)arg5 httpcode:(int)arg6;
- (void)parseJsonFile;
- (void)requestVoiceChangeAuth:(unsigned int)arg1;
- (void)syncVoiceChangeModelsToLocal;
- (id)voiceChangeJsonPath;
- (id)voiceChangeModelPath;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

