//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CloudHTTPRequestDelegate.h"

@class NSData, NSFileHandle, NSString, WYHTTPRequest, WYUploadTaskInfo;

@interface WYUploadHTTPRequest : NSObject <CloudHTTPRequestDelegate>
{
    WYUploadTaskInfo *_taskInfo;
    unsigned long long _dataOffset;
    unsigned long long _speed;
    double _lastTime;
    unsigned long long _lastSize;
    WYHTTPRequest *_request;
    NSString *_path;
    NSFileHandle *_handle;
    unsigned long long _size;
    NSData *_data;
    NSData *_sha;
    NSData *_checkKey;
    id <WYUploadRequestDelegate> _delegate;
}

- (id)buildUploadData;
- (void)cancel;
@property(retain, nonatomic) NSData *checkKey; // @synthesize checkKey=_checkKey;
- (void)cloudHTTPRequest:(id)arg1 didFaileWithErrorCode:(long long)arg2;
- (void)cloudHTTPRequest:(id)arg1 didReceiveData:(id)arg2;
- (id)cloudHTTPRequestBody:(id)arg1;
- (void)cloudHTTPRequestDidFinished:(id)arg1;
- (unsigned long long)cloudHTTPRequestMaxRetryCount:(id)arg1;
- (id)cloudHTTPRequestMethod:(id)arg1;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (unsigned long long)dataLen;
@property(nonatomic) unsigned long long dataOffset; // @synthesize dataOffset=_dataOffset;
- (void)dealloc;
@property(nonatomic) id <WYUploadRequestDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned long long)getUploadBlockSize;
- (id)getUploadData;
@property(retain, nonatomic) NSFileHandle *handle; // @synthesize handle=_handle;
- (id)initWithSHA:(id)arg1 host:(id)arg2 port:(long long)arg3 checkKey:(id)arg4 delegate:(id)arg5;
- (id)initWithUploadData:(id)arg1 sha:(id)arg2 host:(id)arg3 port:(long long)arg4 checkKey:(id)arg5 delegate:(id)arg6;
- (id)initWithUploadPath:(id)arg1 size:(unsigned long long)arg2 sha:(id)arg3 host:(id)arg4 port:(long long)arg5 checkKey:(id)arg6 delegate:(id)arg7;
@property(nonatomic) unsigned long long lastSize; // @synthesize lastSize=_lastSize;
@property(nonatomic) double lastTime; // @synthesize lastTime=_lastTime;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
@property(retain, nonatomic) WYHTTPRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) NSData *sha; // @synthesize sha=_sha;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(nonatomic) unsigned long long speed; // @synthesize speed=_speed;
@property(retain, nonatomic) WYUploadTaskInfo *taskInfo; // @synthesize taskInfo=_taskInfo;
- (void)start;
- (void)taskDidCanceled;
- (void)taskDidFailedWithError:(id)arg1;
- (void)taskDidFinished;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

